# Generated by Django 6.0.6 on 2026-09-04 16:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_and_backfill(apps, schema_editor):
    """Seed the controlled currency catalogue for fresh serial-only installs."""
    Currency = apps.get_model("tenancy", "Currency")
    Company = apps.get_model("tenancy", "Company")

    from tenancy.currencies import seed_currency_catalogue

    seed_currency_catalogue(Currency)
    Company.objects.filter(base_currency__isnull=True).update(
        base_currency_id="PKR",
        tax_environment="non_tax",
    )


def mark_existing_ready(apps, schema_editor):
    """Preserve the original provisioning-state backfill semantics."""
    Company = apps.get_model("tenancy", "Company")
    Company.objects.update(
        provisioning_state="ready",
        provisioning_error_code="",
    )

class Migration(migrations.Migration):
    # Checkpoint 4B: the replaced files are gone and `replaces` is removed, so
    # this is now an ordinary initial migration. Databases that recorded the
    # original chain already carry this migration's own record, written by
    # Django's check_replacements() during the 4A release, so it is a no-op for
    # them; the stale rows are removed by the separately approved
    # `migrate --prune`.


    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('schema_name', models.CharField(blank=True, help_text='Auto-generated PostgreSQL schema name (tenant_company_<id>).', max_length=63, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive companies cannot have their schema activated for requests.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_suspended', models.BooleanField(default=False, help_text='Manual override: immediately block every user of this company, regardless of the paid-until date. Recording a payment lifts it.')),
                ('paid_until', models.DateField(blank=True, help_text='Subscription is paid up to this date (inclusive). Leave empty to disable subscription enforcement for this company.', null=True)),
                ('grace_days', models.PositiveSmallIntegerField(default=3, help_text='Days of continued access after the paid-until date before the company is blocked automatically.')),
                ('warn_days_before', models.PositiveSmallIntegerField(default=7, help_text="Show the company's users a renewal warning banner this many days before the paid-until date.")),
                ('contact_email', models.EmailField(blank=True, help_text="The company's billing email. Subscription expiry/suspension notifications are sent here (not to individual users). Leave empty to skip email notifications for this company.", max_length=254)),
                ('disabled_features', models.JSONField(blank=True, default=list, help_text='Feature keys switched off for this company.')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'tenancy_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'db_table': 'tenancy_membership',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_received', models.DateField(default=datetime.date.today, help_text='The day the money actually arrived.')),
                ('months_covered', models.PositiveSmallIntegerField(default=1, help_text='How many months of service this payment buys.')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('paid_until_after', models.DateField(editable=False, help_text="The company's paid-until date right after this payment was applied.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='tenancy.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenancy_subscription_payment',
                'verbose_name': 'Subscription payment',
                'verbose_name_plural': 'Subscription payments',
                'ordering': ['-date_received', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='Financee', help_text='Display name on outgoing emails.', max_length=100)),
                ('sender_email', models.EmailField(blank=True, help_text='The email account subscription notifications are sent from.', max_length=254)),
                ('app_password', models.CharField(blank=True, help_text='SMTP app password for the sender account (e.g. a Gmail app password).', max_length=128)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('emails_enabled', models.BooleanField(default=True, help_text='Master switch: untick to stop all subscription emails.')),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number clients should message about payments (e.g. +92 300 1234567).', max_length=32)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_note', models.CharField(blank=True, help_text='Optional extra line shown in emails (e.g. office hours, bank account).', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenancy_billing_settings',
                'verbose_name': 'Billing & email settings',
                'verbose_name_plural': 'Billing & email settings',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('expired', 'Subscription expired (grace notice)'), ('suspended', 'Access suspended'), ('manual_suspension', 'Access suspended (manual)'), ('test', 'Test email')], max_length=24)),
                ('to_email', models.EmailField(max_length=254)),
                ('paid_until', models.DateField(blank=True, help_text='The billing cycle this email belongs to (dedup key).', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_emails', to='tenancy.company')),
            ],
            options={
                'db_table': 'tenancy_subscription_email_log',
                'verbose_name': 'Subscription email',
                'verbose_name_plural': 'Subscription emails',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind__in', ['expired', 'suspended']), ('paid_until__isnull', False)), fields=('company', 'kind', 'paid_until'), name='uniq_subscription_email_per_cycle')],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=12)),
                ('minor_units', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'tenancy_currency',
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z]{3}$')), name='tenancy_currency_valid_code'), models.CheckConstraint(condition=models.Q(('minor_units__lte', 4)), name='tenancy_currency_valid_minor_units')],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='base_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='tenancy.currency'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_environment',
            field=models.CharField(choices=[('non_tax', 'Non-tax'), ('tax', 'Tax-based')], default='non_tax', help_text='Choose whether this company operates in a tax-based or non-tax environment. It can be changed only before financial activity.', max_length=16),
        ),
        migrations.RunPython(
            code=seed_and_backfill,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='company',
            name='base_currency',
            field=models.ForeignKey(default='PKR', help_text='Accounting and reporting currency. It can be changed only before the company has financial activity.', on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='tenancy.currency'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('tax_environment__in', ['tax', 'non_tax'])), name='tenancy_company_valid_tax_environment'),
        ),
        migrations.AddField(
            model_name='company',
            name='provisioning_error_code',
            field=models.CharField(blank=True, help_text='Sanitized provisioning failure category; never contains SQL or secrets.', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='provisioning_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='Operational state of the physical tenant schema.', max_length=16),
        ),
        migrations.RunPython(
            code=mark_existing_ready,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('provisioning_state__in', ['pending', 'provisioning', 'ready', 'failed'])), name='tenancy_company_valid_provisioning_state'),
        ),
    ]
