-- Phase 19 shared financial modules and universal period close, quantity v15.
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM tenant_schema_metadata WHERE id=true AND family='quantity' AND version>=14)
 THEN RAISE EXCEPTION 'Quantity financial rollout refused: family/version mismatch.'; END IF;
END $$;

CREATE OR REPLACE VIEW chartofaccounts AS SELECT * FROM chart_of_accounts;
CREATE OR REPLACE VIEW journalentries AS SELECT journal_id,entry_date AS journal_date,
 entry_date,description,source_document_type,source_document_id,
 source_document_number,status,created_by,created_at FROM journal_entries;
CREATE OR REPLACE VIEW journallines AS SELECT * FROM journal_lines;

CREATE TABLE IF NOT EXISTS parties(
 party_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 party_name varchar(200) NOT NULL UNIQUE,party_type varchar(20) NOT NULL,
 contact_info text,address text,opening_balance numeric(24,4) NOT NULL DEFAULT 0,
 balance_type varchar(6) NOT NULL DEFAULT 'Debit',
 ar_account_id bigint REFERENCES chart_of_accounts(account_id),
 ap_account_id bigint REFERENCES chart_of_accounts(account_id),
 expense_account_id bigint REFERENCES chart_of_accounts(account_id),
 opening_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
 is_cash boolean NOT NULL DEFAULT false,is_active boolean NOT NULL DEFAULT true,
 created_by integer,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK(btrim(party_name)<>''),CHECK(party_type IN('Customer','Vendor','Both','Expense')),
 CHECK(opening_balance>=0),CHECK(balance_type IN('Debit','Credit')));
ALTER TABLE journal_lines DROP CONSTRAINT IF EXISTS journal_lines_party_id_fkey;
ALTER TABLE journal_lines ADD CONSTRAINT journal_lines_party_id_fkey FOREIGN KEY(party_id) REFERENCES parties(party_id);

CREATE TABLE IF NOT EXISTS payments(
 payment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,payment_date date NOT NULL,
 party_id bigint NOT NULL REFERENCES parties(party_id),amount numeric(24,4) NOT NULL,
 method varchar(20) NOT NULL DEFAULT 'Cash',reference_no varchar(100),description text,
 journal_id bigint NOT NULL UNIQUE REFERENCES journal_entries(journal_id),
 status varchar(10) NOT NULL DEFAULT 'posted',created_by integer,created_at timestamptz NOT NULL DEFAULT now(),
 CHECK(amount>0),CHECK(method IN('Cash','Bank','Cheque','Online')),CHECK(status IN('posted','reversed')));
CREATE TABLE IF NOT EXISTS receipts(
 receipt_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,receipt_date date NOT NULL,
 party_id bigint NOT NULL REFERENCES parties(party_id),amount numeric(24,4) NOT NULL,
 method varchar(20) NOT NULL DEFAULT 'Cash',reference_no varchar(100),description text,
 journal_id bigint NOT NULL UNIQUE REFERENCES journal_entries(journal_id),
 status varchar(10) NOT NULL DEFAULT 'posted',created_by integer,created_at timestamptz NOT NULL DEFAULT now(),
 CHECK(amount>0),CHECK(method IN('Cash','Bank','Cheque','Online')),CHECK(status IN('posted','reversed')));
CREATE TABLE IF NOT EXISTS contra_entries(
 contra_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,contra_date date NOT NULL,
 from_party_id bigint NOT NULL REFERENCES parties(party_id),to_party_id bigint NOT NULL REFERENCES parties(party_id),
 amount numeric(24,4) NOT NULL,method varchar(20) NOT NULL DEFAULT 'Cash',
 reference_no varchar(100),description text,journal_id bigint NOT NULL UNIQUE REFERENCES journal_entries(journal_id),
 status varchar(10) NOT NULL DEFAULT 'posted',created_by integer,created_at timestamptz NOT NULL DEFAULT now(),
 CHECK(from_party_id<>to_party_id),CHECK(amount>0),CHECK(status IN('posted','reversed')));
CREATE TABLE IF NOT EXISTS opening_cash(
 opening_cash_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,amount numeric(24,4) NOT NULL DEFAULT 0,
 journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),created_by integer,updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK(amount>=0));
CREATE TABLE IF NOT EXISTS owner_equity_transactions(
 txn_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,txn_date date NOT NULL,
 direction varchar(12) NOT NULL,amount numeric(24,4) NOT NULL,
 equity_account_id bigint NOT NULL REFERENCES chart_of_accounts(account_id),description text,
 journal_id bigint NOT NULL UNIQUE REFERENCES journal_entries(journal_id),
 status varchar(10) NOT NULL DEFAULT 'posted',created_by integer,created_at timestamptz NOT NULL DEFAULT now(),
 CHECK(direction IN('injection','withdrawal')),CHECK(amount>0),CHECK(status IN('posted','reversed')));
CREATE TABLE IF NOT EXISTS period_closes(
 period_close_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 period_year integer NOT NULL,period_month integer NOT NULL,closed_at timestamptz NOT NULL DEFAULT now(),
 closed_by integer,UNIQUE(period_year,period_month),CHECK(period_year BETWEEN 2000 AND 9999),
 CHECK(period_month BETWEEN 1 AND 12));

CREATE OR REPLACE FUNCTION quantity_assert_open_date(p_date date) RETURNS void LANGUAGE plpgsql STABLE AS $$
BEGIN
 IF p_date IS NULL THEN RAISE EXCEPTION 'Transaction date is required.'; END IF;
 IF EXISTS(SELECT 1 FROM period_closes WHERE period_year=extract(year FROM p_date)
 AND period_month=extract(month FROM p_date)) THEN
  RAISE EXCEPTION 'Accounting period is closed for %.',p_date USING ERRCODE='check_violation';
 END IF;
END $$;
CREATE OR REPLACE FUNCTION quantity_period_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE d date;r jsonb;k text;
BEGIN
 IF current_setting('financee.period_close_admin',true)='allowed' THEN RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END; END IF;
 IF TG_OP='DELETE' THEN r:=to_jsonb(OLD);ELSE r:=to_jsonb(NEW);END IF;
 k:=CASE TG_TABLE_NAME WHEN 'journal_entries' THEN 'entry_date'
 WHEN 'warehouse_transfers' THEN 'transfer_date' WHEN 'physical_counts' THEN 'count_date'
 WHEN 'opening_stock_documents' THEN 'opening_date' END;
 d:=(r->>k)::date;
 PERFORM quantity_assert_open_date(d);RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
END $$;
DROP TRIGGER IF EXISTS quantity_period_journal_guard ON journal_entries;
CREATE TRIGGER quantity_period_journal_guard BEFORE INSERT OR UPDATE OR DELETE ON journal_entries FOR EACH ROW EXECUTE FUNCTION quantity_period_guard();
DROP TRIGGER IF EXISTS quantity_period_transfer_guard ON warehouse_transfers;
CREATE TRIGGER quantity_period_transfer_guard BEFORE INSERT OR UPDATE OR DELETE ON warehouse_transfers FOR EACH ROW EXECUTE FUNCTION quantity_period_guard();
DROP TRIGGER IF EXISTS quantity_period_count_guard ON physical_counts;
CREATE TRIGGER quantity_period_count_guard BEFORE INSERT OR UPDATE OR DELETE ON physical_counts FOR EACH ROW EXECUTE FUNCTION quantity_period_guard();
DROP TRIGGER IF EXISTS quantity_period_opening_guard ON opening_stock_documents;
CREATE TRIGGER quantity_period_opening_guard BEFORE INSERT OR UPDATE OR DELETE ON opening_stock_documents FOR EACH ROW EXECUTE FUNCTION quantity_period_guard();

CREATE OR REPLACE FUNCTION add_party_from_json(data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE id bigint;nm text;typ text;amt numeric;bt text;usr integer;j bigint;ar bigint;ap bigint;exp bigint;code text;
BEGIN
 nm:=upper(btrim(COALESCE(data->>'party_name','')));typ:=data->>'party_type';
 amt:=COALESCE(NULLIF(data->>'opening_balance','')::numeric,0);bt:=COALESCE(NULLIF(data->>'balance_type',''),'Debit');
 usr:=NULLIF(data->>'created_by_id','')::integer;
 IF nm='' OR typ NOT IN('Customer','Vendor','Both','Expense') OR amt<0 OR bt NOT IN('Debit','Credit')
 THEN RAISE EXCEPTION 'Party values are invalid.' USING ERRCODE='check_violation'; END IF;
 SELECT account_id INTO ar FROM chart_of_accounts WHERE account_code='1200';
 SELECT account_id INTO ap FROM chart_of_accounts WHERE account_code='2000';
 IF typ='Expense' THEN
  code:='E'||lpad(nextval('parties_party_id_seq')::text,10,'0');
  INSERT INTO chart_of_accounts(account_code,account_name,account_type,normal_balance,is_system)
  VALUES(code,nm,'Expense','Debit',false) RETURNING account_id INTO exp;
  INSERT INTO parties(party_id,party_name,party_type,contact_info,address,opening_balance,balance_type,expense_account_id,created_by)
  VALUES(currval('parties_party_id_seq'),nm,typ,data->>'contact_info',data->>'address',amt,bt,exp,usr) RETURNING party_id INTO id;
 ELSE
  INSERT INTO parties(party_name,party_type,contact_info,address,opening_balance,balance_type,ar_account_id,ap_account_id,created_by)
  VALUES(nm,typ,data->>'contact_info',data->>'address',amt,bt,
  CASE WHEN typ IN('Customer','Both') THEN ar END,CASE WHEN typ IN('Vendor','Both') THEN ap END,usr)
  RETURNING party_id INTO id;
 END IF;
 IF amt>0 THEN
  j:=quantity_post_journal(CURRENT_DATE,'Party opening balance','party_opening',id,nm,usr,
  jsonb_build_array(jsonb_build_object('account_code',CASE WHEN typ='Expense' THEN code
  WHEN typ='Vendor' OR (typ='Both' AND bt='Credit') THEN '2000' ELSE '1200' END,
  'party_id',id,'debit',CASE WHEN bt='Debit' THEN amt ELSE 0 END,'credit',CASE WHEN bt='Credit' THEN amt ELSE 0 END),
  jsonb_build_object('account_code','3001','debit',CASE WHEN bt='Credit' THEN amt ELSE 0 END,
  'credit',CASE WHEN bt='Debit' THEN amt ELSE 0 END)));
  UPDATE parties SET opening_journal_id=j WHERE party_id=id;
 END IF;
 RETURN jsonb_build_object('status','success','party_id',id,'party_name',nm);
END $$;

CREATE OR REPLACE FUNCTION update_party_from_json(p_id bigint,data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE p parties%ROWTYPE;nm text;amt numeric;bt text;usr integer;j bigint;party_code text;
BEGIN SELECT * INTO p FROM parties WHERE party_id=p_id FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Party not found.'; END IF;
 nm:=upper(btrim(COALESCE(NULLIF(data->>'party_name',''),p.party_name)));
 amt:=COALESCE(NULLIF(data->>'opening_balance','')::numeric,p.opening_balance);
 bt:=COALESCE(NULLIF(data->>'balance_type',''),p.balance_type);usr:=NULLIF(data->>'created_by_id','')::integer;
 IF p.opening_journal_id IS NOT NULL THEN PERFORM quantity_reverse_journal(p.opening_journal_id,CURRENT_DATE,'Revise party opening',usr); END IF;
 j:=NULL;
 IF p.party_type='Expense' THEN SELECT account_code INTO party_code FROM chart_of_accounts WHERE account_id=p.expense_account_id;
 ELSIF p.party_type='Vendor' OR (p.party_type='Both' AND bt='Credit') THEN party_code:='2000';ELSE party_code:='1200';END IF;
 IF amt>0 THEN j:=quantity_post_journal(CURRENT_DATE,'Party opening balance','party_opening_revision',p_id,nm,usr,
 jsonb_build_array(jsonb_build_object('account_code',party_code,
 'party_id',p_id,'debit',CASE WHEN bt='Debit' THEN amt ELSE 0 END,'credit',CASE WHEN bt='Credit' THEN amt ELSE 0 END),
 jsonb_build_object('account_code','3001','debit',CASE WHEN bt='Credit' THEN amt ELSE 0 END,
 'credit',CASE WHEN bt='Debit' THEN amt ELSE 0 END))); END IF;
 UPDATE parties SET party_name=nm,contact_info=COALESCE(data->>'contact_info',contact_info),
 address=COALESCE(data->>'address',address),opening_balance=amt,balance_type=bt,
 opening_journal_id=j,updated_at=now() WHERE party_id=p_id;
 RETURN jsonb_build_object('status','success','party_id',p_id,'party_name',nm);
END $$;

CREATE OR REPLACE FUNCTION get_party_by_name(p_name text) RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT COALESCE(jsonb_agg(to_jsonb(p) ORDER BY party_id),'[]'::jsonb) FROM parties p WHERE upper(party_name)=upper(p_name) $$;
CREATE OR REPLACE FUNCTION get_parties_json() RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT COALESCE(jsonb_agg(to_jsonb(p) ORDER BY party_name),'[]'::jsonb) FROM parties p WHERE is_active $$;
CREATE OR REPLACE FUNCTION get_party_balance_by_name(p_name text) RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT COALESCE((SELECT jsonb_build_object('found',true,'party_id',p.party_id,'party_name',p.party_name,
 'party_type',p.party_type,'balance',COALESCE(sum(jl.debit-jl.credit),0))
 FROM parties p LEFT JOIN journal_lines jl ON jl.party_id=p.party_id WHERE upper(p.party_name)=upper(p_name)
 GROUP BY p.party_id),jsonb_build_object('found',false,'party_name',p_name)) $$;
CREATE OR REPLACE FUNCTION get_party_balances_json() RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT COALESCE(jsonb_agg(jsonb_build_object('party_id',p.party_id,'party_name',p.party_name,
 'party_type',p.party_type,'balance',COALESCE(x.balance,0)) ORDER BY p.party_name),'[]'::jsonb)
 FROM parties p LEFT JOIN(SELECT party_id,sum(debit-credit) balance FROM journal_lines GROUP BY party_id)x USING(party_id)
 WHERE p.party_type<>'Expense' AND p.is_active $$;
CREATE OR REPLACE FUNCTION get_expense_party_balances_json() RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT COALESCE(jsonb_agg(jsonb_build_object('party_id',party_id,'party_name',party_name,
 'balance',opening_balance) ORDER BY party_name),'[]'::jsonb) FROM parties WHERE party_type='Expense' AND is_active $$;

CREATE OR REPLACE FUNCTION quantity_cash_account(p_method text) RETURNS varchar LANGUAGE sql IMMUTABLE AS $$
 SELECT CASE WHEN lower(COALESCE(p_method,'cash'))='cash' THEN '1000' ELSE '1100' END $$;
CREATE OR REPLACE FUNCTION make_payment(data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE id bigint;p parties%ROWTYPE;amt numeric;d date;m text;j bigint;usr integer;
BEGIN SELECT * INTO p FROM parties WHERE upper(party_name)=upper(data->>'party_name');
 amt:=(data->>'amount')::numeric;d:=COALESCE(NULLIF(data->>'payment_date','')::date,CURRENT_DATE);
 m:=COALESCE(NULLIF(data->>'method',''),'Cash');usr:=NULLIF(data->>'created_by_id','')::integer;
 IF NOT FOUND OR amt<=0 THEN RAISE EXCEPTION 'Payment party or amount is invalid.' USING ERRCODE='check_violation'; END IF;
 id:=nextval('payments_payment_id_seq');
 j:=quantity_post_journal(d,'Payment to '||p.party_name,'payment',id,data->>'reference_no',usr,
 jsonb_build_array(jsonb_build_object('account_code','2000','party_id',p.party_id,'debit',amt,'credit',0),
 jsonb_build_object('account_code',quantity_cash_account(m),'debit',0,'credit',amt)));
 INSERT INTO payments(payment_id,payment_date,party_id,amount,method,reference_no,description,journal_id,created_by)
 VALUES(id,d,p.party_id,amt,m,data->>'reference_no',data->>'description',j,usr);
 RETURN jsonb_build_object('status','success','payment_id',id,'journal_id',j);END $$;
CREATE OR REPLACE FUNCTION make_receipt(data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE id bigint;p parties%ROWTYPE;amt numeric;d date;m text;j bigint;usr integer;
BEGIN SELECT * INTO p FROM parties WHERE upper(party_name)=upper(data->>'party_name');
 amt:=(data->>'amount')::numeric;d:=COALESCE(NULLIF(data->>'receipt_date','')::date,CURRENT_DATE);
 m:=COALESCE(NULLIF(data->>'method',''),'Cash');usr:=NULLIF(data->>'created_by_id','')::integer;
 IF NOT FOUND OR amt<=0 THEN RAISE EXCEPTION 'Receipt party or amount is invalid.' USING ERRCODE='check_violation'; END IF;
 id:=nextval('receipts_receipt_id_seq');
 j:=quantity_post_journal(d,'Receipt from '||p.party_name,'receipt',id,data->>'reference_no',usr,
 jsonb_build_array(jsonb_build_object('account_code',quantity_cash_account(m),'debit',amt,'credit',0),
 jsonb_build_object('account_code','1200','party_id',p.party_id,'debit',0,'credit',amt)));
 INSERT INTO receipts(receipt_id,receipt_date,party_id,amount,method,reference_no,description,journal_id,created_by)
 VALUES(id,d,p.party_id,amt,m,data->>'reference_no',data->>'description',j,usr);
 RETURN jsonb_build_object('status','success','receipt_id',id,'journal_id',j);END $$;
CREATE OR REPLACE FUNCTION make_contra(data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE id bigint;fp parties%ROWTYPE;tp parties%ROWTYPE;amt numeric;d date;j bigint;usr integer;
BEGIN SELECT * INTO fp FROM parties WHERE upper(party_name)=upper(data->>'from_party_name');
 SELECT * INTO tp FROM parties WHERE upper(party_name)=upper(data->>'to_party_name');
 amt:=(data->>'amount')::numeric;d:=COALESCE(NULLIF(data->>'contra_date','')::date,CURRENT_DATE);
 usr:=NULLIF(data->>'created_by_id','')::integer;
 IF fp.party_id IS NULL OR tp.party_id IS NULL OR fp.party_id=tp.party_id THEN
 RAISE EXCEPTION 'Contra parties cannot be the same or missing.' USING ERRCODE='check_violation'; END IF;
 IF amt<=0 THEN RAISE EXCEPTION 'Contra amount is invalid.' USING ERRCODE='check_violation'; END IF;
 id:=nextval('contra_entries_contra_id_seq');
 j:=quantity_post_journal(d,'Contra '||fp.party_name||' to '||tp.party_name,'contra',id,data->>'reference_no',usr,
 jsonb_build_array(jsonb_build_object('account_code','1200','party_id',tp.party_id,'debit',amt,'credit',0),
 jsonb_build_object('account_code','1200','party_id',fp.party_id,'debit',0,'credit',amt)));
 INSERT INTO contra_entries(contra_id,contra_date,from_party_id,to_party_id,amount,reference_no,description,journal_id,created_by)
 VALUES(id,d,fp.party_id,tp.party_id,amt,data->>'reference_no',data->>'description',j,usr);
 RETURN jsonb_build_object('status','success','contra_id',id,'journal_id',j);END $$;

CREATE OR REPLACE FUNCTION quantity_reverse_financial(p_kind text,p_id bigint) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE j bigint;d date;usr integer;
BEGIN
 IF p_kind='payment' THEN SELECT journal_id,payment_date,created_by INTO j,d,usr FROM payments WHERE payment_id=p_id AND status='posted' FOR UPDATE;
 ELSIF p_kind='receipt' THEN SELECT journal_id,receipt_date,created_by INTO j,d,usr FROM receipts WHERE receipt_id=p_id AND status='posted' FOR UPDATE;
 ELSE SELECT journal_id,contra_date,created_by INTO j,d,usr FROM contra_entries WHERE contra_id=p_id AND status='posted' FOR UPDATE; END IF;
 IF j IS NULL THEN RAISE EXCEPTION 'Financial document not found.'; END IF;
 PERFORM quantity_reverse_journal(j,d,'Reverse '||p_kind,usr);
 IF p_kind='payment' THEN UPDATE payments SET status='reversed' WHERE payment_id=p_id;
 ELSIF p_kind='receipt' THEN UPDATE receipts SET status='reversed' WHERE receipt_id=p_id;
 ELSE UPDATE contra_entries SET status='reversed' WHERE contra_id=p_id; END IF;
 RETURN jsonb_build_object('status','success','id',p_id);END $$;
CREATE OR REPLACE FUNCTION delete_payment(p_id bigint) RETURNS jsonb LANGUAGE sql AS $$SELECT quantity_reverse_financial('payment',p_id)$$;
CREATE OR REPLACE FUNCTION delete_receipt(p_id bigint) RETURNS jsonb LANGUAGE sql AS $$SELECT quantity_reverse_financial('receipt',p_id)$$;
CREATE OR REPLACE FUNCTION delete_contra(p_id bigint) RETURNS jsonb LANGUAGE sql AS $$SELECT quantity_reverse_financial('contra',p_id)$$;
CREATE OR REPLACE FUNCTION update_payment(p_id bigint,data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE old payments%ROWTYPE;r jsonb;BEGIN SELECT * INTO old FROM payments WHERE payment_id=p_id AND status='posted';
 IF NOT FOUND THEN RAISE EXCEPTION 'Payment not found.'; END IF;PERFORM quantity_reverse_financial('payment',p_id);
 data:=data||jsonb_build_object('party_name',(SELECT party_name FROM parties WHERE party_id=old.party_id),
 'payment_date',COALESCE(data->>'payment_date',old.payment_date::text),'method',COALESCE(data->>'method',old.method),
 'created_by_id',old.created_by);r:=make_payment(data);RETURN r||jsonb_build_object('replaced_payment_id',p_id);END $$;
CREATE OR REPLACE FUNCTION update_receipt(p_id bigint,data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE old receipts%ROWTYPE;r jsonb;BEGIN SELECT * INTO old FROM receipts WHERE receipt_id=p_id AND status='posted';
 IF NOT FOUND THEN RAISE EXCEPTION 'Receipt not found.'; END IF;PERFORM quantity_reverse_financial('receipt',p_id);
 data:=data||jsonb_build_object('party_name',(SELECT party_name FROM parties WHERE party_id=old.party_id),
 'receipt_date',COALESCE(data->>'receipt_date',old.receipt_date::text),'method',COALESCE(data->>'method',old.method),
 'created_by_id',old.created_by);r:=make_receipt(data);RETURN r||jsonb_build_object('replaced_receipt_id',p_id);END $$;
CREATE OR REPLACE FUNCTION update_contra(p_id bigint,data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE old contra_entries%ROWTYPE;r jsonb;BEGIN SELECT * INTO old FROM contra_entries WHERE contra_id=p_id AND status='posted';
 IF NOT FOUND THEN RAISE EXCEPTION 'Contra not found.'; END IF;PERFORM quantity_reverse_financial('contra',p_id);
 data:=data||jsonb_build_object('from_party_name',(SELECT party_name FROM parties WHERE party_id=old.from_party_id),
 'to_party_name',(SELECT party_name FROM parties WHERE party_id=old.to_party_id),
 'contra_date',COALESCE(data->>'contra_date',old.contra_date::text),'created_by_id',old.created_by);
 r:=make_contra(data);RETURN r||jsonb_build_object('replaced_contra_id',p_id);END $$;

CREATE OR REPLACE FUNCTION get_payment_details(p_id bigint) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT to_jsonb(x) FROM(SELECT py.*,p.party_name FROM payments py JOIN parties p USING(party_id) WHERE payment_id=p_id)x$$;
CREATE OR REPLACE FUNCTION get_receipt_details(p_id bigint) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT to_jsonb(x) FROM(SELECT r.*,p.party_name FROM receipts r JOIN parties p USING(party_id) WHERE receipt_id=p_id)x$$;
CREATE OR REPLACE FUNCTION get_contra_details(p_id bigint) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT to_jsonb(x) FROM(SELECT c.*,fp.party_name from_party_name,tp.party_name to_party_name FROM contra_entries c JOIN parties fp ON fp.party_id=c.from_party_id JOIN parties tp ON tp.party_id=c.to_party_id WHERE contra_id=p_id)x$$;
CREATE OR REPLACE FUNCTION get_previous_payment(p_id bigint) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT get_payment_details(max(payment_id)) FROM payments WHERE payment_id<p_id$$;
CREATE OR REPLACE FUNCTION get_next_payment(p_id bigint) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT get_payment_details(min(payment_id)) FROM payments WHERE payment_id>p_id$$;
CREATE OR REPLACE FUNCTION get_last_payment() RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT get_payment_details(max(payment_id)) FROM payments$$;
CREATE OR REPLACE FUNCTION get_previous_receipt(p_id bigint) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT get_receipt_details(max(receipt_id)) FROM receipts WHERE receipt_id<p_id$$;
CREATE OR REPLACE FUNCTION get_next_receipt(p_id bigint) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT get_receipt_details(min(receipt_id)) FROM receipts WHERE receipt_id>p_id$$;
CREATE OR REPLACE FUNCTION get_last_receipt() RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT get_receipt_details(max(receipt_id)) FROM receipts$$;
CREATE OR REPLACE FUNCTION get_previous_contra(p_id bigint) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT get_contra_details(max(contra_id)) FROM contra_entries WHERE contra_id<p_id$$;
CREATE OR REPLACE FUNCTION get_next_contra(p_id bigint) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT get_contra_details(min(contra_id)) FROM contra_entries WHERE contra_id>p_id$$;
CREATE OR REPLACE FUNCTION get_last_contra() RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT get_contra_details(max(contra_id)) FROM contra_entries$$;
CREATE OR REPLACE FUNCTION get_last_20_payments_json(data jsonb) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY payment_id DESC),'[]'::jsonb) FROM(SELECT py.*,p.party_name FROM payments py JOIN parties p USING(party_id) ORDER BY payment_id DESC LIMIT 20)x$$;
CREATE OR REPLACE FUNCTION get_last_20_receipts_json(data jsonb) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY receipt_id DESC),'[]'::jsonb) FROM(SELECT r.*,p.party_name FROM receipts r JOIN parties p USING(party_id) ORDER BY receipt_id DESC LIMIT 20)x$$;
CREATE OR REPLACE FUNCTION get_last_20_contras_json(data jsonb) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT COALESCE(jsonb_agg(get_contra_details(contra_id) ORDER BY contra_id DESC),'[]'::jsonb) FROM(SELECT contra_id FROM contra_entries ORDER BY contra_id DESC LIMIT 20)x$$;
CREATE OR REPLACE FUNCTION get_payments_by_date_json(data jsonb) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT COALESCE(jsonb_agg(get_payment_details(payment_id)),'[]'::jsonb) FROM payments WHERE payment_date BETWEEN (data->>'start_date')::date AND (data->>'end_date')::date$$;
CREATE OR REPLACE FUNCTION get_receipts_by_date_json(data jsonb) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT COALESCE(jsonb_agg(get_receipt_details(receipt_id)),'[]'::jsonb) FROM receipts WHERE receipt_date BETWEEN (data->>'start_date')::date AND (data->>'end_date')::date$$;
CREATE OR REPLACE FUNCTION get_contras_by_date_json(data jsonb) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT COALESCE(jsonb_agg(get_contra_details(contra_id)),'[]'::jsonb) FROM contra_entries WHERE contra_date BETWEEN (data->>'start_date')::date AND (data->>'end_date')::date$$;

CREATE OR REPLACE FUNCTION get_opening_cash_json() RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT COALESCE((SELECT jsonb_build_object('amount',amount,'opening_cash',amount,'is_set',true) FROM opening_cash LIMIT 1),
 jsonb_build_object('amount',0,'opening_cash',0,'is_set',false)) $$;
CREATE OR REPLACE FUNCTION set_opening_cash_from_json(data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE amt numeric;old opening_cash%ROWTYPE;j bigint;usr integer;
BEGIN amt:=(data->>'amount')::numeric;usr:=NULLIF(data->>'created_by_id','')::integer;
 IF amt<0 THEN RAISE EXCEPTION 'Opening cash cannot be negative.' USING ERRCODE='check_violation'; END IF;
 SELECT * INTO old FROM opening_cash LIMIT 1 FOR UPDATE;
 IF FOUND AND old.journal_id IS NOT NULL THEN PERFORM quantity_reverse_journal(old.journal_id,CURRENT_DATE,'Revise opening cash',usr); END IF;
 j:=NULL;
 IF amt>0 THEN j:=quantity_post_journal(CURRENT_DATE,'Opening Cash in Hand','opening_cash',
 COALESCE(old.opening_cash_id,1),NULL,usr,jsonb_build_array(
 jsonb_build_object('account_code','1000','debit',amt,'credit',0),
 jsonb_build_object('account_code','3000','debit',0,'credit',amt))); END IF;
 IF old.opening_cash_id IS NULL THEN INSERT INTO opening_cash(amount,journal_id,created_by) VALUES(amt,j,usr);
 ELSE UPDATE opening_cash SET amount=amt,journal_id=j,created_by=usr,updated_at=now(); END IF;
 RETURN jsonb_build_object('status','success','amount',amt,'journal_id',j);END $$;

CREATE OR REPLACE FUNCTION add_owner_equity_txn(data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE id bigint;dir text;amt numeric;d date;acct chart_of_accounts%ROWTYPE;j bigint;usr integer;
BEGIN dir:=data->>'direction';amt:=(data->>'amount')::numeric;
 d:=COALESCE(NULLIF(data->>'txn_date','')::date,CURRENT_DATE);usr:=NULLIF(data->>'created_by_id','')::integer;
 IF dir NOT IN('injection','withdrawal') THEN RAISE EXCEPTION 'Invalid direction.' USING ERRCODE='check_violation'; END IF;
 IF amt<=0 THEN RAISE EXCEPTION 'Invalid amount.' USING ERRCODE='check_violation'; END IF;
 SELECT * INTO acct FROM chart_of_accounts WHERE account_type='Equity' AND account_name=
 COALESCE(NULLIF(data->>'equity_account',''),'Owner''s Capital');
 IF NOT FOUND THEN RAISE EXCEPTION 'Equity account not found.'; END IF;
 id:=nextval('owner_equity_transactions_txn_id_seq');
 j:=quantity_post_journal(d,'Owner equity '||dir,'owner_equity',id,NULL,usr,
 jsonb_build_array(jsonb_build_object('account_code','1000',
 'debit',CASE WHEN dir='injection' THEN amt ELSE 0 END,'credit',CASE WHEN dir='withdrawal' THEN amt ELSE 0 END),
 jsonb_build_object('account_code',acct.account_code,'debit',CASE WHEN dir='withdrawal' THEN amt ELSE 0 END,
 'credit',CASE WHEN dir='injection' THEN amt ELSE 0 END)));
 INSERT INTO owner_equity_transactions(txn_id,txn_date,direction,amount,equity_account_id,description,journal_id,created_by)
 VALUES(id,d,dir,amt,acct.account_id,data->>'description',j,usr);
 RETURN jsonb_build_object('status','success','txn_id',id,'journal_id',j);END $$;
CREATE OR REPLACE FUNCTION delete_owner_equity_txn(p_id bigint) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE x owner_equity_transactions%ROWTYPE;
BEGIN SELECT * INTO x FROM owner_equity_transactions WHERE txn_id=p_id AND status='posted' FOR UPDATE;
 IF NOT FOUND THEN RETURN jsonb_build_object('status','not_found'); END IF;
 PERFORM quantity_reverse_journal(x.journal_id,x.txn_date,'Reverse owner equity',x.created_by);
 UPDATE owner_equity_transactions SET status='reversed' WHERE txn_id=p_id;
 RETURN jsonb_build_object('status','success','txn_id',p_id);END $$;
CREATE OR REPLACE FUNCTION get_owner_equity_json(p_limit integer) RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT jsonb_build_object('transactions',COALESCE(jsonb_agg(to_jsonb(x) ORDER BY txn_id DESC),'[]'::jsonb))
 FROM(SELECT o.*,c.account_name equity_account FROM owner_equity_transactions o
 JOIN chart_of_accounts c ON c.account_id=o.equity_account_id ORDER BY txn_id DESC LIMIT p_limit)x $$;

CREATE OR REPLACE FUNCTION preview_period_close(p_year integer,p_month integer) RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE sd date;ed date;
BEGIN IF p_month NOT BETWEEN 1 AND 12 THEN RAISE EXCEPTION 'Invalid month.'; END IF;
 sd:=make_date(p_year,p_month,1);ed:=(sd+interval '1 month - 1 day')::date;
 RETURN jsonb_build_object('year',p_year,'month',p_month,'start_date',sd,'end_date',ed,
 'debit_total',(SELECT COALESCE(sum(debit),0) FROM journal_lines l JOIN journal_entries e USING(journal_id) WHERE e.entry_date BETWEEN sd AND ed),
 'credit_total',(SELECT COALESCE(sum(credit),0) FROM journal_lines l JOIN journal_entries e USING(journal_id) WHERE e.entry_date BETWEEN sd AND ed),
 'is_closed',EXISTS(SELECT 1 FROM period_closes WHERE period_year=p_year AND period_month=p_month));END $$;
CREATE OR REPLACE FUNCTION close_period_from_json(data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE y integer;m integer;usr integer;
BEGIN y:=(data->>'year')::integer;m:=(data->>'month')::integer;usr:=NULLIF(data->>'created_by_id','')::integer;
 IF m NOT BETWEEN 1 AND 12 THEN RAISE EXCEPTION 'Invalid month.'; END IF;
 IF EXISTS(SELECT 1 FROM period_closes WHERE period_year=y AND period_month=m) THEN RAISE EXCEPTION 'Period is already closed.'; END IF;
 INSERT INTO period_closes(period_year,period_month,closed_by) VALUES(y,m,usr);
 RETURN jsonb_build_object('status','success','year',y,'month',m);END $$;
CREATE OR REPLACE FUNCTION reverse_period_close(p_year integer,p_month integer) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE removed integer;
BEGIN PERFORM set_config('financee.period_close_admin','allowed',true);
 DELETE FROM period_closes WHERE period_year=p_year AND period_month=p_month;GET DIAGNOSTICS removed=ROW_COUNT;
 PERFORM set_config('financee.period_close_admin','',true);
 IF removed=0 THEN RETURN jsonb_build_object('status','not_found'); END IF;
 RETURN jsonb_build_object('status','success','year',p_year,'month',p_month);END $$;
CREATE OR REPLACE FUNCTION get_period_closes_json() RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT jsonb_build_object('closed',COALESCE(jsonb_agg(to_jsonb(p) ORDER BY period_year DESC,period_month DESC),'[]'::jsonb))
 FROM period_closes p $$;
CREATE OR REPLACE FUNCTION reclassify_opening_balance_to_capital(data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE bal numeric;j bigint;usr integer;
BEGIN SELECT COALESCE(sum(l.credit-l.debit),0) INTO bal FROM journal_lines l JOIN chart_of_accounts c USING(account_id) WHERE c.account_code='3001';
 IF bal=0 THEN RETURN jsonb_build_object('status','noop','amount',0); END IF;
 usr:=NULLIF(data->>'created_by_id','')::integer;
 j:=quantity_post_journal(CURRENT_DATE,'Reclassify Opening Balance','opening_reclass',NULL,NULL,usr,
 jsonb_build_array(jsonb_build_object('account_code',CASE WHEN bal>0 THEN '3001' ELSE '3000' END,'debit',abs(bal),'credit',0),
 jsonb_build_object('account_code',CASE WHEN bal>0 THEN '3000' ELSE '3001' END,'debit',0,'credit',abs(bal))));
 RETURN jsonb_build_object('status','success','amount',abs(bal),'journal_id',j);END $$;

INSERT INTO quantity_seed_registry(seed_key,seed_version,payload)
VALUES('quantity.financial_modules',1,'{"phase":19,"schema_version":15}'::jsonb)
ON CONFLICT(seed_key) DO UPDATE SET seed_version=1,payload=EXCLUDED.payload,applied_at=now();
UPDATE tenant_schema_metadata SET version=GREATEST(version,15),applied_at=now() WHERE id=true AND family='quantity';
