-- Idempotent Phase 15 warehouse transfers for QUANTITY schemas, v11.
DO $$ BEGIN
 IF to_regclass('tenant_schema_metadata') IS NULL OR NOT EXISTS(
  SELECT 1 FROM tenant_schema_metadata WHERE id=true AND family='quantity' AND version>=10
 ) THEN RAISE EXCEPTION 'Quantity transfer rollout refused: family/version mismatch.'; END IF;
END $$;

CREATE TABLE IF NOT EXISTS warehouse_transfers(
 transfer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 document_number varchar(32) NOT NULL UNIQUE,
 transfer_date date NOT NULL,
 source_warehouse_id bigint NOT NULL REFERENCES warehouses(warehouse_id),
 destination_warehouse_id bigint NOT NULL REFERENCES warehouses(warehouse_id),
 description text,status varchar(10) NOT NULL DEFAULT 'draft',
 revision_number integer NOT NULL DEFAULT 1,
 total_quantity numeric NOT NULL DEFAULT 0,
 total_value_base numeric(24,6) NOT NULL DEFAULT 0,
 idempotency_key varchar(100) NOT NULL UNIQUE,
 request_fingerprint varchar(32) NOT NULL,
 created_by integer,updated_by integer,reversed_by integer,
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,reversed_at timestamptz,
 CHECK(source_warehouse_id<>destination_warehouse_id),
 CHECK(status IN('draft','posted','reversed')),
 CHECK(total_quantity>=0 AND total_value_base>=0)
);
CREATE TABLE IF NOT EXISTS warehouse_transfer_lines(
 transfer_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 transfer_id bigint NOT NULL REFERENCES warehouse_transfers(transfer_id),
 line_number integer NOT NULL,variant_id bigint NOT NULL REFERENCES product_variants(variant_id),
 quantity numeric NOT NULL,total_cost_base numeric(24,6) NOT NULL DEFAULT 0,
 source_movement_id bigint NOT NULL UNIQUE REFERENCES stock_movements(movement_id),
 description text,
 CHECK(quantity>0 AND quantity=round(quantity,3)),CHECK(total_cost_base>=0),
 UNIQUE(transfer_id,line_number),UNIQUE(transfer_id,variant_id)
);
CREATE TABLE IF NOT EXISTS warehouse_transfer_cost_segments(
 segment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 transfer_line_id bigint NOT NULL REFERENCES warehouse_transfer_lines(transfer_line_id),
 segment_order integer NOT NULL,source_inbound_movement_id bigint NOT NULL REFERENCES stock_movements(movement_id),
 quantity numeric NOT NULL,unit_cost_base numeric(20,6) NOT NULL,total_cost_base numeric(24,6) NOT NULL,
 destination_movement_id bigint NOT NULL UNIQUE REFERENCES stock_movements(movement_id),
 CHECK(quantity>0 AND quantity=round(quantity,3)),CHECK(unit_cost_base>=0),
 CHECK(total_cost_base=round(quantity*unit_cost_base,6)),
 UNIQUE(transfer_line_id,segment_order)
);
CREATE TABLE IF NOT EXISTS warehouse_transfer_revisions(
 transfer_revision_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 transfer_id bigint NOT NULL REFERENCES warehouse_transfers(transfer_id),
 revision_number integer NOT NULL,previous_document jsonb NOT NULL,changed_by integer,
 changed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(transfer_id,revision_number)
);
CREATE INDEX IF NOT EXISTS warehouse_transfer_date_idx ON warehouse_transfers(transfer_date,transfer_id);

CREATE OR REPLACE FUNCTION quantity_protect_transfer() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF current_setting('financee.transfer_engine',true)='allowed' THEN RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END; END IF;
 RAISE EXCEPTION 'Posted transfer records are immutable; use transfer operations.' USING ERRCODE='check_violation';
END $$;
DROP TRIGGER IF EXISTS warehouse_transfers_guard ON warehouse_transfers;
CREATE TRIGGER warehouse_transfers_guard BEFORE UPDATE OR DELETE ON warehouse_transfers FOR EACH ROW EXECUTE FUNCTION quantity_protect_transfer();
DROP TRIGGER IF EXISTS warehouse_transfer_lines_guard ON warehouse_transfer_lines;
CREATE TRIGGER warehouse_transfer_lines_guard BEFORE UPDATE OR DELETE ON warehouse_transfer_lines FOR EACH ROW EXECUTE FUNCTION quantity_protect_transfer();
DROP TRIGGER IF EXISTS warehouse_transfer_segments_guard ON warehouse_transfer_cost_segments;
CREATE TRIGGER warehouse_transfer_segments_guard BEFORE UPDATE OR DELETE ON warehouse_transfer_cost_segments FOR EACH ROW EXECUTE FUNCTION quantity_protect_transfer();
DROP TRIGGER IF EXISTS warehouse_transfer_revisions_guard ON warehouse_transfer_revisions;
CREATE TRIGGER warehouse_transfer_revisions_guard BEFORE UPDATE OR DELETE ON warehouse_transfer_revisions FOR EACH ROW EXECUTE FUNCTION quantity_protect_transfer();

CREATE OR REPLACE FUNCTION quantity_transfer_fingerprint(data jsonb) RETURNS varchar LANGUAGE sql IMMUTABLE AS $$
 SELECT md5(jsonb_build_object('transfer_date',data->>'transfer_date',
  'source_warehouse_id',data->>'source_warehouse_id','destination_warehouse_id',data->>'destination_warehouse_id',
  'description',btrim(COALESCE(data->>'description','')),'lines',COALESCE(data->'lines',data->'items','[]'::jsonb))::text)
$$;

CREATE OR REPLACE FUNCTION quantity_transfer_details(p_id bigint) RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT jsonb_build_object('transfer_id',t.transfer_id,'document_number',t.document_number,
  'transfer_date',t.transfer_date,'source_warehouse_id',t.source_warehouse_id,
  'source_warehouse_code',sw.warehouse_code,'source_warehouse_name',sw.warehouse_name,
  'destination_warehouse_id',t.destination_warehouse_id,'destination_warehouse_code',dw.warehouse_code,
  'destination_warehouse_name',dw.warehouse_name,'description',t.description,'status',t.status,
  'revision_number',t.revision_number,'total_quantity',t.total_quantity,'total_value_base',t.total_value_base,
  'lines',COALESCE(jsonb_agg(jsonb_build_object('transfer_line_id',l.transfer_line_id,
   'line_number',l.line_number,'variant_id',l.variant_id,'sku',v.sku,'product_name',p.product_name,
   'unit_code',u.code,'quantity',l.quantity,'total_cost_base',l.total_cost_base,
   'description',l.description) ORDER BY l.line_number) FILTER(WHERE l.transfer_line_id IS NOT NULL),'[]'::jsonb))
 FROM warehouse_transfers t JOIN warehouses sw ON sw.warehouse_id=t.source_warehouse_id
 JOIN warehouses dw ON dw.warehouse_id=t.destination_warehouse_id
 LEFT JOIN warehouse_transfer_lines l USING(transfer_id) LEFT JOIN product_variants v ON v.variant_id=l.variant_id
 LEFT JOIN products p ON p.product_id=v.product_id LEFT JOIN units_of_measure u ON u.unit_id=v.unit_id
 WHERE t.transfer_id=p_id GROUP BY t.transfer_id,sw.warehouse_id,dw.warehouse_id
$$;

CREATE OR REPLACE FUNCTION quantity_create_transfer(data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE d date;srcw bigint;dstw bigint;descr text;lines jsonb;usr integer;key varchar;fp varchar;
 existing warehouse_transfers%ROWTYPE;id bigint;number text;x jsonb;n integer:=0;v bigint;qty numeric;
 outbound jsonb;line_id bigint;a record;seg integer;dest jsonb;line_cost numeric(24,6);
 total_qty numeric:=0;total_value numeric(24,6):=0;pairs jsonb;
BEGIN
 BEGIN d:=(data->>'transfer_date')::date;srcw:=(data->>'source_warehouse_id')::bigint;
  dstw:=(data->>'destination_warehouse_id')::bigint;usr:=NULLIF(data->>'created_by_id','')::integer;
 EXCEPTION WHEN others THEN RAISE EXCEPTION 'Transfer date, warehouses, or user is invalid.' USING ERRCODE='check_violation'; END;
 descr:=NULLIF(btrim(COALESCE(data->>'description','')),'');lines:=COALESCE(data->'lines',data->'items');
 key:=btrim(COALESCE(data->>'idempotency_key',''));
 IF d IS NULL OR srcw=dstw OR lines IS NULL OR jsonb_typeof(lines)<>'array' OR jsonb_array_length(lines)=0 OR key='' OR length(key)>100
 THEN RAISE EXCEPTION 'Transfer date, distinct warehouses, lines, and idempotency key are required.' USING ERRCODE='check_violation'; END IF;
 IF NOT EXISTS(SELECT 1 FROM warehouses WHERE warehouse_id=srcw AND is_active) OR
    NOT EXISTS(SELECT 1 FROM warehouses WHERE warehouse_id=dstw AND is_active)
 THEN RAISE EXCEPTION 'Both transfer warehouses must be active.' USING ERRCODE='check_violation'; END IF;
 fp:=quantity_transfer_fingerprint(data);PERFORM pg_advisory_xact_lock(hashtextextended(current_schema()||':transfer:'||key,0));
 SELECT * INTO existing FROM warehouse_transfers WHERE idempotency_key=key FOR UPDATE;
 IF FOUND THEN IF existing.request_fingerprint=fp THEN RETURN jsonb_build_object('status','success','idempotent',true,
  'transfer_id',existing.transfer_id,'document_number',existing.document_number,'total_quantity',existing.total_quantity,
  'total_value_base',existing.total_value_base); END IF;
  RAISE EXCEPTION 'Idempotency key reused with different transfer data.' USING ERRCODE='unique_violation'; END IF;
 SELECT jsonb_agg(p ORDER BY (p->>'warehouse_id')::bigint,(p->>'variant_id')::bigint) INTO pairs FROM(
  SELECT jsonb_build_object('warehouse_id',w,'variant_id',(x.value->>'variant_id')::bigint)p
  FROM jsonb_array_elements(lines)x CROSS JOIN LATERAL(VALUES(srcw),(dstw))z(w))s;
 PERFORM quantity_lock_inventory_pairs(pairs);number:=quantity_next_document_number('transfer');
 PERFORM set_config('financee.transfer_engine','allowed',true);
 INSERT INTO warehouse_transfers(document_number,transfer_date,source_warehouse_id,destination_warehouse_id,
  description,status,idempotency_key,request_fingerprint,created_by,updated_by)
 VALUES(number,d,srcw,dstw,descr,'draft',key,fp,usr,usr) RETURNING transfer_id INTO id;
 FOR x IN SELECT value FROM jsonb_array_elements(lines) LOOP n:=n+1;
  BEGIN v:=(x->>'variant_id')::bigint;qty:=(x->>'quantity')::numeric;
  EXCEPTION WHEN others THEN RAISE EXCEPTION 'Transfer line % contains invalid numbers.',n USING ERRCODE='check_violation'; END;
  PERFORM quantity_validate_quantity(v,qty);
  outbound:=quantity_post_stock_movement('transfer_out',v,srcw,d,qty,NULL,'transfer',id,n,number,usr,
   COALESCE(NULLIF(btrim(x->>'description'),''),descr,'Warehouse transfer'));
  INSERT INTO warehouse_transfer_lines(transfer_id,line_number,variant_id,quantity,source_movement_id,description)
  VALUES(id,n,v,qty,(outbound->>'movement_id')::bigint,NULLIF(btrim(x->>'description'),''))
  RETURNING transfer_line_id INTO line_id;
  seg:=0;line_cost:=0;
  FOR a IN SELECT fa.*,fl.inbound_movement_id FROM fifo_allocations fa JOIN fifo_layers fl USING(layer_id)
   WHERE fa.outbound_movement_id=(outbound->>'movement_id')::bigint ORDER BY fa.allocation_order
  LOOP seg:=seg+1;
   dest:=quantity_post_stock_movement('transfer_in',v,dstw,d,a.quantity,a.unit_cost_base,
    'transfer',id,n*1000+seg,number,usr,'Transfer from '||srcw);
   INSERT INTO warehouse_transfer_cost_segments(transfer_line_id,segment_order,source_inbound_movement_id,
    quantity,unit_cost_base,total_cost_base,destination_movement_id)
   VALUES(line_id,seg,a.inbound_movement_id,a.quantity,a.unit_cost_base,a.total_cost_base,(dest->>'movement_id')::bigint);
   line_cost:=line_cost+a.total_cost_base;
  END LOOP;
  UPDATE warehouse_transfer_lines SET total_cost_base=line_cost WHERE transfer_line_id=line_id;
  total_qty:=total_qty+qty;total_value:=total_value+line_cost;
 END LOOP;
 UPDATE warehouse_transfers SET status='posted',total_quantity=total_qty,total_value_base=total_value WHERE transfer_id=id;
 PERFORM set_config('financee.transfer_engine','',true);
 RETURN jsonb_build_object('status','success','idempotent',false,'transfer_id',id,'document_number',number,
  'total_quantity',total_qty,'total_value_base',total_value);
END $$;

CREATE OR REPLACE FUNCTION quantity_reverse_transfer(p_id bigint,p_date date,p_user integer) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE h warehouse_transfers%ROWTYPE;s record;first_layer bigint;outbound jsonb;restored jsonb;
BEGIN
 SELECT * INTO h FROM warehouse_transfers WHERE transfer_id=p_id FOR UPDATE;
 IF NOT FOUND OR h.status<>'posted' THEN RAISE EXCEPTION 'Posted transfer not found.' USING ERRCODE='check_violation'; END IF;
 IF p_date<h.transfer_date THEN RAISE EXCEPTION 'Reversal date precedes transfer date.' USING ERRCODE='check_violation'; END IF;
 PERFORM quantity_lock_inventory_pairs((SELECT jsonb_agg(jsonb_build_object('warehouse_id',w,'variant_id',l.variant_id))
  FROM warehouse_transfer_lines l CROSS JOIN LATERAL(VALUES(h.source_warehouse_id),(h.destination_warehouse_id))z(w)
  WHERE l.transfer_id=p_id));
 -- Guarded reversal is allowed only while every transferred destination layer is
 -- untouched and is the next FIFO stock. This prevents unrelated stock removal.
 FOR s IN SELECT cs.*,l.variant_id,fl.layer_id,fl.remaining_quantity,fl.original_quantity
  FROM warehouse_transfer_cost_segments cs JOIN warehouse_transfer_lines l USING(transfer_line_id)
  JOIN fifo_layers fl ON fl.inbound_movement_id=cs.destination_movement_id
  WHERE l.transfer_id=p_id ORDER BY l.line_number,cs.segment_order FOR UPDATE OF fl
 LOOP
  SELECT min(layer_id) INTO first_layer FROM fifo_layers WHERE variant_id=s.variant_id
   AND warehouse_id=h.destination_warehouse_id AND remaining_quantity>0;
  IF s.remaining_quantity<>s.original_quantity OR first_layer<>s.layer_id THEN
   RAISE EXCEPTION 'Transfer cannot be reversed after destination stock order or quantity changed.'
    USING ERRCODE='check_violation'; END IF;
  outbound:=quantity_post_stock_movement('transfer_out',s.variant_id,h.destination_warehouse_id,p_date,
   s.quantity,NULL,'transfer_reversal',p_id,s.segment_id,h.document_number,p_user,'Reverse transfer destination');
  restored:=quantity_post_stock_movement('transfer_in',s.variant_id,h.source_warehouse_id,p_date,
   s.quantity,s.unit_cost_base,'transfer_reversal',p_id,1000000+s.segment_id,h.document_number,p_user,
   'Restore transfer source');
 END LOOP;
 PERFORM set_config('financee.transfer_engine','allowed',true);
 UPDATE warehouse_transfers SET status='reversed',reversed_by=p_user,reversed_at=CURRENT_TIMESTAMP,
  updated_by=p_user,updated_at=CURRENT_TIMESTAMP WHERE transfer_id=p_id;
 PERFORM set_config('financee.transfer_engine','',true);
 RETURN jsonb_build_object('status','success','transfer_id',p_id,'document_number',h.document_number);
END $$;

CREATE OR REPLACE FUNCTION quantity_update_transfer(p_id bigint,data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE h warehouse_transfers%ROWTYPE;usr integer;replacement jsonb;
BEGIN
 SELECT * INTO h FROM warehouse_transfers WHERE transfer_id=p_id FOR UPDATE;
 IF NOT FOUND OR h.status<>'posted' THEN RAISE EXCEPTION 'Only posted transfers can be updated.' USING ERRCODE='check_violation'; END IF;
 usr:=NULLIF(data->>'created_by_id','')::integer;
 PERFORM set_config('financee.transfer_engine','allowed',true);
 INSERT INTO warehouse_transfer_revisions(transfer_id,revision_number,previous_document,changed_by)
 VALUES(p_id,h.revision_number,quantity_transfer_details(p_id),usr);
 PERFORM set_config('financee.transfer_engine','',true);
 PERFORM quantity_reverse_transfer(p_id,COALESCE(NULLIF(data->>'transfer_date','')::date,CURRENT_DATE),usr);
 data:=jsonb_set(data,'{idempotency_key}',to_jsonb(COALESCE(NULLIF(data->>'idempotency_key',''),
  'transfer-update-'||p_id||'-'||(h.revision_number+1))));
 replacement:=quantity_create_transfer(data);
 RETURN replacement||jsonb_build_object('replaced_transfer_id',p_id,'previous_document_number',h.document_number,
  'revision_number',h.revision_number+1);
END $$;

CREATE OR REPLACE FUNCTION quantity_transfer_navigate(action text,current_id bigint DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE id bigint;BEGIN CASE lower(COALESCE(action,'last'))
 WHEN 'current' THEN id:=current_id;
 WHEN 'previous' THEN SELECT max(transfer_id) INTO id FROM warehouse_transfers WHERE transfer_id<current_id;
 WHEN 'next' THEN SELECT min(transfer_id) INTO id FROM warehouse_transfers WHERE transfer_id>current_id;
 WHEN 'first' THEN SELECT min(transfer_id) INTO id FROM warehouse_transfers;
 WHEN 'last' THEN SELECT max(transfer_id) INTO id FROM warehouse_transfers;
 ELSE RAISE EXCEPTION 'Unknown navigation action.' USING ERRCODE='check_violation';END CASE;
 RETURN quantity_transfer_details(id);END $$;
CREATE OR REPLACE FUNCTION quantity_transfer_summary(from_date date DEFAULT NULL,to_date date DEFAULT NULL) RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT jsonb_build_object('transfer_count',count(*)::integer,'posted_count',count(*)FILTER(WHERE status='posted')::integer,
 'reversed_count',count(*)FILTER(WHERE status='reversed')::integer,
 'documents',COALESCE(jsonb_agg(jsonb_build_object('transfer_id',t.transfer_id,'document_number',t.document_number,
 'transfer_date',t.transfer_date,'source_warehouse_code',sw.warehouse_code,'destination_warehouse_code',dw.warehouse_code,
 'status',t.status,'total_quantity',t.total_quantity,'total_value_base',t.total_value_base)ORDER BY t.transfer_id DESC),'[]'::jsonb))
 FROM warehouse_transfers t JOIN warehouses sw ON sw.warehouse_id=t.source_warehouse_id
 JOIN warehouses dw ON dw.warehouse_id=t.destination_warehouse_id
 WHERE(from_date IS NULL OR transfer_date>=from_date)AND(to_date IS NULL OR transfer_date<=to_date)
$$;
INSERT INTO quantity_seed_registry(seed_key,seed_version,payload)VALUES('quantity.warehouse_transfers',1,
'{"fifo_cost_preserved":true,"company_value_neutral":true}'::jsonb)
ON CONFLICT(seed_key)DO UPDATE SET seed_version=GREATEST(quantity_seed_registry.seed_version,EXCLUDED.seed_version),
payload=EXCLUDED.payload,applied_at=CURRENT_TIMESTAMP;
UPDATE tenant_schema_metadata SET version=GREATEST(version,11),applied_at=CURRENT_TIMESTAMP WHERE id=true AND family='quantity';
