-- Idempotent Phase 10 opening-stock capability for QUANTITY schemas, version 6.
DO $$
BEGIN
    IF to_regclass('tenant_schema_metadata') IS NULL
       OR NOT EXISTS (
           SELECT 1 FROM tenant_schema_metadata
            WHERE id = true AND family = 'quantity' AND version >= 5
       ) THEN
        RAISE EXCEPTION 'Quantity opening-stock rollout refused: family/version mismatch.';
    END IF;
END;
$$;

INSERT INTO document_sequences (document_type, prefix)
VALUES ('opening_stock', 'OPN')
ON CONFLICT (document_type) DO UPDATE SET prefix = EXCLUDED.prefix;

CREATE TABLE IF NOT EXISTS opening_stock_documents (
    opening_stock_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_number varchar(32) NOT NULL UNIQUE,
    opening_date date NOT NULL,
    description text,
    status varchar(10) NOT NULL DEFAULT 'posted',
    journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
    reversal_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
    reversed_at timestamptz,
    reversed_by integer,
    created_by integer,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT opening_stock_status_check CHECK (
        status IN ('draft', 'posted', 'reversed')
    ),
    CONSTRAINT opening_stock_reversal_shape_check CHECK (
        (status = 'draft' AND journal_id IS NULL
         AND reversal_journal_id IS NULL AND reversed_at IS NULL)
        OR
        (status = 'posted' AND journal_id IS NOT NULL
         AND reversal_journal_id IS NULL AND reversed_at IS NULL)
        OR
        (status = 'reversed' AND journal_id IS NOT NULL
         AND reversal_journal_id IS NOT NULL
         AND reversed_at IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS opening_stock_lines (
    opening_stock_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opening_stock_id bigint NOT NULL
        REFERENCES opening_stock_documents(opening_stock_id),
    line_number integer NOT NULL,
    variant_id bigint NOT NULL REFERENCES product_variants(variant_id),
    warehouse_id bigint NOT NULL REFERENCES warehouses(warehouse_id),
    quantity numeric NOT NULL,
    unit_cost_base numeric(20,6) NOT NULL,
    line_total_base numeric(24,6) NOT NULL,
    movement_id bigint NOT NULL UNIQUE REFERENCES stock_movements(movement_id),
    description text,
    CONSTRAINT opening_stock_line_number_positive CHECK (line_number > 0),
    CONSTRAINT opening_stock_line_quantity_positive CHECK (
        quantity > 0 AND quantity = round(quantity, 3)
    ),
    CONSTRAINT opening_stock_line_cost_non_negative CHECK (unit_cost_base >= 0),
    CONSTRAINT opening_stock_line_total_check CHECK (
        line_total_base = round(quantity * unit_cost_base, 6)
    ),
    CONSTRAINT opening_stock_line_number_unique
        UNIQUE (opening_stock_id, line_number),
    CONSTRAINT opening_stock_scope_unique
        UNIQUE (opening_stock_id, variant_id, warehouse_id)
);

CREATE INDEX IF NOT EXISTS opening_stock_documents_date_idx
    ON opening_stock_documents(opening_date, opening_stock_id);
CREATE INDEX IF NOT EXISTS opening_stock_lines_variant_warehouse_idx
    ON opening_stock_lines(variant_id, warehouse_id);

CREATE OR REPLACE FUNCTION quantity_protect_opening_stock_document()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF current_setting('financee.opening_stock_engine', true) = 'allowed' THEN
        RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
    END IF;
    RAISE EXCEPTION 'Opening-stock documents are immutable; use reversal.'
        USING ERRCODE = 'check_violation';
END;
$$;

DROP TRIGGER IF EXISTS opening_stock_documents_write_guard
    ON opening_stock_documents;
CREATE TRIGGER opening_stock_documents_write_guard
BEFORE UPDATE OR DELETE ON opening_stock_documents
FOR EACH ROW EXECUTE FUNCTION quantity_protect_opening_stock_document();

DROP TRIGGER IF EXISTS opening_stock_lines_write_guard ON opening_stock_lines;
CREATE TRIGGER opening_stock_lines_write_guard
BEFORE UPDATE OR DELETE ON opening_stock_lines
FOR EACH ROW EXECUTE FUNCTION quantity_protect_opening_stock_document();

CREATE OR REPLACE FUNCTION quantity_create_opening_stock(data jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    v_document_id bigint;
    v_document_number text;
    v_opening_date date;
    v_description text;
    v_created_by integer;
    v_lines jsonb;
    v_line jsonb;
    v_line_number integer := 0;
    v_variant_id bigint;
    v_warehouse_id bigint;
    v_quantity numeric;
    v_unit_cost numeric(20,6);
    v_line_total numeric(24,6);
    v_total numeric(24,6) := 0;
    v_movement jsonb;
    v_movement_id bigint;
    v_journal_id bigint;
    v_pairs jsonb;
BEGIN
    IF data IS NULL OR jsonb_typeof(data) <> 'object' THEN
        RAISE EXCEPTION 'Opening-stock payload must be an object.'
            USING ERRCODE = 'check_violation';
    END IF;
    BEGIN
        v_opening_date := COALESCE(
            NULLIF(data->>'opening_date', '')::date,
            NULLIF(data->>'as_of_date', '')::date
        );
        v_created_by := NULLIF(data->>'created_by_id', '')::integer;
    EXCEPTION WHEN invalid_text_representation OR datetime_field_overflow THEN
        RAISE EXCEPTION 'Opening-stock date or user is invalid.'
            USING ERRCODE = 'check_violation';
    END;
    v_opening_date := COALESCE(v_opening_date, CURRENT_DATE);
    v_description := NULLIF(btrim(COALESCE(data->>'description',
                                          data->>'notes', '')), '');
    v_lines := COALESCE(data->'lines', data->'items');
    IF v_lines IS NULL OR jsonb_typeof(v_lines) <> 'array'
       OR jsonb_array_length(v_lines) = 0 THEN
        RAISE EXCEPTION 'At least one opening-stock line is required.'
            USING ERRCODE = 'check_violation';
    END IF;

    BEGIN
        SELECT jsonb_agg(jsonb_build_object(
                   'variant_id', (value->>'variant_id')::bigint,
                   'warehouse_id', (value->>'warehouse_id')::bigint
               ))
          INTO v_pairs
          FROM jsonb_array_elements(v_lines);
    EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
        RAISE EXCEPTION 'Every line requires valid variant and warehouse IDs.'
            USING ERRCODE = 'check_violation';
    END;
    PERFORM quantity_lock_inventory_pairs(v_pairs);

    v_document_number := quantity_next_document_number('opening_stock');
    PERFORM set_config('financee.opening_stock_engine', 'allowed', true);
    INSERT INTO opening_stock_documents (
        document_number, opening_date, description, status, created_by
    ) VALUES (
        v_document_number, v_opening_date, v_description, 'draft', v_created_by
    ) RETURNING opening_stock_id INTO v_document_id;

    FOR v_line IN SELECT value FROM jsonb_array_elements(v_lines)
    LOOP
        v_line_number := v_line_number + 1;
        BEGIN
            v_variant_id := (v_line->>'variant_id')::bigint;
            v_warehouse_id := (v_line->>'warehouse_id')::bigint;
            v_quantity := (v_line->>'quantity')::numeric;
            v_unit_cost := (v_line->>'unit_cost_base')::numeric;
        EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
            RAISE EXCEPTION 'Opening-stock line % contains invalid numbers.',
                v_line_number USING ERRCODE = 'check_violation';
        END;
        PERFORM quantity_validate_quantity(v_variant_id, v_quantity);
        IF v_unit_cost IS NULL OR v_unit_cost < 0
           OR v_unit_cost <> round(v_unit_cost, 6) THEN
            RAISE EXCEPTION 'Opening-stock line % has an invalid unit cost.',
                v_line_number USING ERRCODE = 'check_violation';
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM warehouses
             WHERE warehouse_id = v_warehouse_id AND is_active
        ) THEN
            RAISE EXCEPTION 'Opening-stock line % uses an inactive warehouse.',
                v_line_number USING ERRCODE = 'foreign_key_violation';
        END IF;
        IF EXISTS (
            SELECT 1 FROM opening_stock_lines
             WHERE opening_stock_id = v_document_id
               AND variant_id = v_variant_id
               AND warehouse_id = v_warehouse_id
        ) THEN
            RAISE EXCEPTION 'Duplicate SKU and warehouse in opening stock.'
                USING ERRCODE = 'unique_violation';
        END IF;
        v_line_total := round(v_quantity * v_unit_cost, 6);
        v_movement := quantity_post_stock_movement(
            'opening', v_variant_id, v_warehouse_id, v_opening_date,
            v_quantity, v_unit_cost, 'opening_stock', v_document_id,
            v_line_number, v_document_number, v_created_by,
            COALESCE(NULLIF(btrim(v_line->>'description'), ''),
                     v_description, 'Opening stock')
        );
        v_movement_id := (v_movement->>'movement_id')::bigint;
        INSERT INTO opening_stock_lines (
            opening_stock_id, line_number, variant_id, warehouse_id,
            quantity, unit_cost_base, line_total_base, movement_id, description
        ) VALUES (
            v_document_id, v_line_number, v_variant_id, v_warehouse_id,
            v_quantity, v_unit_cost, v_line_total, v_movement_id,
            NULLIF(btrim(v_line->>'description'), '')
        );
        v_total := v_total + v_line_total;
    END LOOP;
    IF round(v_total, 4) <= 0 THEN
        RAISE EXCEPTION 'Opening stock must have a positive accounting value.'
            USING ERRCODE = 'check_violation';
    END IF;

    v_journal_id := quantity_post_journal(
        v_opening_date,
        'Opening stock ' || v_document_number,
        'opening_stock', v_document_id, v_document_number, v_created_by,
        jsonb_build_array(
            jsonb_build_object(
                'account_code', '1400', 'debit', round(v_total, 4), 'credit', 0,
                'description', COALESCE(v_description, 'Opening inventory')
            ),
            jsonb_build_object(
                'account_code', '3001', 'debit', 0, 'credit', round(v_total, 4),
                'description', 'Opening Balance'
            )
        )
    );
    UPDATE opening_stock_documents
       SET journal_id = v_journal_id, status = 'posted'
     WHERE opening_stock_id = v_document_id;
    PERFORM set_config('financee.opening_stock_engine', '', true);
    RETURN jsonb_build_object(
        'status', 'success', 'opening_stock_id', v_document_id,
        'document_number', v_document_number, 'journal_id', v_journal_id,
        'line_count', v_line_number, 'total_cost_base', v_total
    );
END;
$$;

CREATE OR REPLACE FUNCTION quantity_opening_stock_list()
RETURNS jsonb LANGUAGE sql STABLE AS $$
    SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.opening_stock_id DESC),
                    '[]'::jsonb)
      FROM (
        SELECT d.opening_stock_id, d.document_number, d.opening_date,
               d.description, d.status, d.journal_id, d.reversal_journal_id,
               d.created_by, d.created_at,
               count(l.opening_stock_line_id)::integer AS line_count,
               COALESCE(sum(l.quantity), 0) AS total_quantity,
               COALESCE(sum(l.line_total_base), 0) AS total_cost_base
          FROM opening_stock_documents d
          LEFT JOIN opening_stock_lines l USING (opening_stock_id)
         GROUP BY d.opening_stock_id
      ) x;
$$;

CREATE OR REPLACE FUNCTION quantity_opening_stock_details(p_opening_stock_id bigint)
RETURNS jsonb LANGUAGE sql STABLE AS $$
    SELECT jsonb_build_object(
        'opening_stock_id', d.opening_stock_id,
        'document_number', d.document_number,
        'opening_date', d.opening_date,
        'description', d.description,
        'status', d.status,
        'journal_id', d.journal_id,
        'reversal_journal_id', d.reversal_journal_id,
        'created_by', d.created_by,
        'created_at', d.created_at,
        'total_cost_base', COALESCE(sum(l.line_total_base), 0),
        'lines', COALESCE(jsonb_agg(
            jsonb_build_object(
                'opening_stock_line_id', l.opening_stock_line_id,
                'line_number', l.line_number,
                'variant_id', l.variant_id,
                'sku', v.sku,
                'product_name', p.product_name,
                'unit_code', u.code,
                'warehouse_id', l.warehouse_id,
                'warehouse_code', w.warehouse_code,
                'warehouse_name', w.warehouse_name,
                'quantity', l.quantity,
                'unit_cost_base', l.unit_cost_base,
                'line_total_base', l.line_total_base,
                'movement_id', l.movement_id,
                'description', l.description
            ) ORDER BY l.line_number
        ) FILTER (WHERE l.opening_stock_line_id IS NOT NULL), '[]'::jsonb)
    )
      FROM opening_stock_documents d
      LEFT JOIN opening_stock_lines l USING (opening_stock_id)
      LEFT JOIN product_variants v ON v.variant_id = l.variant_id
      LEFT JOIN products p ON p.product_id = v.product_id
      LEFT JOIN units_of_measure u ON u.unit_id = v.unit_id
      LEFT JOIN warehouses w ON w.warehouse_id = l.warehouse_id
     WHERE d.opening_stock_id = p_opening_stock_id
     GROUP BY d.opening_stock_id;
$$;

CREATE OR REPLACE FUNCTION quantity_reverse_opening_stock(
    p_opening_stock_id bigint, p_reversal_date date, p_created_by integer
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    v_document opening_stock_documents%ROWTYPE;
    v_line opening_stock_lines%ROWTYPE;
    v_layer fifo_layers%ROWTYPE;
    v_reversal jsonb;
    v_reversal_journal_id bigint;
BEGIN
    SELECT * INTO v_document FROM opening_stock_documents
     WHERE opening_stock_id = p_opening_stock_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Opening-stock document not found.'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    IF v_document.status <> 'posted' THEN
        RAISE EXCEPTION 'Opening stock is already reversed.'
            USING ERRCODE = 'check_violation';
    END IF;
    IF p_reversal_date IS NULL OR p_reversal_date < v_document.opening_date THEN
        RAISE EXCEPTION 'Reversal date cannot precede the opening date.'
            USING ERRCODE = 'check_violation';
    END IF;
    PERFORM quantity_lock_inventory_pairs((
        SELECT jsonb_agg(jsonb_build_object(
                   'variant_id', variant_id, 'warehouse_id', warehouse_id
               ))
          FROM opening_stock_lines
         WHERE opening_stock_id = p_opening_stock_id
    ));
    -- An opening load can only be reversed while every original layer remains
    -- untouched. This prevents arbitrary current FIFO from replacing its cost.
    FOR v_line IN
        SELECT * FROM opening_stock_lines
         WHERE opening_stock_id = p_opening_stock_id ORDER BY line_number
    LOOP
        SELECT * INTO v_layer FROM fifo_layers
         WHERE inbound_movement_id = v_line.movement_id FOR UPDATE;
        IF NOT FOUND OR v_layer.remaining_quantity <> v_layer.original_quantity THEN
            RAISE EXCEPTION
                'Opening stock cannot be reversed after any of its quantity was consumed.'
                USING ERRCODE = 'check_violation';
        END IF;
    END LOOP;
    FOR v_line IN
        SELECT * FROM opening_stock_lines
         WHERE opening_stock_id = p_opening_stock_id ORDER BY line_number
    LOOP
        v_reversal := quantity_reverse_stock_movement(
            v_line.movement_id, p_reversal_date,
            p_opening_stock_id * 1000000 + v_line.line_number, p_created_by
        );
    END LOOP;
    v_reversal_journal_id := quantity_reverse_journal(
        v_document.journal_id, p_reversal_date,
        'Reverse opening stock ' || v_document.document_number, p_created_by
    );
    PERFORM set_config('financee.opening_stock_engine', 'allowed', true);
    UPDATE opening_stock_documents
       SET status = 'reversed', reversal_journal_id = v_reversal_journal_id,
           reversed_at = CURRENT_TIMESTAMP, reversed_by = p_created_by
     WHERE opening_stock_id = p_opening_stock_id;
    PERFORM set_config('financee.opening_stock_engine', '', true);
    RETURN jsonb_build_object(
        'status', 'success', 'opening_stock_id', p_opening_stock_id,
        'reversal_journal_id', v_reversal_journal_id
    );
END;
$$;

CREATE OR REPLACE FUNCTION quantity_opening_balance_status()
RETURNS jsonb LANGUAGE sql STABLE AS $$
    WITH balances AS (
        SELECT coa.account_code,
               COALESCE(sum(jl.debit - jl.credit), 0) AS debit_minus_credit
          FROM chart_of_accounts coa
          LEFT JOIN journal_lines jl ON jl.account_id = coa.account_id
         WHERE coa.account_code IN ('3000', '3001')
         GROUP BY coa.account_code
    )
    SELECT jsonb_build_object(
        'obe_balance_dr_cr',
            COALESCE((SELECT debit_minus_credit FROM balances
                       WHERE account_code='3001'), 0),
        'obe_equity_amount',
            -COALESCE((SELECT debit_minus_credit FROM balances
                        WHERE account_code='3001'), 0),
        'capital_equity_amount',
            -COALESCE((SELECT debit_minus_credit FROM balances
                        WHERE account_code='3000'), 0),
        'needs_reclass',
            COALESCE((SELECT debit_minus_credit FROM balances
                       WHERE account_code='3001'), 0) <> 0
    );
$$;

CREATE OR REPLACE FUNCTION quantity_reclassify_opening_balance(data jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    v_balance numeric(24,4);
    v_journal_id bigint;
    v_created_by integer;
BEGIN
    BEGIN
        v_created_by := NULLIF(data->>'created_by_id', '')::integer;
    EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
        RAISE EXCEPTION 'Invalid user.'
            USING ERRCODE = 'check_violation';
    END;
    PERFORM pg_advisory_xact_lock(
        hashtextextended(current_schema() || ':opening_balance_reclass', 0)
    );
    SELECT COALESCE(sum(jl.debit - jl.credit), 0)
      INTO v_balance
      FROM journal_lines jl
      JOIN chart_of_accounts coa ON coa.account_id = jl.account_id
     WHERE coa.account_code = '3001';
    IF v_balance = 0 THEN
        RETURN jsonb_build_object(
            'status', 'noop',
            'message', 'Opening Balance is already zero.'
        );
    END IF;
    v_journal_id := quantity_post_journal(
        CURRENT_DATE, 'Reclassify Opening Balance to Owner''s Capital',
        'opening_reclassification', NULL, NULL, v_created_by,
        CASE WHEN v_balance < 0 THEN
            jsonb_build_array(
                jsonb_build_object('account_code','3001',
                                   'debit',-v_balance,'credit',0),
                jsonb_build_object('account_code','3000',
                                   'debit',0,'credit',-v_balance)
            )
        ELSE
            jsonb_build_array(
                jsonb_build_object('account_code','3001',
                                   'debit',0,'credit',v_balance),
                jsonb_build_object('account_code','3000',
                                   'debit',v_balance,'credit',0)
            )
        END
    );
    RETURN jsonb_build_object(
        'status', 'success', 'amount', abs(v_balance),
        'journal_id', v_journal_id
    );
END;
$$;

INSERT INTO quantity_seed_registry (seed_key, seed_version, payload)
VALUES (
    'quantity.opening_stock', 1,
    '{"document_prefix":"OPN","inventory_account":"1400","opening_balance_account":"3001","capital_account":"3000"}'::jsonb
)
ON CONFLICT (seed_key) DO UPDATE
SET seed_version = GREATEST(
        quantity_seed_registry.seed_version, EXCLUDED.seed_version
    ),
    payload = EXCLUDED.payload,
    applied_at = CURRENT_TIMESTAMP;

UPDATE tenant_schema_metadata
   SET version = GREATEST(version, 6), applied_at = CURRENT_TIMESTAMP
 WHERE id = true AND family = 'quantity';
