-- Idempotent Phase 14 quantity purchase returns for QUANTITY schemas, v10.
DO $$
BEGIN
    IF to_regclass('tenant_schema_metadata') IS NULL OR NOT EXISTS (
        SELECT 1 FROM tenant_schema_metadata
         WHERE id=true AND family='quantity' AND version>=9
    ) THEN
        RAISE EXCEPTION 'Quantity purchase-return rollout refused: family/version mismatch.';
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS purchase_return_invoices (
    purchase_return_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_number varchar(32) NOT NULL UNIQUE,
    return_date date NOT NULL,
    vendor_name varchar(200) NOT NULL,
    description text,
    status varchar(10) NOT NULL DEFAULT 'draft',
    revision_number integer NOT NULL DEFAULT 1,
    total_base numeric(24,6) NOT NULL DEFAULT 0,
    journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
    reversal_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
    idempotency_key varchar(100) NOT NULL UNIQUE,
    request_fingerprint varchar(32) NOT NULL,
    created_by integer, updated_by integer, reversed_by integer,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reversed_at timestamptz,
    CHECK (btrim(vendor_name)<>''),
    CHECK (status IN ('draft','posted','reversed')),
    CHECK (total_base>=0)
);

CREATE TABLE IF NOT EXISTS purchase_return_lines (
    purchase_return_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_return_id bigint NOT NULL REFERENCES purchase_return_invoices(purchase_return_id),
    line_number integer NOT NULL,
    source_purchase_line_id bigint NOT NULL REFERENCES purchase_lines(purchase_line_id),
    variant_id bigint NOT NULL REFERENCES product_variants(variant_id),
    warehouse_id bigint NOT NULL REFERENCES warehouses(warehouse_id),
    quantity numeric NOT NULL,
    unit_cost_base numeric(20,6) NOT NULL,
    line_total_base numeric(24,6) NOT NULL,
    movement_id bigint NOT NULL UNIQUE REFERENCES stock_movements(movement_id),
    description text,
    CHECK (quantity>0 AND quantity=round(quantity,3)),
    CHECK (unit_cost_base>0),
    CHECK (line_total_base=round(quantity*unit_cost_base,6)),
    UNIQUE(purchase_return_id,line_number),
    UNIQUE(purchase_return_id,source_purchase_line_id)
);

-- Stable directives survive FIFO projection rebuilds. A purchase return is
-- never allowed to consume an unrelated FIFO layer.
CREATE TABLE IF NOT EXISTS purchase_return_source_allocations (
    source_allocation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_return_line_id bigint NOT NULL
        REFERENCES purchase_return_lines(purchase_return_line_id),
    outbound_movement_id bigint NOT NULL REFERENCES stock_movements(movement_id),
    inbound_movement_id bigint NOT NULL REFERENCES stock_movements(movement_id),
    quantity numeric NOT NULL,
    allocation_order integer NOT NULL,
    CHECK (quantity>0 AND quantity=round(quantity,3)),
    UNIQUE(outbound_movement_id,allocation_order),
    UNIQUE(purchase_return_line_id,inbound_movement_id)
);

CREATE TABLE IF NOT EXISTS purchase_return_revisions (
    purchase_return_revision_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_return_id bigint NOT NULL REFERENCES purchase_return_invoices(purchase_return_id),
    revision_number integer NOT NULL,
    previous_document jsonb NOT NULL,
    changed_by integer,
    changed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(purchase_return_id,revision_number)
);

CREATE INDEX IF NOT EXISTS purchase_return_date_idx
 ON purchase_return_invoices(return_date,purchase_return_id);
CREATE INDEX IF NOT EXISTS purchase_return_source_idx
 ON purchase_return_lines(source_purchase_line_id);

CREATE OR REPLACE FUNCTION quantity_protect_purchase_return()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF current_setting('financee.purchase_return_engine',true)='allowed' THEN
  RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
 END IF;
 RAISE EXCEPTION 'Posted purchase-return records are immutable; use return operations.'
  USING ERRCODE='check_violation';
END;
$$;
DROP TRIGGER IF EXISTS purchase_return_invoices_guard ON purchase_return_invoices;
CREATE TRIGGER purchase_return_invoices_guard BEFORE UPDATE OR DELETE
 ON purchase_return_invoices FOR EACH ROW EXECUTE FUNCTION quantity_protect_purchase_return();
DROP TRIGGER IF EXISTS purchase_return_lines_guard ON purchase_return_lines;
CREATE TRIGGER purchase_return_lines_guard BEFORE UPDATE OR DELETE
 ON purchase_return_lines FOR EACH ROW EXECUTE FUNCTION quantity_protect_purchase_return();
DROP TRIGGER IF EXISTS purchase_return_allocations_guard ON purchase_return_source_allocations;
CREATE TRIGGER purchase_return_allocations_guard BEFORE UPDATE OR DELETE
 ON purchase_return_source_allocations FOR EACH ROW EXECUTE FUNCTION quantity_protect_purchase_return();
DROP TRIGGER IF EXISTS purchase_return_revisions_guard ON purchase_return_revisions;
CREATE TRIGGER purchase_return_revisions_guard BEFORE UPDATE OR DELETE
 ON purchase_return_revisions FOR EACH ROW EXECUTE FUNCTION quantity_protect_purchase_return();

CREATE OR REPLACE FUNCTION quantity_guard_purchase_with_returns()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF OLD.status='posted' AND NEW.status<>OLD.status AND EXISTS (
  SELECT 1 FROM purchase_return_lines rl
  JOIN purchase_return_invoices r USING(purchase_return_id)
  WHERE rl.source_purchase_line_id IN (
   SELECT purchase_line_id FROM purchase_lines
    WHERE purchase_invoice_id=OLD.purchase_invoice_id
  ) AND r.status='posted'
 ) THEN
  RAISE EXCEPTION 'Purchase cannot be changed after a posted return.'
   USING ERRCODE='check_violation';
 END IF;
 RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS purchase_invoices_return_guard ON purchase_invoices;
CREATE TRIGGER purchase_invoices_return_guard BEFORE UPDATE ON purchase_invoices
 FOR EACH ROW EXECUTE FUNCTION quantity_guard_purchase_with_returns();

-- Phase 14 replay: ordinary outbounds remain FIFO; purchase returns follow
-- their locked, persistent source directives.
CREATE OR REPLACE FUNCTION quantity_replay_inventory(
 p_variant_id bigint,p_warehouse_id bigint
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
 event_count integer; movement stock_movements%ROWTYPE; layer fifo_layers%ROWTYPE;
 running_quantity numeric:=0; needed numeric; take_quantity numeric;
 allocation_no integer; movement_cost numeric(24,6);
 closing_quantity numeric; fifo_quantity numeric; fifo_value numeric(24,6);
 directive record;
BEGIN
 PERFORM quantity_inventory_scope_lock(p_variant_id,p_warehouse_id);
 PERFORM set_config('financee.inventory_engine','allowed',true);
 INSERT INTO stock_balances(variant_id,warehouse_id) VALUES(p_variant_id,p_warehouse_id)
 ON CONFLICT(variant_id,warehouse_id) DO NOTHING;
 PERFORM 1 FROM stock_balances WHERE variant_id=p_variant_id
  AND warehouse_id=p_warehouse_id FOR UPDATE;
 SELECT count(*) INTO event_count FROM stock_movements
  WHERE variant_id=p_variant_id AND warehouse_id=p_warehouse_id;
 IF event_count>10000 THEN RAISE EXCEPTION 'Inventory replay scope exceeds synchronous limit.'
  USING ERRCODE='program_limit_exceeded'; END IF;
 FOR movement IN SELECT * FROM stock_movements WHERE variant_id=p_variant_id
  AND warehouse_id=p_warehouse_id ORDER BY movement_date,effective_sequence,movement_id
 LOOP
  running_quantity:=running_quantity+movement.quantity_in-movement.quantity_out;
  IF running_quantity<0 THEN RAISE EXCEPTION
   'Insufficient stock: requested %, available %, variant %, warehouse %.',
   movement.quantity_out,running_quantity+movement.quantity_out,p_variant_id,p_warehouse_id
   USING ERRCODE='check_violation'; END IF;
 END LOOP;
 closing_quantity:=running_quantity;
 DELETE FROM fifo_allocations fa USING stock_movements sm
  WHERE fa.outbound_movement_id=sm.movement_id AND sm.variant_id=p_variant_id
   AND sm.warehouse_id=p_warehouse_id;
 INSERT INTO fifo_layers(inbound_movement_id,variant_id,warehouse_id,source_type,
  source_id,source_line_id,source_date,effective_sequence,original_quantity,
  remaining_quantity,unit_cost_base)
 SELECT movement_id,variant_id,warehouse_id,source_type,source_id,source_line_id,
  movement_date,effective_sequence,quantity_in,quantity_in,unit_cost_base
 FROM stock_movements WHERE variant_id=p_variant_id AND warehouse_id=p_warehouse_id
  AND quantity_in>0
 ON CONFLICT(inbound_movement_id) DO UPDATE SET source_date=EXCLUDED.source_date,
  effective_sequence=EXCLUDED.effective_sequence,
  original_quantity=EXCLUDED.original_quantity,
  remaining_quantity=EXCLUDED.original_quantity,unit_cost_base=EXCLUDED.unit_cost_base;
 FOR movement IN SELECT * FROM stock_movements WHERE variant_id=p_variant_id
  AND warehouse_id=p_warehouse_id ORDER BY movement_date,effective_sequence,movement_id
 LOOP
  IF movement.quantity_out>0 THEN
   needed:=movement.quantity_out; allocation_no:=0; movement_cost:=0;
   IF movement.movement_type='purchase_return' THEN
    FOR directive IN SELECT a.*,fl.layer_id,fl.remaining_quantity,fl.unit_cost_base,
      fl.source_date,fl.effective_sequence
     FROM purchase_return_source_allocations a JOIN fifo_layers fl
      ON fl.inbound_movement_id=a.inbound_movement_id
     WHERE a.outbound_movement_id=movement.movement_id
     ORDER BY a.allocation_order FOR UPDATE OF fl
    LOOP
     IF directive.source_date>movement.movement_date OR
       (directive.source_date=movement.movement_date AND
        directive.effective_sequence>movement.effective_sequence) OR
        directive.remaining_quantity<directive.quantity THEN
      RAISE EXCEPTION 'Purchase return source quantity is unavailable at return date.'
       USING ERRCODE='check_violation';
     END IF;
     allocation_no:=allocation_no+1;
     INSERT INTO fifo_allocations(outbound_movement_id,layer_id,quantity,
      unit_cost_base,total_cost_base,allocation_order)
     VALUES(movement.movement_id,directive.layer_id,directive.quantity,
      directive.unit_cost_base,round(directive.quantity*directive.unit_cost_base,6),
      allocation_no);
     UPDATE fifo_layers SET remaining_quantity=remaining_quantity-directive.quantity
      WHERE layer_id=directive.layer_id;
     needed:=needed-directive.quantity;
     movement_cost:=movement_cost+round(directive.quantity*directive.unit_cost_base,6);
    END LOOP;
   ELSE
    FOR layer IN SELECT * FROM fifo_layers WHERE variant_id=p_variant_id
      AND warehouse_id=p_warehouse_id AND remaining_quantity>0 AND
      (source_date<movement.movement_date OR (source_date=movement.movement_date
       AND effective_sequence<=movement.effective_sequence))
      ORDER BY source_date,effective_sequence,layer_id FOR UPDATE
    LOOP
     EXIT WHEN needed=0; take_quantity:=LEAST(needed,layer.remaining_quantity);
     allocation_no:=allocation_no+1;
     INSERT INTO fifo_allocations(outbound_movement_id,layer_id,quantity,
      unit_cost_base,total_cost_base,allocation_order)
     VALUES(movement.movement_id,layer.layer_id,take_quantity,layer.unit_cost_base,
      round(take_quantity*layer.unit_cost_base,6),allocation_no);
     UPDATE fifo_layers SET remaining_quantity=remaining_quantity-take_quantity
      WHERE layer_id=layer.layer_id;
     needed:=needed-take_quantity;
     movement_cost:=movement_cost+round(take_quantity*layer.unit_cost_base,6);
    END LOOP;
   END IF;
   IF needed<>0 THEN RAISE EXCEPTION 'FIFO allocation did not satisfy movement.'
    USING ERRCODE='check_violation'; END IF;
   UPDATE stock_movements SET total_cost_base=movement_cost,
    unit_cost_base=round(movement_cost/movement.quantity_out,6)
    WHERE movement_id=movement.movement_id;
  ELSE
   UPDATE stock_movements SET total_cost_base=round(quantity_in*unit_cost_base,6)
    WHERE movement_id=movement.movement_id;
  END IF;
 END LOOP;
 SELECT COALESCE(sum(remaining_quantity),0),
  COALESCE(sum(round(remaining_quantity*unit_cost_base,6)),0)
 INTO fifo_quantity,fifo_value FROM fifo_layers
 WHERE variant_id=p_variant_id AND warehouse_id=p_warehouse_id;
 IF fifo_quantity<>closing_quantity THEN RAISE EXCEPTION
  'Inventory/FIFO quantity reconciliation failed.' USING ERRCODE='check_violation'; END IF;
 UPDATE stock_balances SET on_hand_quantity=closing_quantity,
  balance_version=balance_version+1,updated_at=CURRENT_TIMESTAMP
  WHERE variant_id=p_variant_id AND warehouse_id=p_warehouse_id;
 PERFORM set_config('financee.inventory_engine','',true);
 RETURN jsonb_build_object('variant_id',p_variant_id,'warehouse_id',p_warehouse_id,
  'on_hand_quantity',closing_quantity,'fifo_quantity',fifo_quantity,
  'fifo_value',fifo_value,'event_count',event_count);
END;
$$;

CREATE OR REPLACE FUNCTION quantity_purchase_return_details(p_id bigint)
RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT jsonb_build_object('purchase_return_id',r.purchase_return_id,
  'document_number',r.document_number,'return_date',r.return_date,
  'vendor_name',r.vendor_name,'description',r.description,'status',r.status,
  'revision_number',r.revision_number,'total_base',r.total_base,
  'lines',COALESCE(jsonb_agg(jsonb_build_object(
   'purchase_return_line_id',l.purchase_return_line_id,'line_number',l.line_number,
   'source_purchase_line_id',l.source_purchase_line_id,
   'source_document_number',i.document_number,'variant_id',l.variant_id,
   'sku',v.sku,'product_name',p.product_name,'unit_code',u.code,
   'warehouse_id',l.warehouse_id,'warehouse_code',w.warehouse_code,
   'warehouse_name',w.warehouse_name,'quantity',l.quantity,
   'unit_cost_base',l.unit_cost_base,'line_total_base',l.line_total_base
  ) ORDER BY l.line_number) FILTER(WHERE l.purchase_return_line_id IS NOT NULL),'[]'::jsonb))
 FROM purchase_return_invoices r LEFT JOIN purchase_return_lines l USING(purchase_return_id)
 LEFT JOIN purchase_lines pl ON pl.purchase_line_id=l.source_purchase_line_id
 LEFT JOIN purchase_invoices i ON i.purchase_invoice_id=pl.purchase_invoice_id
 LEFT JOIN product_variants v ON v.variant_id=l.variant_id
 LEFT JOIN products p ON p.product_id=v.product_id LEFT JOIN units_of_measure u ON u.unit_id=v.unit_id
 LEFT JOIN warehouses w ON w.warehouse_id=l.warehouse_id
 WHERE r.purchase_return_id=p_id GROUP BY r.purchase_return_id;
$$;

CREATE OR REPLACE FUNCTION quantity_purchase_return_sources(p_vendor text DEFAULT NULL)
RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT COALESCE(jsonb_agg(jsonb_build_object(
  'source_purchase_line_id',l.purchase_line_id,'purchase_invoice_id',i.purchase_invoice_id,
  'document_number',i.document_number,'invoice_date',i.invoice_date,
  'vendor_name',i.vendor_name,'purchase_type',i.purchase_type,
  'payment_account_code',i.payment_account_code,'variant_id',l.variant_id,
  'sku',v.sku,'product_name',p.product_name,'unit_code',u.code,
  'warehouse_id',l.warehouse_id,'warehouse_code',w.warehouse_code,
  'warehouse_name',w.warehouse_name,'purchased_quantity',l.quantity,
  'eligible_quantity',COALESCE(eligible.quantity,0),
  'unit_cost_base',l.unit_cost_base
 ) ORDER BY i.purchase_invoice_id DESC,l.line_number),'[]'::jsonb)
 FROM purchase_lines l JOIN purchase_invoices i USING(purchase_invoice_id)
 JOIN product_variants v USING(variant_id) JOIN products p USING(product_id)
 JOIN units_of_measure u USING(unit_id) JOIN warehouses w USING(warehouse_id)
 LEFT JOIN LATERAL (
  SELECT sum(fl.remaining_quantity) quantity FROM fifo_layers fl
  WHERE fl.inbound_movement_id=l.movement_id OR fl.inbound_movement_id IN (
   SELECT reverse_sm.movement_id FROM purchase_return_lines prl
   JOIN stock_movements reverse_sm ON reverse_sm.reversal_of_movement_id=prl.movement_id
   WHERE prl.source_purchase_line_id=l.purchase_line_id
  )
 ) eligible ON true
 WHERE i.status='posted' AND COALESCE(eligible.quantity,0)>0
 AND (p_vendor IS NULL OR upper(i.vendor_name)=upper(btrim(p_vendor)));
$$;

CREATE OR REPLACE FUNCTION quantity_purchase_return_fingerprint(data jsonb)
RETURNS varchar LANGUAGE sql IMMUTABLE AS $$
 SELECT md5(jsonb_build_object('return_date',data->>'return_date',
  'vendor_name',upper(btrim(COALESCE(data->>'vendor_name',data->>'party_name',''))),
  'description',btrim(COALESCE(data->>'description','')),
  'lines',COALESCE(data->'lines',data->'items','[]'::jsonb))::text);
$$;

CREATE OR REPLACE FUNCTION quantity_create_purchase_return(data jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
 d date; vendor varchar; descr text; lines jsonb; usr integer; key varchar; fp varchar;
 existing purchase_return_invoices%ROWTYPE; id bigint; number text; x jsonb;
 src purchase_lines%ROWTYPE; inv purchase_invoices%ROWTYPE; qty numeric; eligible numeric;
 n integer:=0; line_id bigint; movement_id bigint; total numeric(24,6):=0;
 journal bigint; account_code varchar; line_account varchar; pairs jsonb;
 source_layer record; remaining numeric; allocation_n integer;
BEGIN
 BEGIN d:=(data->>'return_date')::date; usr:=NULLIF(data->>'created_by_id','')::integer;
 EXCEPTION WHEN others THEN RAISE EXCEPTION 'Return date or user is invalid.'
  USING ERRCODE='check_violation'; END;
 vendor:=btrim(COALESCE(data->>'vendor_name',data->>'party_name',''));
 descr:=NULLIF(btrim(COALESCE(data->>'description','')),'');
 lines:=COALESCE(data->'lines',data->'items'); key:=btrim(COALESCE(data->>'idempotency_key',''));
 IF d IS NULL OR vendor='' OR lines IS NULL OR jsonb_typeof(lines)<>'array'
  OR jsonb_array_length(lines)=0 OR key='' OR length(key)>100 THEN
  RAISE EXCEPTION 'Return date, vendor, lines, and idempotency key are required.'
   USING ERRCODE='check_violation'; END IF;
 fp:=quantity_purchase_return_fingerprint(data);
 PERFORM pg_advisory_xact_lock(hashtextextended(current_schema()||':purchase-return:'||key,0));
 SELECT * INTO existing FROM purchase_return_invoices WHERE idempotency_key=key FOR UPDATE;
 IF FOUND THEN
  IF existing.request_fingerprint=fp THEN RETURN jsonb_build_object('status','success',
   'idempotent',true,'purchase_return_id',existing.purchase_return_id,
   'document_number',existing.document_number,'total_base',existing.total_base); END IF;
  RAISE EXCEPTION 'Idempotency key reused with different return data.'
   USING ERRCODE='unique_violation'; END IF;
 SELECT jsonb_agg(jsonb_build_object('variant_id',pl.variant_id,'warehouse_id',pl.warehouse_id))
 INTO pairs FROM jsonb_array_elements(lines) x JOIN purchase_lines pl
  ON pl.purchase_line_id=(x.value->>'source_purchase_line_id')::bigint;
 PERFORM quantity_lock_inventory_pairs(pairs);
 number:=quantity_next_document_number('purchase_return');
 PERFORM set_config('financee.purchase_return_engine','allowed',true);
 INSERT INTO purchase_return_invoices(document_number,return_date,vendor_name,
  description,status,idempotency_key,request_fingerprint,created_by,updated_by)
 VALUES(number,d,vendor,descr,'draft',key,fp,usr,usr) RETURNING purchase_return_id INTO id;
 FOR x IN SELECT value FROM jsonb_array_elements(lines) LOOP
  n:=n+1;
  BEGIN qty:=(x->>'quantity')::numeric;
  EXCEPTION WHEN others THEN RAISE EXCEPTION 'Purchase return line % has invalid quantity.',n
   USING ERRCODE='check_violation'; END;
  SELECT * INTO src FROM purchase_lines
   WHERE purchase_line_id=(x->>'source_purchase_line_id')::bigint FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Original purchase line not found.'
   USING ERRCODE='foreign_key_violation'; END IF;
  SELECT * INTO inv FROM purchase_invoices WHERE purchase_invoice_id=src.purchase_invoice_id FOR UPDATE;
  IF inv.status<>'posted' OR upper(inv.vendor_name)<>upper(vendor) THEN
   RAISE EXCEPTION 'Purchase return vendor does not match original purchase.'
    USING ERRCODE='check_violation'; END IF;
  IF d<inv.invoice_date THEN RAISE EXCEPTION 'Return date cannot precede purchase date.'
   USING ERRCODE='check_violation'; END IF;
  PERFORM quantity_validate_quantity(src.variant_id,qty);
  SELECT COALESCE(sum(fl.remaining_quantity),0) INTO eligible FROM fifo_layers fl
   WHERE fl.inbound_movement_id=src.movement_id OR fl.inbound_movement_id IN (
    SELECT reverse_sm.movement_id FROM purchase_return_lines old_line
    JOIN stock_movements reverse_sm
      ON reverse_sm.reversal_of_movement_id=old_line.movement_id
    WHERE old_line.source_purchase_line_id=src.purchase_line_id
   );
  IF COALESCE(eligible,0)<qty THEN
   RAISE EXCEPTION 'Requested quantity exceeds eligible original purchase stock.'
    USING ERRCODE='check_violation'; END IF;
  PERFORM set_config('financee.inventory_engine','allowed',true);
  INSERT INTO stock_movements(variant_id,warehouse_id,movement_date,effective_sequence,
   movement_type,quantity_in,quantity_out,source_type,source_id,source_line_id,
   document_number,created_by,description)
  VALUES(src.variant_id,src.warehouse_id,d,nextval('inventory_effective_sequence_seq'),
   'purchase_return',0,qty,'purchase_return',id,n,number,usr,
   COALESCE(NULLIF(btrim(x->>'description'),''),descr,'Purchase return'))
  RETURNING stock_movements.movement_id INTO movement_id;
  INSERT INTO purchase_return_lines(purchase_return_id,line_number,
   source_purchase_line_id,variant_id,warehouse_id,quantity,unit_cost_base,
   line_total_base,movement_id,description)
  VALUES(id,n,src.purchase_line_id,src.variant_id,src.warehouse_id,qty,
   src.unit_cost_base,round(qty*src.unit_cost_base,6),movement_id,
   NULLIF(btrim(x->>'description'),''))
  RETURNING purchase_return_line_id INTO line_id;
  remaining:=qty; allocation_n:=0;
  FOR source_layer IN
   SELECT fl.* FROM fifo_layers fl
    WHERE fl.remaining_quantity>0 AND (
     fl.inbound_movement_id=src.movement_id OR fl.inbound_movement_id IN (
      SELECT reverse_sm.movement_id FROM purchase_return_lines old_line
      JOIN stock_movements reverse_sm
       ON reverse_sm.reversal_of_movement_id=old_line.movement_id
      WHERE old_line.source_purchase_line_id=src.purchase_line_id
     ))
    ORDER BY CASE WHEN fl.inbound_movement_id=src.movement_id THEN 0 ELSE 1 END,
     fl.source_date,fl.effective_sequence,fl.layer_id FOR UPDATE
  LOOP
   EXIT WHEN remaining=0; allocation_n:=allocation_n+1;
   INSERT INTO purchase_return_source_allocations(purchase_return_line_id,
    outbound_movement_id,inbound_movement_id,quantity,allocation_order)
   VALUES(line_id,movement_id,source_layer.inbound_movement_id,
    LEAST(remaining,source_layer.remaining_quantity),allocation_n);
   remaining:=remaining-LEAST(remaining,source_layer.remaining_quantity);
  END LOOP;
  INSERT INTO variant_transaction_registry(variant_id,source_type,source_id)
   VALUES(src.variant_id,'purchase_return',id) ON CONFLICT DO NOTHING;
  INSERT INTO warehouse_reference_registry(warehouse_id,source_type,source_id)
   VALUES(src.warehouse_id,'purchase_return',id) ON CONFLICT DO NOTHING;
  PERFORM quantity_replay_inventory(src.variant_id,src.warehouse_id);
  total:=total+round(qty*src.unit_cost_base,6);
  line_account:=CASE WHEN inv.purchase_type='credit' THEN '2000'
                     ELSE inv.payment_account_code END;
  IF n=1 THEN account_code:=line_account; END IF;
  IF account_code<>line_account THEN
   RAISE EXCEPTION 'All return lines must use the same original settlement account.'
    USING ERRCODE='check_violation'; END IF;
 END LOOP;
 UPDATE purchase_return_invoices SET total_base=total WHERE purchase_return_id=id;
 journal:=quantity_post_journal(d,'Purchase return '||number,'purchase_return',id,
  number,usr,jsonb_build_array(
   jsonb_build_object('account_code',account_code,'debit',round(total,4),'credit',0,
    'description','Vendor credit/cash restored'),
   jsonb_build_object('account_code','1400','debit',0,'credit',round(total,4),
    'description','Inventory returned')));
 UPDATE purchase_return_invoices SET status='posted',journal_id=journal
  WHERE purchase_return_id=id;
 PERFORM set_config('financee.purchase_return_engine','',true);
 RETURN jsonb_build_object('status','success','idempotent',false,
  'purchase_return_id',id,'document_number',number,'total_base',total,'journal_id',journal);
END;
$$;

CREATE OR REPLACE FUNCTION quantity_reverse_purchase_return(
 p_id bigint,p_date date,p_user integer
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE h purchase_return_invoices%ROWTYPE; l record; j bigint;
BEGIN
 SELECT * INTO h FROM purchase_return_invoices WHERE purchase_return_id=p_id FOR UPDATE;
 IF NOT FOUND OR h.status<>'posted' THEN RAISE EXCEPTION 'Posted purchase return not found.'
  USING ERRCODE='check_violation'; END IF;
 IF p_date<h.return_date THEN RAISE EXCEPTION 'Reversal date precedes return date.'
  USING ERRCODE='check_violation'; END IF;
 FOR l IN SELECT * FROM purchase_return_lines WHERE purchase_return_id=p_id ORDER BY line_number LOOP
  PERFORM quantity_reverse_stock_movement(l.movement_id,p_date,p_id*1000000+l.line_number,p_user);
 END LOOP;
 j:=quantity_reverse_journal(h.journal_id,p_date,'Reverse purchase return '||h.document_number,p_user);
 PERFORM set_config('financee.purchase_return_engine','allowed',true);
 UPDATE purchase_return_invoices SET status='reversed',reversal_journal_id=j,
  reversed_by=p_user,reversed_at=CURRENT_TIMESTAMP,updated_by=p_user,
  updated_at=CURRENT_TIMESTAMP WHERE purchase_return_id=p_id;
 PERFORM set_config('financee.purchase_return_engine','',true);
 RETURN jsonb_build_object('status','success','purchase_return_id',p_id,
  'document_number',h.document_number,'reversal_journal_id',j);
END;
$$;

CREATE OR REPLACE FUNCTION quantity_update_purchase_return(p_id bigint,data jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE h purchase_return_invoices%ROWTYPE; usr integer; replacement jsonb;
BEGIN
 SELECT * INTO h FROM purchase_return_invoices WHERE purchase_return_id=p_id FOR UPDATE;
 IF NOT FOUND OR h.status<>'posted' THEN RAISE EXCEPTION 'Only posted purchase returns can be updated.'
  USING ERRCODE='check_violation'; END IF;
 usr:=NULLIF(data->>'created_by_id','')::integer;
 PERFORM set_config('financee.purchase_return_engine','allowed',true);
 INSERT INTO purchase_return_revisions(purchase_return_id,revision_number,previous_document,changed_by)
 VALUES(p_id,h.revision_number,quantity_purchase_return_details(p_id),usr);
 PERFORM set_config('financee.purchase_return_engine','',true);
 PERFORM quantity_reverse_purchase_return(p_id,
  COALESCE(NULLIF(data->>'return_date','')::date,CURRENT_DATE),usr);
 data:=jsonb_set(data,'{idempotency_key}',to_jsonb(COALESCE(NULLIF(data->>'idempotency_key',''),
  'purchase-return-update-'||p_id||'-'||(h.revision_number+1))));
 replacement:=quantity_create_purchase_return(data);
 RETURN replacement||jsonb_build_object('replaced_purchase_return_id',p_id,
  'previous_document_number',h.document_number,'revision_number',h.revision_number+1);
END;
$$;

CREATE OR REPLACE FUNCTION quantity_purchase_return_navigate(action text,current_id bigint DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE id bigint;
BEGIN
 CASE lower(COALESCE(action,'last'))
 WHEN 'current' THEN id:=current_id;
 WHEN 'previous' THEN SELECT max(purchase_return_id) INTO id FROM purchase_return_invoices WHERE purchase_return_id<current_id;
 WHEN 'next' THEN SELECT min(purchase_return_id) INTO id FROM purchase_return_invoices WHERE purchase_return_id>current_id;
 WHEN 'first' THEN SELECT min(purchase_return_id) INTO id FROM purchase_return_invoices;
 WHEN 'last' THEN SELECT max(purchase_return_id) INTO id FROM purchase_return_invoices;
 ELSE RAISE EXCEPTION 'Unknown navigation action.' USING ERRCODE='check_violation'; END CASE;
 RETURN quantity_purchase_return_details(id);
END;
$$;

CREATE OR REPLACE FUNCTION quantity_purchase_return_summary(from_date date DEFAULT NULL,to_date date DEFAULT NULL)
RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT jsonb_build_object('invoice_count',count(*)::integer,
  'posted_count',count(*) FILTER(WHERE status='posted')::integer,
  'reversed_count',count(*) FILTER(WHERE status='reversed')::integer,
  'total_base',COALESCE(sum(total_base) FILTER(WHERE status='posted'),0),
  'documents',COALESCE(jsonb_agg(jsonb_build_object(
   'purchase_return_id',purchase_return_id,'document_number',document_number,
   'return_date',return_date,'vendor_name',vendor_name,'status',status,'total_base',total_base
  ) ORDER BY purchase_return_id DESC),'[]'::jsonb))
 FROM purchase_return_invoices WHERE (from_date IS NULL OR return_date>=from_date)
 AND (to_date IS NULL OR return_date<=to_date);
$$;

INSERT INTO quantity_seed_registry(seed_key,seed_version,payload)
VALUES('quantity.purchase_returns',1,
 '{"source":"purchase_lines/fifo_layers","partial":true,"original_cost":true}'::jsonb)
ON CONFLICT(seed_key) DO UPDATE SET seed_version=GREATEST(
 quantity_seed_registry.seed_version,EXCLUDED.seed_version),
 payload=EXCLUDED.payload,applied_at=CURRENT_TIMESTAMP;
UPDATE tenant_schema_metadata SET version=GREATEST(version,10),
 applied_at=CURRENT_TIMESTAMP WHERE id=true AND family='quantity';
