-- Idempotent Phase 13 quantity sale returns for QUANTITY schemas, v9.
DO $$
BEGIN
    IF to_regclass('tenant_schema_metadata') IS NULL OR NOT EXISTS (
        SELECT 1 FROM tenant_schema_metadata
         WHERE id=true AND family='quantity' AND version>=8
    ) THEN
        RAISE EXCEPTION 'Quantity sale-return rollout refused: family/version mismatch.';
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS sale_return_invoices (
    sale_return_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_number varchar(32) NOT NULL UNIQUE,
    return_date date NOT NULL,
    customer_name varchar(200) NOT NULL,
    description text,
    status varchar(10) NOT NULL DEFAULT 'draft',
    revision_number integer NOT NULL DEFAULT 1,
    revenue_total_base numeric(24,6) NOT NULL DEFAULT 0,
    cogs_total_base numeric(24,6) NOT NULL DEFAULT 0,
    journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
    reversal_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
    idempotency_key varchar(100) NOT NULL UNIQUE,
    request_fingerprint varchar(32) NOT NULL,
    created_by integer, updated_by integer, reversed_by integer,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reversed_at timestamptz,
    CONSTRAINT sale_return_customer_required CHECK (btrim(customer_name)<>''),
    CONSTRAINT sale_return_status_check CHECK (status IN ('draft','posted','reversed')),
    CONSTRAINT sale_return_totals_check CHECK (
        revenue_total_base>=0 AND cogs_total_base>=0
    )
);

CREATE TABLE IF NOT EXISTS sale_return_lines (
    sale_return_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_return_id bigint NOT NULL REFERENCES sale_return_invoices(sale_return_id),
    line_number integer NOT NULL,
    source_sale_line_id bigint NOT NULL REFERENCES sale_lines(sale_line_id),
    variant_id bigint NOT NULL REFERENCES product_variants(variant_id),
    source_warehouse_id bigint NOT NULL REFERENCES warehouses(warehouse_id),
    destination_warehouse_id bigint NOT NULL REFERENCES warehouses(warehouse_id),
    quantity numeric NOT NULL,
    unit_price_base numeric(20,6) NOT NULL,
    revenue_total_base numeric(24,6) NOT NULL,
    cogs_total_base numeric(24,6) NOT NULL,
    description text,
    CONSTRAINT sale_return_line_quantity CHECK (
        quantity>0 AND quantity=round(quantity,3)
    ),
    CONSTRAINT sale_return_line_values CHECK (
        unit_price_base>0
        AND revenue_total_base=round(quantity*unit_price_base,6)
        AND cogs_total_base>=0
    ),
    CONSTRAINT sale_return_line_number_unique UNIQUE(sale_return_id,line_number),
    CONSTRAINT sale_return_source_unique UNIQUE(sale_return_id,source_sale_line_id)
);

CREATE TABLE IF NOT EXISTS sale_return_cost_restorations (
    restoration_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_return_line_id bigint NOT NULL
        REFERENCES sale_return_lines(sale_return_line_id),
    -- Snapshot lineage ID. FIFO replay rebuilds allocation rows, so this
    -- historical identifier cannot safely retain a live foreign key.
    source_allocation_id bigint NOT NULL,
    quantity numeric NOT NULL,
    unit_cost_base numeric(20,6) NOT NULL,
    total_cost_base numeric(24,6) NOT NULL,
    movement_id bigint NOT NULL UNIQUE REFERENCES stock_movements(movement_id),
    restoration_order integer NOT NULL,
    CONSTRAINT sale_return_restoration_quantity CHECK (
        quantity>0 AND quantity=round(quantity,3)
    ),
    CONSTRAINT sale_return_restoration_value CHECK (
        unit_cost_base>=0
        AND total_cost_base=round(quantity*unit_cost_base,6)
    ),
    CONSTRAINT sale_return_restoration_order_unique
        UNIQUE(sale_return_line_id,restoration_order)
);
ALTER TABLE sale_return_cost_restorations
 DROP CONSTRAINT IF EXISTS sale_return_cost_restorations_source_allocation_id_fkey;

CREATE TABLE IF NOT EXISTS sale_return_revisions (
    sale_return_revision_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_return_id bigint NOT NULL REFERENCES sale_return_invoices(sale_return_id),
    revision_number integer NOT NULL,
    previous_document jsonb NOT NULL,
    changed_by integer,
    changed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(sale_return_id,revision_number)
);

CREATE INDEX IF NOT EXISTS sale_return_date_idx
    ON sale_return_invoices(return_date,sale_return_id);
CREATE INDEX IF NOT EXISTS sale_return_source_line_idx
    ON sale_return_lines(source_sale_line_id);

CREATE OR REPLACE FUNCTION quantity_protect_sale_return()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF current_setting('financee.sale_return_engine',true)='allowed' THEN
        RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
    END IF;
    RAISE EXCEPTION 'Posted sale-return records are immutable; use return operations.'
        USING ERRCODE='check_violation';
END;
$$;

DROP TRIGGER IF EXISTS sale_return_invoices_guard ON sale_return_invoices;
CREATE TRIGGER sale_return_invoices_guard BEFORE UPDATE OR DELETE
ON sale_return_invoices FOR EACH ROW EXECUTE FUNCTION quantity_protect_sale_return();
DROP TRIGGER IF EXISTS sale_return_lines_guard ON sale_return_lines;
CREATE TRIGGER sale_return_lines_guard BEFORE UPDATE OR DELETE
ON sale_return_lines FOR EACH ROW EXECUTE FUNCTION quantity_protect_sale_return();
DROP TRIGGER IF EXISTS sale_return_restorations_guard ON sale_return_cost_restorations;
CREATE TRIGGER sale_return_restorations_guard BEFORE UPDATE OR DELETE
ON sale_return_cost_restorations FOR EACH ROW EXECUTE FUNCTION quantity_protect_sale_return();
DROP TRIGGER IF EXISTS sale_return_revisions_guard ON sale_return_revisions;
CREATE TRIGGER sale_return_revisions_guard BEFORE UPDATE OR DELETE
ON sale_return_revisions FOR EACH ROW EXECUTE FUNCTION quantity_protect_sale_return();

CREATE OR REPLACE FUNCTION quantity_guard_sale_with_returns()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.status='posted' AND NEW.status<>OLD.status AND EXISTS (
        SELECT 1 FROM sale_return_lines rl
        JOIN sale_return_invoices r USING(sale_return_id)
        WHERE rl.source_sale_line_id IN (
            SELECT sale_line_id FROM sale_lines
             WHERE sale_invoice_id=OLD.sale_invoice_id
        ) AND r.status='posted'
    ) THEN
        RAISE EXCEPTION 'Sale cannot be changed after a posted return.'
            USING ERRCODE='check_violation';
    END IF;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS sale_invoices_return_guard ON sale_invoices;
CREATE TRIGGER sale_invoices_return_guard BEFORE UPDATE ON sale_invoices
FOR EACH ROW EXECUTE FUNCTION quantity_guard_sale_with_returns();

CREATE OR REPLACE FUNCTION quantity_sale_return_fingerprint(data jsonb)
RETURNS varchar LANGUAGE sql IMMUTABLE AS $$
 SELECT md5(jsonb_build_object(
   'return_date',data->>'return_date',
   'customer_name',upper(btrim(COALESCE(data->>'customer_name',data->>'party_name',''))),
   'description',btrim(COALESCE(data->>'description','')),
   'lines',COALESCE(data->'lines',data->'items','[]'::jsonb)
 )::text);
$$;

CREATE OR REPLACE FUNCTION quantity_sale_return_details(p_id bigint)
RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT jsonb_build_object(
   'sale_return_id',r.sale_return_id,'document_number',r.document_number,
   'return_date',r.return_date,'customer_name',r.customer_name,
   'description',r.description,'status',r.status,
   'revision_number',r.revision_number,
   'revenue_total_base',r.revenue_total_base,'cogs_total_base',r.cogs_total_base,
   'lines',COALESCE(jsonb_agg(jsonb_build_object(
      'sale_return_line_id',l.sale_return_line_id,'line_number',l.line_number,
      'source_sale_line_id',l.source_sale_line_id,
      'source_sale_invoice_id',s.sale_invoice_id,
      'source_document_number',i.document_number,'variant_id',l.variant_id,
      'sku',v.sku,'product_name',p.product_name,'unit_code',u.code,
      'source_warehouse_id',l.source_warehouse_id,
      'destination_warehouse_id',l.destination_warehouse_id,
      'warehouse_code',w.warehouse_code,'warehouse_name',w.warehouse_name,
      'quantity',l.quantity,'unit_price_base',l.unit_price_base,
      'revenue_total_base',l.revenue_total_base,
      'cogs_total_base',l.cogs_total_base,'description',l.description
   ) ORDER BY l.line_number) FILTER(WHERE l.sale_return_line_id IS NOT NULL),'[]'::jsonb))
 FROM sale_return_invoices r
 LEFT JOIN sale_return_lines l USING(sale_return_id)
 LEFT JOIN sale_lines s ON s.sale_line_id=l.source_sale_line_id
 LEFT JOIN sale_invoices i ON i.sale_invoice_id=s.sale_invoice_id
 LEFT JOIN product_variants v ON v.variant_id=l.variant_id
 LEFT JOIN products p ON p.product_id=v.product_id
 LEFT JOIN units_of_measure u ON u.unit_id=v.unit_id
 LEFT JOIN warehouses w ON w.warehouse_id=l.destination_warehouse_id
 WHERE r.sale_return_id=p_id GROUP BY r.sale_return_id;
$$;

CREATE OR REPLACE FUNCTION quantity_sale_return_sources(p_customer text DEFAULT NULL)
RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT COALESCE(jsonb_agg(jsonb_build_object(
   'source_sale_line_id',l.sale_line_id,'sale_invoice_id',i.sale_invoice_id,
   'document_number',i.document_number,'invoice_date',i.invoice_date,
   'customer_name',i.customer_name,'variant_id',l.variant_id,'sku',v.sku,
   'product_name',p.product_name,'unit_code',u.code,
   'source_warehouse_id',l.warehouse_id,'warehouse_code',w.warehouse_code,
   'warehouse_name',w.warehouse_name,'sold_quantity',l.quantity,
   'returned_quantity',COALESCE(r.returned,0),
   'returnable_quantity',l.quantity-COALESCE(r.returned,0),
   'unit_price_base',l.unit_price_base
 ) ORDER BY i.sale_invoice_id DESC,l.line_number),'[]'::jsonb)
 FROM sale_lines l JOIN sale_invoices i USING(sale_invoice_id)
 JOIN product_variants v USING(variant_id) JOIN products p USING(product_id)
 JOIN units_of_measure u USING(unit_id) JOIN warehouses w USING(warehouse_id)
 LEFT JOIN LATERAL (
   SELECT sum(rl.quantity) returned FROM sale_return_lines rl
   JOIN sale_return_invoices ri USING(sale_return_id)
   WHERE rl.source_sale_line_id=l.sale_line_id AND ri.status='posted'
 ) r ON true
 WHERE i.status='posted' AND l.quantity>COALESCE(r.returned,0)
 AND (p_customer IS NULL OR upper(i.customer_name)=upper(btrim(p_customer)));
$$;

CREATE OR REPLACE FUNCTION quantity_sale_return_post_lines(
    p_return_id bigint,p_lines jsonb,p_user integer
) RETURNS TABLE(revenue numeric,cogs numeric) LANGUAGE plpgsql AS $$
DECLARE
    h sale_return_invoices%ROWTYPE; x jsonb; src sale_lines%ROWTYPE;
    inv sale_invoices%ROWTYPE; n integer:=0; dest bigint; qty numeric;
    prior numeric; skip_qty numeric; remaining numeric; take_qty numeric;
    rev numeric(24,6):=0; cost numeric(24,6):=0; line_cost numeric(24,6);
    line_id bigint; alloc record; movement jsonb; restoration_n integer;
BEGIN
 SELECT * INTO h FROM sale_return_invoices WHERE sale_return_id=p_return_id FOR UPDATE;
 FOR x IN SELECT value FROM jsonb_array_elements(p_lines) LOOP
   n:=n+1;
   BEGIN
     SELECT * INTO src FROM sale_lines
      WHERE sale_line_id=(x->>'source_sale_line_id')::bigint FOR UPDATE;
     dest:=COALESCE(NULLIF(x->>'destination_warehouse_id','')::bigint,
                    src.warehouse_id);
     qty:=COALESCE(NULLIF(x->>'quantity','')::numeric,NULLIF(x->>'qty','')::numeric);
   EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
     RAISE EXCEPTION 'Sale-return line % is invalid.',n USING ERRCODE='check_violation';
   END;
   IF NOT FOUND THEN RAISE EXCEPTION 'Source sale line not found.'
      USING ERRCODE='foreign_key_violation'; END IF;
   SELECT * INTO inv FROM sale_invoices WHERE sale_invoice_id=src.sale_invoice_id FOR UPDATE;
   IF inv.status<>'posted' THEN RAISE EXCEPTION 'Source sale is not posted.'
      USING ERRCODE='check_violation'; END IF;
   IF upper(btrim(inv.customer_name))<>upper(btrim(h.customer_name)) THEN
     RAISE EXCEPTION 'Return customer does not match the source sale.'
       USING ERRCODE='check_violation';
   END IF;
   PERFORM quantity_validate_quantity(src.variant_id,qty);
   IF NOT EXISTS(SELECT 1 FROM warehouses WHERE warehouse_id=dest AND is_active) THEN
     RAISE EXCEPTION 'Return destination warehouse is inactive.'
       USING ERRCODE='foreign_key_violation';
   END IF;
   SELECT COALESCE(sum(l.quantity),0) INTO prior
     FROM sale_return_lines l JOIN sale_return_invoices r USING(sale_return_id)
    WHERE l.source_sale_line_id=src.sale_line_id AND r.status='posted';
   IF prior+qty>src.quantity THEN
     RAISE EXCEPTION 'Return quantity exceeds the remaining source quantity.'
       USING ERRCODE='check_violation';
   END IF;
   INSERT INTO sale_return_lines(
     sale_return_id,line_number,source_sale_line_id,variant_id,
     source_warehouse_id,destination_warehouse_id,quantity,unit_price_base,
     revenue_total_base,cogs_total_base,description
   ) VALUES(p_return_id,n,src.sale_line_id,src.variant_id,src.warehouse_id,dest,
     qty,src.unit_price_base,round(qty*src.unit_price_base,6),0,
     NULLIF(btrim(x->>'description'),''))
   RETURNING sale_return_line_id INTO line_id;
   skip_qty:=prior; remaining:=qty; line_cost:=0; restoration_n:=0;
   FOR alloc IN
     SELECT fa.* FROM fifo_allocations fa
      WHERE fa.outbound_movement_id=src.movement_id ORDER BY fa.allocation_order
      FOR UPDATE
   LOOP
     IF skip_qty>=alloc.quantity THEN skip_qty:=skip_qty-alloc.quantity; CONTINUE; END IF;
     take_qty:=LEAST(remaining,alloc.quantity-skip_qty);
     restoration_n:=restoration_n+1;
     movement:=quantity_post_stock_movement(
       'sale_return',src.variant_id,dest,h.return_date,take_qty,
       alloc.unit_cost_base,'sale_return',p_return_id,
       n*1000+restoration_n,h.document_number,p_user,
       COALESCE(NULLIF(btrim(x->>'description'),''),h.description,'Sale return')
     );
     INSERT INTO sale_return_cost_restorations(
       sale_return_line_id,source_allocation_id,quantity,unit_cost_base,
       total_cost_base,movement_id,restoration_order
     ) VALUES(line_id,alloc.allocation_id,take_qty,alloc.unit_cost_base,
       round(take_qty*alloc.unit_cost_base,6),
       (movement->>'movement_id')::bigint,restoration_n);
     line_cost:=line_cost+round(take_qty*alloc.unit_cost_base,6);
     remaining:=remaining-take_qty; skip_qty:=0;
     EXIT WHEN remaining=0;
   END LOOP;
   IF remaining<>0 THEN RAISE EXCEPTION 'Original FIFO allocation is incomplete.'
      USING ERRCODE='check_violation'; END IF;
   UPDATE sale_return_lines SET cogs_total_base=line_cost
    WHERE sale_return_line_id=line_id;
   rev:=rev+round(qty*src.unit_price_base,6); cost:=cost+line_cost;
 END LOOP;
 IF n=0 THEN RAISE EXCEPTION 'At least one return line is required.'
    USING ERRCODE='check_violation'; END IF;
 revenue:=rev; cogs:=cost; RETURN NEXT;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_sale_return_post_journal(
 p_id bigint,p_user integer,p_revision boolean DEFAULT false
) RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE h sale_return_invoices%ROWTYPE; original sale_invoices%ROWTYPE;
 account_code varchar; source_type varchar; source_id bigint;
BEGIN
 SELECT * INTO h FROM sale_return_invoices WHERE sale_return_id=p_id FOR UPDATE;
 SELECT i.* INTO original FROM sale_invoices i JOIN sale_lines s
   ON s.sale_invoice_id=i.sale_invoice_id JOIN sale_return_lines l
   ON l.source_sale_line_id=s.sale_line_id WHERE l.sale_return_id=p_id LIMIT 1;
 account_code:=CASE WHEN original.sale_type='credit' THEN '1200'
                    ELSE original.payment_account_code END;
 source_type:=CASE WHEN p_revision THEN 'sale_return_revision' ELSE 'sale_return' END;
 source_id:=CASE WHEN p_revision THEN p_id*1000000+h.revision_number ELSE p_id END;
 RETURN quantity_post_journal(h.return_date,'Sale return '||h.document_number,
   source_type,source_id,h.document_number,p_user,jsonb_build_array(
    jsonb_build_object('account_code','4000','debit',round(h.revenue_total_base,4),
      'credit',0,'description','Sales return'),
    jsonb_build_object('account_code',account_code,'debit',0,
      'credit',round(h.revenue_total_base,4),'description','Refund/customer credit'),
    jsonb_build_object('account_code','1400','debit',round(h.cogs_total_base,4),
      'credit',0,'description','Inventory restored'),
    jsonb_build_object('account_code','5000','debit',0,
      'credit',round(h.cogs_total_base,4),'description','COGS reversed')
   ));
END;
$$;

CREATE OR REPLACE FUNCTION quantity_create_sale_return(data jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE d date; customer varchar; descr text; lines jsonb; usr integer;
 key varchar; fp varchar; existing sale_return_invoices%ROWTYPE;
 id bigint; number text; totals record; journal bigint; pairs jsonb;
BEGIN
 BEGIN d:=(data->>'return_date')::date; usr:=NULLIF(data->>'created_by_id','')::integer;
 EXCEPTION WHEN others THEN RAISE EXCEPTION 'Return date or user is invalid.'
   USING ERRCODE='check_violation'; END;
 customer:=btrim(COALESCE(data->>'customer_name',data->>'party_name',''));
 descr:=NULLIF(btrim(COALESCE(data->>'description','')),'');
 lines:=COALESCE(data->'lines',data->'items'); key:=btrim(COALESCE(data->>'idempotency_key',''));
 IF d IS NULL OR customer='' OR lines IS NULL OR jsonb_typeof(lines)<>'array'
    OR jsonb_array_length(lines)=0 OR key='' OR length(key)>100 THEN
   RAISE EXCEPTION 'Return date, customer, lines, and idempotency key are required.'
    USING ERRCODE='check_violation';
 END IF;
 fp:=quantity_sale_return_fingerprint(data);
 PERFORM pg_advisory_xact_lock(hashtextextended(current_schema()||':sale-return:'||key,0));
 SELECT * INTO existing FROM sale_return_invoices WHERE idempotency_key=key FOR UPDATE;
 IF FOUND THEN
  IF existing.request_fingerprint=fp THEN RETURN jsonb_build_object(
   'status','success','idempotent',true,'sale_return_id',existing.sale_return_id,
   'document_number',existing.document_number,'revenue_total_base',existing.revenue_total_base,
   'cogs_total_base',existing.cogs_total_base); END IF;
  RAISE EXCEPTION 'Idempotency key reused with different return data.'
    USING ERRCODE='unique_violation';
 END IF;
 SELECT jsonb_agg(jsonb_build_object('variant_id',s.variant_id,
   'warehouse_id',COALESCE(NULLIF(x.value->>'destination_warehouse_id','')::bigint,s.warehouse_id)))
 INTO pairs FROM jsonb_array_elements(lines) x
 JOIN sale_lines s ON s.sale_line_id=(x.value->>'source_sale_line_id')::bigint;
 PERFORM quantity_lock_inventory_pairs(pairs);
 number:=quantity_next_document_number('sale_return');
 PERFORM set_config('financee.sale_return_engine','allowed',true);
 INSERT INTO sale_return_invoices(document_number,return_date,customer_name,
   description,status,idempotency_key,request_fingerprint,created_by,updated_by)
 VALUES(number,d,customer,descr,'draft',key,fp,usr,usr) RETURNING sale_return_id INTO id;
 SELECT * INTO totals FROM quantity_sale_return_post_lines(id,lines,usr);
 UPDATE sale_return_invoices SET revenue_total_base=totals.revenue,
   cogs_total_base=totals.cogs WHERE sale_return_id=id;
 journal:=quantity_sale_return_post_journal(id,usr,false);
 UPDATE sale_return_invoices SET status='posted',journal_id=journal WHERE sale_return_id=id;
 PERFORM set_config('financee.sale_return_engine','',true);
 RETURN jsonb_build_object('status','success','idempotent',false,
   'sale_return_id',id,'document_number',number,'revenue_total_base',totals.revenue,
   'cogs_total_base',totals.cogs,'journal_id',journal);
END;
$$;

CREATE OR REPLACE FUNCTION quantity_reverse_sale_return(
 p_id bigint,p_date date,p_user integer
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE h sale_return_invoices%ROWTYPE; r record; j bigint;
BEGIN
 SELECT * INTO h FROM sale_return_invoices WHERE sale_return_id=p_id FOR UPDATE;
 IF NOT FOUND OR h.status<>'posted' THEN RAISE EXCEPTION 'Posted sale return not found.'
  USING ERRCODE='check_violation'; END IF;
 IF p_date<h.return_date THEN RAISE EXCEPTION 'Reversal date precedes return date.'
  USING ERRCODE='check_violation'; END IF;
 FOR r IN SELECT cr.*,fl.remaining_quantity,fl.original_quantity
   FROM sale_return_cost_restorations cr JOIN fifo_layers fl
     ON fl.inbound_movement_id=cr.movement_id
   JOIN sale_return_lines l USING(sale_return_line_id)
   WHERE l.sale_return_id=p_id ORDER BY cr.restoration_id FOR UPDATE OF fl
 LOOP
   IF r.remaining_quantity<>r.original_quantity THEN
    RAISE EXCEPTION 'Sale return cannot be reversed after returned stock was consumed.'
      USING ERRCODE='check_violation';
   END IF;
   PERFORM quantity_reverse_stock_movement(r.movement_id,p_date,
     p_id*1000000+r.restoration_id,p_user);
 END LOOP;
 j:=quantity_reverse_journal(h.journal_id,p_date,
   'Reverse sale return '||h.document_number,p_user);
 PERFORM set_config('financee.sale_return_engine','allowed',true);
 UPDATE sale_return_invoices SET status='reversed',reversal_journal_id=j,
   reversed_by=p_user,reversed_at=CURRENT_TIMESTAMP,updated_by=p_user,
   updated_at=CURRENT_TIMESTAMP WHERE sale_return_id=p_id;
 PERFORM set_config('financee.sale_return_engine','',true);
 RETURN jsonb_build_object('status','success','sale_return_id',p_id,
   'document_number',h.document_number,'reversal_journal_id',j);
END;
$$;

CREATE OR REPLACE FUNCTION quantity_update_sale_return(
 p_id bigint,data jsonb
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE h sale_return_invoices%ROWTYPE; usr integer; replacement jsonb;
BEGIN
 SELECT * INTO h FROM sale_return_invoices WHERE sale_return_id=p_id FOR UPDATE;
 IF NOT FOUND OR h.status<>'posted' THEN
  RAISE EXCEPTION 'Only posted sale returns can be updated.'
   USING ERRCODE='check_violation';
 END IF;
 BEGIN usr:=NULLIF(data->>'created_by_id','')::integer;
 EXCEPTION WHEN others THEN RAISE EXCEPTION 'Return user is invalid.'
  USING ERRCODE='check_violation'; END;
 PERFORM set_config('financee.sale_return_engine','allowed',true);
 INSERT INTO sale_return_revisions(
   sale_return_id,revision_number,previous_document,changed_by
 ) VALUES(p_id,h.revision_number,quantity_sale_return_details(p_id),usr);
 PERFORM set_config('financee.sale_return_engine','',true);
 PERFORM quantity_reverse_sale_return(
   p_id,COALESCE(NULLIF(data->>'return_date','')::date,CURRENT_DATE),usr
 );
 data:=jsonb_set(data,'{idempotency_key}',
   to_jsonb(COALESCE(NULLIF(data->>'idempotency_key',''),
    'sale-return-update-'||p_id||'-'||(h.revision_number+1))));
 replacement:=quantity_create_sale_return(data);
 RETURN replacement||jsonb_build_object(
   'replaced_sale_return_id',p_id,
   'previous_document_number',h.document_number,
   'revision_number',h.revision_number+1
 );
END;
$$;

CREATE OR REPLACE FUNCTION quantity_sale_return_navigate(
 action text,current_id bigint DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE id bigint;
BEGIN
 CASE lower(COALESCE(action,'last'))
 WHEN 'current' THEN id:=current_id;
 WHEN 'previous' THEN SELECT max(sale_return_id) INTO id FROM sale_return_invoices WHERE sale_return_id<current_id;
 WHEN 'next' THEN SELECT min(sale_return_id) INTO id FROM sale_return_invoices WHERE sale_return_id>current_id;
 WHEN 'first' THEN SELECT min(sale_return_id) INTO id FROM sale_return_invoices;
 WHEN 'last' THEN SELECT max(sale_return_id) INTO id FROM sale_return_invoices;
 ELSE RAISE EXCEPTION 'Unknown navigation action.' USING ERRCODE='check_violation'; END CASE;
 RETURN quantity_sale_return_details(id);
END;
$$;

CREATE OR REPLACE FUNCTION quantity_sale_return_summary(
 from_date date DEFAULT NULL,to_date date DEFAULT NULL
) RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT jsonb_build_object('invoice_count',count(*)::integer,
  'posted_count',count(*) FILTER(WHERE status='posted')::integer,
  'reversed_count',count(*) FILTER(WHERE status='reversed')::integer,
  'revenue_total_base',COALESCE(sum(revenue_total_base) FILTER(WHERE status='posted'),0),
  'cogs_total_base',COALESCE(sum(cogs_total_base) FILTER(WHERE status='posted'),0),
  'documents',COALESCE(jsonb_agg(jsonb_build_object(
    'sale_return_id',sale_return_id,'document_number',document_number,
    'return_date',return_date,'customer_name',customer_name,'status',status,
    'revenue_total_base',revenue_total_base,'cogs_total_base',cogs_total_base
  ) ORDER BY sale_return_id DESC),'[]'::jsonb))
 FROM sale_return_invoices WHERE (from_date IS NULL OR return_date>=from_date)
 AND (to_date IS NULL OR return_date<=to_date);
$$;

INSERT INTO quantity_seed_registry(seed_key,seed_version,payload)
VALUES('quantity.sale_returns',1,
 '{"source":"sale_lines/fifo_allocations","partial":true,"exact_cost":true}'::jsonb)
ON CONFLICT(seed_key) DO UPDATE SET seed_version=GREATEST(
 quantity_seed_registry.seed_version,EXCLUDED.seed_version),
 payload=EXCLUDED.payload,applied_at=CURRENT_TIMESTAMP;
UPDATE tenant_schema_metadata SET version=GREATEST(version,9),
 applied_at=CURRENT_TIMESTAMP WHERE id=true AND family='quantity';
