-- Idempotent Phase 11 domestic purchase lifecycle for QUANTITY schemas, v7.
DO $$
BEGIN
    IF to_regclass('tenant_schema_metadata') IS NULL
       OR NOT EXISTS (
           SELECT 1 FROM tenant_schema_metadata
            WHERE id = true AND family = 'quantity' AND version >= 6
       ) THEN
        RAISE EXCEPTION 'Quantity purchase rollout refused: family/version mismatch.';
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS purchase_invoices (
    purchase_invoice_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_number varchar(32) NOT NULL UNIQUE,
    invoice_date date NOT NULL,
    vendor_name varchar(200) NOT NULL,
    purchase_type varchar(10) NOT NULL,
    payment_account_code varchar(20),
    description text,
    status varchar(10) NOT NULL DEFAULT 'draft',
    revision_number integer NOT NULL DEFAULT 1,
    subtotal_base numeric(24,6) NOT NULL DEFAULT 0,
    total_base numeric(24,6) NOT NULL DEFAULT 0,
    journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
    reversal_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
    idempotency_key varchar(100) NOT NULL UNIQUE,
    request_fingerprint varchar(32) NOT NULL,
    created_by integer,
    updated_by integer,
    reversed_by integer,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reversed_at timestamptz,
    CONSTRAINT purchase_vendor_required CHECK (btrim(vendor_name) <> ''),
    CONSTRAINT purchase_type_check CHECK (purchase_type IN ('credit', 'cash')),
    CONSTRAINT purchase_payment_account_check CHECK (
        (purchase_type='credit' AND payment_account_code IS NULL)
        OR
        (purchase_type='cash' AND payment_account_code IN ('1000','1100'))
    ),
    CONSTRAINT purchase_status_check CHECK (
        status IN ('draft','posted','reversed')
    ),
    CONSTRAINT purchase_revision_positive CHECK (revision_number > 0),
    CONSTRAINT purchase_totals_check CHECK (
        subtotal_base >= 0 AND total_base >= 0
        AND subtotal_base = total_base
    ),
    CONSTRAINT purchase_posting_shape_check CHECK (
        (status='draft' AND journal_id IS NULL
         AND reversal_journal_id IS NULL AND reversed_at IS NULL)
        OR
        (status='posted' AND journal_id IS NOT NULL
         AND reversal_journal_id IS NULL AND reversed_at IS NULL)
        OR
        (status='reversed' AND journal_id IS NOT NULL
         AND reversal_journal_id IS NOT NULL AND reversed_at IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS purchase_lines (
    purchase_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_invoice_id bigint NOT NULL
        REFERENCES purchase_invoices(purchase_invoice_id),
    line_number integer NOT NULL,
    variant_id bigint NOT NULL REFERENCES product_variants(variant_id),
    warehouse_id bigint NOT NULL REFERENCES warehouses(warehouse_id),
    quantity numeric NOT NULL,
    unit_cost_base numeric(20,6) NOT NULL,
    line_total_base numeric(24,6) NOT NULL,
    description text,
    movement_id bigint NOT NULL UNIQUE REFERENCES stock_movements(movement_id),
    CONSTRAINT purchase_line_number_positive CHECK (line_number > 0),
    CONSTRAINT purchase_line_quantity_positive CHECK (
        quantity > 0 AND quantity=round(quantity,3)
    ),
    CONSTRAINT purchase_line_cost_positive CHECK (unit_cost_base > 0),
    CONSTRAINT purchase_line_total_check CHECK (
        line_total_base=round(quantity*unit_cost_base,6)
    ),
    CONSTRAINT purchase_line_number_unique
        UNIQUE (purchase_invoice_id,line_number),
    CONSTRAINT purchase_line_scope_unique
        UNIQUE (purchase_invoice_id,variant_id,warehouse_id)
);

CREATE TABLE IF NOT EXISTS purchase_revisions (
    purchase_revision_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_invoice_id bigint NOT NULL
        REFERENCES purchase_invoices(purchase_invoice_id),
    revision_number integer NOT NULL,
    previous_document jsonb NOT NULL,
    changed_by integer,
    changed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT purchase_revision_unique
        UNIQUE (purchase_invoice_id,revision_number),
    CONSTRAINT purchase_revision_snapshot_object CHECK (
        jsonb_typeof(previous_document)='object'
    )
);

CREATE INDEX IF NOT EXISTS purchase_invoices_date_idx
    ON purchase_invoices(invoice_date,purchase_invoice_id);
CREATE INDEX IF NOT EXISTS purchase_invoices_vendor_idx
    ON purchase_invoices(lower(vendor_name),purchase_invoice_id);
CREATE INDEX IF NOT EXISTS purchase_lines_variant_warehouse_idx
    ON purchase_lines(variant_id,warehouse_id);

CREATE OR REPLACE FUNCTION quantity_protect_purchase()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF current_setting('financee.purchase_engine',true)='allowed' THEN
        RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
    END IF;
    RAISE EXCEPTION 'Posted purchase records are immutable; use purchase operations.'
        USING ERRCODE='check_violation';
END;
$$;

DROP TRIGGER IF EXISTS purchase_invoices_write_guard ON purchase_invoices;
CREATE TRIGGER purchase_invoices_write_guard
BEFORE UPDATE OR DELETE ON purchase_invoices
FOR EACH ROW EXECUTE FUNCTION quantity_protect_purchase();
DROP TRIGGER IF EXISTS purchase_lines_write_guard ON purchase_lines;
CREATE TRIGGER purchase_lines_write_guard
BEFORE UPDATE OR DELETE ON purchase_lines
FOR EACH ROW EXECUTE FUNCTION quantity_protect_purchase();
DROP TRIGGER IF EXISTS purchase_revisions_write_guard ON purchase_revisions;
CREATE TRIGGER purchase_revisions_write_guard
BEFORE UPDATE OR DELETE ON purchase_revisions
FOR EACH ROW EXECUTE FUNCTION quantity_protect_purchase();

CREATE OR REPLACE FUNCTION quantity_purchase_normalized_fingerprint(data jsonb)
RETURNS varchar LANGUAGE sql IMMUTABLE AS $$
    SELECT md5(jsonb_build_object(
        'invoice_date',COALESCE(data->>'invoice_date',data->>'purchase_date'),
        'vendor_name',upper(btrim(COALESCE(data->>'vendor_name',
                                          data->>'party_name',''))),
        'purchase_type',lower(COALESCE(data->>'purchase_type','credit')),
        'payment_account_code',COALESCE(data->>'payment_account_code',''),
        'description',btrim(COALESCE(data->>'description','')),
        'lines',COALESCE(data->'lines',data->'items','[]'::jsonb)
    )::text);
$$;

CREATE OR REPLACE FUNCTION quantity_purchase_validate_header(
    data jsonb, OUT invoice_date date, OUT vendor_name varchar,
    OUT purchase_type varchar, OUT payment_account_code varchar,
    OUT description text, OUT created_by integer, OUT lines jsonb
) RETURNS record LANGUAGE plpgsql AS $$
BEGIN
    IF data IS NULL OR jsonb_typeof(data)<>'object' THEN
        RAISE EXCEPTION 'Purchase payload must be an object.'
            USING ERRCODE='check_violation';
    END IF;
    BEGIN
        invoice_date := COALESCE(
            NULLIF(data->>'invoice_date','')::date,
            NULLIF(data->>'purchase_date','')::date
        );
        created_by := NULLIF(COALESCE(data->>'created_by_id',
                                     data->>'user_id'),'')::integer;
    EXCEPTION WHEN invalid_text_representation OR datetime_field_overflow
                   OR numeric_value_out_of_range THEN
        RAISE EXCEPTION 'Purchase date or user is invalid.'
            USING ERRCODE='check_violation';
    END;
    IF invoice_date IS NULL THEN
        RAISE EXCEPTION 'Purchase date is required.'
            USING ERRCODE='not_null_violation';
    END IF;
    vendor_name := btrim(COALESCE(data->>'vendor_name',
                                  data->>'party_name',''));
    purchase_type := lower(COALESCE(NULLIF(data->>'purchase_type',''),'credit'));
    IF purchase_type NOT IN ('credit','cash') THEN
        RAISE EXCEPTION 'Purchase type must be credit or cash.'
            USING ERRCODE='check_violation';
    END IF;
    IF vendor_name='' THEN
        IF purchase_type='cash' THEN vendor_name := 'Cash Purchase';
        ELSE
            RAISE EXCEPTION 'Vendor name is required for a credit purchase.'
                USING ERRCODE='check_violation';
        END IF;
    END IF;
    IF length(vendor_name)>200 THEN
        RAISE EXCEPTION 'Vendor name is too long.'
            USING ERRCODE='check_violation';
    END IF;
    payment_account_code := NULL;
    IF purchase_type='cash' THEN
        payment_account_code := COALESCE(
            NULLIF(data->>'payment_account_code',''),'1000'
        );
        IF payment_account_code NOT IN ('1000','1100') THEN
            RAISE EXCEPTION 'Cash purchases must use Cash or Bank.'
                USING ERRCODE='check_violation';
        END IF;
    END IF;
    description := NULLIF(btrim(COALESCE(data->>'description','')),'');
    lines := COALESCE(data->'lines',data->'items');
    IF lines IS NULL OR jsonb_typeof(lines)<>'array'
       OR jsonb_array_length(lines)=0 THEN
        RAISE EXCEPTION 'At least one purchase line is required.'
            USING ERRCODE='check_violation';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_purchase_post_lines(
    p_purchase_invoice_id bigint,p_lines jsonb,p_user_id integer
) RETURNS numeric LANGUAGE plpgsql AS $$
DECLARE
    v_invoice purchase_invoices%ROWTYPE;
    v_line jsonb;
    v_line_number integer := 0;
    v_variant_id bigint;
    v_warehouse_id bigint;
    v_quantity numeric;
    v_unit_cost numeric(20,6);
    v_total numeric(24,6) := 0;
    v_line_total numeric(24,6);
    v_movement jsonb;
BEGIN
    SELECT * INTO v_invoice FROM purchase_invoices
     WHERE purchase_invoice_id=p_purchase_invoice_id FOR UPDATE;
    IF NOT FOUND OR v_invoice.status<>'draft' THEN
        RAISE EXCEPTION 'Purchase draft not found.'
            USING ERRCODE='foreign_key_violation';
    END IF;
    FOR v_line IN SELECT value FROM jsonb_array_elements(p_lines)
    LOOP
        v_line_number := v_line_number+1;
        BEGIN
            v_variant_id := (v_line->>'variant_id')::bigint;
            v_warehouse_id := (v_line->>'warehouse_id')::bigint;
            v_quantity := COALESCE(
                NULLIF(v_line->>'quantity','')::numeric,
                NULLIF(v_line->>'qty','')::numeric
            );
            v_unit_cost := COALESCE(
                NULLIF(v_line->>'unit_cost_base','')::numeric,
                NULLIF(v_line->>'unit_price','')::numeric
            );
        EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
            RAISE EXCEPTION 'Purchase line % contains invalid numbers.',
                v_line_number USING ERRCODE='check_violation';
        END;
        PERFORM quantity_validate_quantity(v_variant_id,v_quantity);
        IF NOT EXISTS (
            SELECT 1 FROM warehouses
             WHERE warehouse_id=v_warehouse_id AND is_active
        ) THEN
            RAISE EXCEPTION 'Purchase line % uses an inactive warehouse.',
                v_line_number USING ERRCODE='foreign_key_violation';
        END IF;
        IF v_unit_cost IS NULL OR v_unit_cost<=0
           OR v_unit_cost<>round(v_unit_cost,6) THEN
            RAISE EXCEPTION 'Purchase line % has an invalid unit cost.',
                v_line_number USING ERRCODE='check_violation';
        END IF;
        IF EXISTS (
            SELECT 1 FROM purchase_lines
             WHERE purchase_invoice_id=p_purchase_invoice_id
               AND variant_id=v_variant_id AND warehouse_id=v_warehouse_id
        ) THEN
            RAISE EXCEPTION 'Duplicate SKU and warehouse in purchase.'
                USING ERRCODE='unique_violation';
        END IF;
        v_line_total := round(v_quantity*v_unit_cost,6);
        v_movement := quantity_post_stock_movement(
            'purchase',v_variant_id,v_warehouse_id,v_invoice.invoice_date,
            v_quantity,v_unit_cost,'purchase',p_purchase_invoice_id,
            v_line_number,v_invoice.document_number,p_user_id,
            COALESCE(NULLIF(btrim(v_line->>'description'),''),
                     v_invoice.description,'Purchase')
        );
        INSERT INTO purchase_lines (
            purchase_invoice_id,line_number,variant_id,warehouse_id,quantity,
            unit_cost_base,line_total_base,description,movement_id
        ) VALUES (
            p_purchase_invoice_id,v_line_number,v_variant_id,v_warehouse_id,
            v_quantity,v_unit_cost,v_line_total,
            NULLIF(btrim(v_line->>'description'),''),
            (v_movement->>'movement_id')::bigint
        );
        v_total := v_total+v_line_total;
    END LOOP;
    IF round(v_total,4)<=0 THEN
        RAISE EXCEPTION 'Purchase must have a positive accounting value.'
            USING ERRCODE='check_violation';
    END IF;
    RETURN v_total;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_purchase_post_journal(
    p_purchase_invoice_id bigint,p_user_id integer,p_revision boolean DEFAULT false
) RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
    v_invoice purchase_invoices%ROWTYPE;
    v_counterparty_code varchar;
    v_source_type varchar;
    v_source_id bigint;
BEGIN
    SELECT * INTO v_invoice FROM purchase_invoices
     WHERE purchase_invoice_id=p_purchase_invoice_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Purchase not found.'
            USING ERRCODE='foreign_key_violation';
    END IF;
    v_counterparty_code := CASE WHEN v_invoice.purchase_type='credit'
        THEN '2000' ELSE v_invoice.payment_account_code END;
    v_source_type := CASE WHEN p_revision
        THEN 'purchase_revision' ELSE 'purchase' END;
    v_source_id := CASE WHEN p_revision
        THEN p_purchase_invoice_id*1000000+v_invoice.revision_number
        ELSE p_purchase_invoice_id END;
    RETURN quantity_post_journal(
        v_invoice.invoice_date,'Purchase '||v_invoice.document_number,
        v_source_type,v_source_id,v_invoice.document_number,p_user_id,
        jsonb_build_array(
            jsonb_build_object(
                'account_code','1400','debit',round(v_invoice.total_base,4),
                'credit',0,'description','Inventory purchase'
            ),
            jsonb_build_object(
                'account_code',v_counterparty_code,'debit',0,
                'credit',round(v_invoice.total_base,4),
                'description',CASE WHEN v_invoice.purchase_type='credit'
                    THEN 'Payable: '||v_invoice.vendor_name
                    ELSE v_invoice.vendor_name END
            )
        )
    );
END;
$$;

CREATE OR REPLACE FUNCTION quantity_create_purchase(data jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    v_date date; v_vendor varchar; v_type varchar; v_account varchar;
    v_description text; v_user integer; v_lines jsonb;
    v_key varchar; v_fingerprint varchar;
    v_existing purchase_invoices%ROWTYPE;
    v_id bigint; v_number text; v_total numeric(24,6); v_journal bigint;
    v_pairs jsonb;
BEGIN
    SELECT * INTO v_date,v_vendor,v_type,v_account,v_description,v_user,v_lines
      FROM quantity_purchase_validate_header(data);
    v_key := btrim(COALESCE(data->>'idempotency_key',''));
    IF v_key='' OR length(v_key)>100 THEN
        RAISE EXCEPTION 'A valid idempotency key is required.'
            USING ERRCODE='check_violation';
    END IF;
    v_fingerprint := quantity_purchase_normalized_fingerprint(data);
    PERFORM pg_advisory_xact_lock(
        hashtextextended(current_schema()||':purchase:'||v_key,0)
    );
    SELECT * INTO v_existing FROM purchase_invoices
     WHERE idempotency_key=v_key FOR UPDATE;
    IF FOUND THEN
        IF v_existing.request_fingerprint=v_fingerprint THEN
            RETURN jsonb_build_object(
                'status','success','idempotent',true,
                'purchase_invoice_id',v_existing.purchase_invoice_id,
                'document_number',v_existing.document_number,
                'total_base',v_existing.total_base
            );
        END IF;
        RAISE EXCEPTION 'Idempotency key was reused with different purchase data.'
            USING ERRCODE='unique_violation';
    END IF;
    BEGIN
        SELECT jsonb_agg(jsonb_build_object(
                   'variant_id',(value->>'variant_id')::bigint,
                   'warehouse_id',(value->>'warehouse_id')::bigint
               )) INTO v_pairs FROM jsonb_array_elements(v_lines);
    EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
        RAISE EXCEPTION 'Every purchase line requires SKU and warehouse.'
            USING ERRCODE='check_violation';
    END;
    PERFORM quantity_lock_inventory_pairs(v_pairs);
    v_number := quantity_next_document_number('purchase');
    PERFORM set_config('financee.purchase_engine','allowed',true);
    INSERT INTO purchase_invoices (
        document_number,invoice_date,vendor_name,purchase_type,
        payment_account_code,description,status,idempotency_key,
        request_fingerprint,created_by,updated_by
    ) VALUES (
        v_number,v_date,v_vendor,v_type,v_account,v_description,'draft',
        v_key,v_fingerprint,v_user,v_user
    ) RETURNING purchase_invoice_id INTO v_id;
    v_total := quantity_purchase_post_lines(v_id,v_lines,v_user);
    UPDATE purchase_invoices SET subtotal_base=v_total,total_base=v_total
     WHERE purchase_invoice_id=v_id;
    v_journal := quantity_purchase_post_journal(v_id,v_user,false);
    UPDATE purchase_invoices SET status='posted',journal_id=v_journal
     WHERE purchase_invoice_id=v_id;
    PERFORM set_config('financee.purchase_engine','',true);
    RETURN jsonb_build_object(
        'status','success','idempotent',false,'purchase_invoice_id',v_id,
        'document_number',v_number,'journal_id',v_journal,'total_base',v_total
    );
END;
$$;

CREATE OR REPLACE FUNCTION quantity_purchase_details(p_purchase_invoice_id bigint)
RETURNS jsonb LANGUAGE sql STABLE AS $$
    SELECT jsonb_build_object(
        'purchase_invoice_id',i.purchase_invoice_id,
        'document_number',i.document_number,'invoice_date',i.invoice_date,
        'vendor_name',i.vendor_name,'purchase_type',i.purchase_type,
        'payment_account_code',i.payment_account_code,
        'description',i.description,'status',i.status,
        'revision_number',i.revision_number,'subtotal_base',i.subtotal_base,
        'total_base',i.total_base,'journal_id',i.journal_id,
        'reversal_journal_id',i.reversal_journal_id,
        'created_by',i.created_by,'created_at',i.created_at,
        'updated_by',i.updated_by,'updated_at',i.updated_at,
        'lines',COALESCE(jsonb_agg(jsonb_build_object(
            'purchase_line_id',l.purchase_line_id,'line_number',l.line_number,
            'variant_id',l.variant_id,'sku',v.sku,'product_name',p.product_name,
            'unit_code',u.code,'warehouse_id',l.warehouse_id,
            'warehouse_code',w.warehouse_code,'warehouse_name',w.warehouse_name,
            'quantity',l.quantity,'unit_cost_base',l.unit_cost_base,
            'line_total_base',l.line_total_base,'description',l.description,
            'movement_id',l.movement_id
        ) ORDER BY l.line_number) FILTER (
            WHERE l.purchase_line_id IS NOT NULL
        ),'[]'::jsonb)
    )
      FROM purchase_invoices i
      LEFT JOIN purchase_lines l USING (purchase_invoice_id)
      LEFT JOIN product_variants v ON v.variant_id=l.variant_id
      LEFT JOIN products p ON p.product_id=v.product_id
      LEFT JOIN units_of_measure u ON u.unit_id=v.unit_id
      LEFT JOIN warehouses w ON w.warehouse_id=l.warehouse_id
     WHERE i.purchase_invoice_id=p_purchase_invoice_id
     GROUP BY i.purchase_invoice_id;
$$;

CREATE OR REPLACE FUNCTION quantity_purchase_teardown_lines(
    p_purchase_invoice_id bigint
) RETURNS void LANGUAGE plpgsql AS $$
DECLARE v_scope record;
BEGIN
    CREATE TEMP TABLE IF NOT EXISTS pg_temp.purchase_affected_scopes (
        variant_id bigint,warehouse_id bigint,PRIMARY KEY(variant_id,warehouse_id)
    ) ON COMMIT DROP;
    TRUNCATE pg_temp.purchase_affected_scopes;
    INSERT INTO pg_temp.purchase_affected_scopes
    SELECT DISTINCT variant_id,warehouse_id FROM purchase_lines
     WHERE purchase_invoice_id=p_purchase_invoice_id;
    PERFORM quantity_lock_inventory_pairs((
        SELECT jsonb_agg(jsonb_build_object(
            'variant_id',variant_id,'warehouse_id',warehouse_id
        )) FROM pg_temp.purchase_affected_scopes
    ));
    PERFORM set_config('financee.inventory_engine','allowed',true);
    FOR v_scope IN SELECT * FROM pg_temp.purchase_affected_scopes
    LOOP
        DELETE FROM fifo_allocations fa USING stock_movements sm
         WHERE fa.outbound_movement_id=sm.movement_id
           AND sm.variant_id=v_scope.variant_id
           AND sm.warehouse_id=v_scope.warehouse_id;
        DELETE FROM fifo_layers
         WHERE variant_id=v_scope.variant_id
           AND warehouse_id=v_scope.warehouse_id;
    END LOOP;
    DELETE FROM purchase_lines WHERE purchase_invoice_id=p_purchase_invoice_id;
    DELETE FROM stock_movements
     WHERE source_type='purchase' AND source_id=p_purchase_invoice_id;
    PERFORM set_config('financee.inventory_engine','',true);
END;
$$;

CREATE OR REPLACE FUNCTION quantity_update_purchase(
    p_purchase_invoice_id bigint,data jsonb
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    v_old purchase_invoices%ROWTYPE;
    v_date date; v_vendor varchar; v_type varchar; v_account varchar;
    v_description text; v_user integer; v_lines jsonb;
    v_total numeric(24,6); v_old_journal bigint; v_journal bigint;
    v_pairs jsonb; v_fingerprint varchar; v_scope record;
BEGIN
    SELECT * INTO v_old FROM purchase_invoices
     WHERE purchase_invoice_id=p_purchase_invoice_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Purchase not found.'
            USING ERRCODE='foreign_key_violation';
    END IF;
    IF v_old.status<>'posted' THEN
        RAISE EXCEPTION 'Only posted purchases can be edited.'
            USING ERRCODE='check_violation';
    END IF;
    SELECT * INTO v_date,v_vendor,v_type,v_account,v_description,v_user,v_lines
      FROM quantity_purchase_validate_header(data);
    BEGIN
        SELECT jsonb_agg(jsonb_build_object(
                   'variant_id',(value->>'variant_id')::bigint,
                   'warehouse_id',(value->>'warehouse_id')::bigint
               )) INTO v_pairs FROM jsonb_array_elements(v_lines);
    EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
        RAISE EXCEPTION 'Every purchase line requires SKU and warehouse.'
            USING ERRCODE='check_violation';
    END;
    PERFORM quantity_lock_inventory_pairs(v_pairs);
    PERFORM set_config('financee.purchase_engine','allowed',true);
    INSERT INTO purchase_revisions (
        purchase_invoice_id,revision_number,previous_document,changed_by
    ) VALUES (
        p_purchase_invoice_id,v_old.revision_number,
        quantity_purchase_details(p_purchase_invoice_id),v_user
    );
    v_old_journal := v_old.journal_id;
    PERFORM quantity_purchase_teardown_lines(p_purchase_invoice_id);
    PERFORM quantity_reverse_journal(
        v_old_journal,v_date,'Superseded purchase '||v_old.document_number,v_user
    );
    v_fingerprint := quantity_purchase_normalized_fingerprint(data);
    UPDATE purchase_invoices SET
        invoice_date=v_date,vendor_name=v_vendor,purchase_type=v_type,
        payment_account_code=v_account,description=v_description,status='draft',
        revision_number=revision_number+1,subtotal_base=0,total_base=0,
        journal_id=NULL,request_fingerprint=v_fingerprint,
        updated_by=v_user,updated_at=CURRENT_TIMESTAMP
     WHERE purchase_invoice_id=p_purchase_invoice_id;
    v_total := quantity_purchase_post_lines(
        p_purchase_invoice_id,v_lines,v_user
    );
    -- Revalidate old scopes that were removed from the edited document. New or
    -- retained scopes were already replayed by their new movement postings.
    FOR v_scope IN SELECT * FROM pg_temp.purchase_affected_scopes
    LOOP
        PERFORM quantity_replay_inventory(
            v_scope.variant_id,v_scope.warehouse_id
        );
    END LOOP;
    UPDATE purchase_invoices SET subtotal_base=v_total,total_base=v_total
     WHERE purchase_invoice_id=p_purchase_invoice_id;
    v_journal := quantity_purchase_post_journal(
        p_purchase_invoice_id,v_user,true
    );
    UPDATE purchase_invoices SET status='posted',journal_id=v_journal
     WHERE purchase_invoice_id=p_purchase_invoice_id;
    PERFORM set_config('financee.purchase_engine','',true);
    RETURN jsonb_build_object(
        'status','success','purchase_invoice_id',p_purchase_invoice_id,
        'document_number',v_old.document_number,
        'revision_number',v_old.revision_number+1,
        'journal_id',v_journal,'total_base',v_total
    );
END;
$$;

CREATE OR REPLACE FUNCTION quantity_reverse_purchase(
    p_purchase_invoice_id bigint,p_reversal_date date,p_user_id integer
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    v_invoice purchase_invoices%ROWTYPE;
    v_line purchase_lines%ROWTYPE;
    v_layer fifo_layers%ROWTYPE;
    v_result jsonb; v_journal bigint;
BEGIN
    SELECT * INTO v_invoice FROM purchase_invoices
     WHERE purchase_invoice_id=p_purchase_invoice_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Purchase not found.'
            USING ERRCODE='foreign_key_violation';
    END IF;
    IF v_invoice.status<>'posted' THEN
        RAISE EXCEPTION 'Purchase is already reversed.'
            USING ERRCODE='check_violation';
    END IF;
    IF p_reversal_date IS NULL OR p_reversal_date<v_invoice.invoice_date THEN
        RAISE EXCEPTION 'Reversal date cannot precede purchase date.'
            USING ERRCODE='check_violation';
    END IF;
    PERFORM quantity_lock_inventory_pairs((
        SELECT jsonb_agg(jsonb_build_object(
            'variant_id',variant_id,'warehouse_id',warehouse_id
        )) FROM purchase_lines WHERE purchase_invoice_id=p_purchase_invoice_id
    ));
    FOR v_line IN SELECT * FROM purchase_lines
        WHERE purchase_invoice_id=p_purchase_invoice_id ORDER BY line_number
    LOOP
        SELECT * INTO v_layer FROM fifo_layers
         WHERE inbound_movement_id=v_line.movement_id FOR UPDATE;
        IF NOT FOUND OR v_layer.remaining_quantity<>v_layer.original_quantity THEN
            RAISE EXCEPTION
                'Purchase cannot be reversed after its stock was consumed.'
                USING ERRCODE='check_violation';
        END IF;
    END LOOP;
    FOR v_line IN SELECT * FROM purchase_lines
        WHERE purchase_invoice_id=p_purchase_invoice_id ORDER BY line_number
    LOOP
        v_result := quantity_reverse_stock_movement(
            v_line.movement_id,p_reversal_date,
            p_purchase_invoice_id*1000000+v_line.line_number,p_user_id
        );
    END LOOP;
    v_journal := quantity_reverse_journal(
        v_invoice.journal_id,p_reversal_date,
        'Reverse purchase '||v_invoice.document_number,p_user_id
    );
    PERFORM set_config('financee.purchase_engine','allowed',true);
    UPDATE purchase_invoices SET status='reversed',reversal_journal_id=v_journal,
        reversed_by=p_user_id,reversed_at=CURRENT_TIMESTAMP,
        updated_by=p_user_id,updated_at=CURRENT_TIMESTAMP
     WHERE purchase_invoice_id=p_purchase_invoice_id;
    PERFORM set_config('financee.purchase_engine','',true);
    RETURN jsonb_build_object(
        'status','success','purchase_invoice_id',p_purchase_invoice_id,
        'document_number',v_invoice.document_number,
        'reversal_journal_id',v_journal
    );
END;
$$;

CREATE OR REPLACE FUNCTION quantity_purchase_navigate(
    p_action text,p_current_id bigint DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE v_id bigint;
BEGIN
    CASE lower(COALESCE(p_action,'last'))
      WHEN 'current' THEN v_id:=p_current_id;
      WHEN 'previous' THEN
        SELECT max(purchase_invoice_id) INTO v_id FROM purchase_invoices
         WHERE purchase_invoice_id<p_current_id;
      WHEN 'next' THEN
        SELECT min(purchase_invoice_id) INTO v_id FROM purchase_invoices
         WHERE purchase_invoice_id>p_current_id;
      WHEN 'first' THEN
        SELECT min(purchase_invoice_id) INTO v_id FROM purchase_invoices;
      WHEN 'last' THEN
        SELECT max(purchase_invoice_id) INTO v_id FROM purchase_invoices;
      ELSE RAISE EXCEPTION 'Unknown navigation action.'
        USING ERRCODE='check_violation';
    END CASE;
    RETURN quantity_purchase_details(v_id);
END;
$$;

CREATE OR REPLACE FUNCTION quantity_purchase_summary(
    p_from date DEFAULT NULL,p_to date DEFAULT NULL
) RETURNS jsonb LANGUAGE sql STABLE AS $$
    SELECT jsonb_build_object(
        'from_date',p_from,'to_date',p_to,
        'invoice_count',count(*)::integer,
        'posted_count',count(*) FILTER (WHERE status='posted')::integer,
        'reversed_count',count(*) FILTER (WHERE status='reversed')::integer,
        'credit_total_base',COALESCE(sum(total_base) FILTER (
            WHERE status='posted' AND purchase_type='credit'
        ),0),
        'cash_total_base',COALESCE(sum(total_base) FILTER (
            WHERE status='posted' AND purchase_type='cash'
        ),0),
        'total_base',COALESCE(sum(total_base) FILTER (WHERE status='posted'),0),
        'documents',COALESCE(jsonb_agg(jsonb_build_object(
            'purchase_invoice_id',purchase_invoice_id,
            'document_number',document_number,'invoice_date',invoice_date,
            'vendor_name',vendor_name,'purchase_type',purchase_type,
            'status',status,'total_base',total_base,'revision_number',revision_number
        ) ORDER BY purchase_invoice_id DESC),'[]'::jsonb)
    )
      FROM purchase_invoices
     WHERE (p_from IS NULL OR invoice_date>=p_from)
       AND (p_to IS NULL OR invoice_date<=p_to);
$$;

INSERT INTO quantity_seed_registry(seed_key,seed_version,payload)
VALUES (
    'quantity.purchases',1,
    '{"scope":"domestic_base_currency","credit_account":"2000","cash_accounts":["1000","1100"],"tax":false,"attachments":"deferred"}'::jsonb
)
ON CONFLICT(seed_key) DO UPDATE SET
    seed_version=GREATEST(quantity_seed_registry.seed_version,EXCLUDED.seed_version),
    payload=EXCLUDED.payload,applied_at=CURRENT_TIMESTAMP;

UPDATE tenant_schema_metadata SET version=GREATEST(version,7),
    applied_at=CURRENT_TIMESTAMP
 WHERE id=true AND family='quantity';
