-- Idempotent Phase 6 accounting foundation for QUANTITY schemas, version 2.
DO $$
BEGIN
    IF to_regclass('tenant_schema_metadata') IS NULL
       OR NOT EXISTS (
           SELECT 1 FROM tenant_schema_metadata
            WHERE id = true AND family = 'quantity' AND version >= 1
       ) THEN
        RAISE EXCEPTION 'Quantity accounting rollout refused: family/version mismatch.';
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS chart_of_accounts (
    account_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code varchar(20) NOT NULL UNIQUE,
    account_name varchar(150) NOT NULL UNIQUE,
    account_type varchar(20) NOT NULL,
    normal_balance varchar(6) NOT NULL,
    is_system boolean NOT NULL DEFAULT true,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chart_of_accounts_code_format CHECK (
        account_code ~ '^[A-Z0-9][A-Z0-9.-]{0,19}$'
    ),
    CONSTRAINT chart_of_accounts_type_check CHECK (
        account_type IN ('Asset', 'Liability', 'Equity', 'Revenue', 'Expense')
    ),
    CONSTRAINT chart_of_accounts_normal_balance_check CHECK (
        normal_balance IN ('Debit', 'Credit')
    ),
    CONSTRAINT chart_of_accounts_type_balance_check CHECK (
        (account_type IN ('Asset', 'Expense') AND normal_balance = 'Debit')
        OR (account_type IN ('Liability', 'Equity', 'Revenue')
            AND normal_balance = 'Credit')
    )
);

INSERT INTO chart_of_accounts (
    account_code, account_name, account_type, normal_balance
) VALUES
    ('1000', 'Cash', 'Asset', 'Debit'),
    ('1100', 'Bank', 'Asset', 'Debit'),
    ('1200', 'Accounts Receivable', 'Asset', 'Debit'),
    ('1300', 'Input Tax', 'Asset', 'Debit'),
    ('1400', 'Inventory', 'Asset', 'Debit'),
    ('1990', 'Exchange Loss', 'Expense', 'Debit'),
    ('2000', 'Accounts Payable', 'Liability', 'Credit'),
    ('2100', 'Output Tax', 'Liability', 'Credit'),
    ('3000', 'Owner''s Capital', 'Equity', 'Credit'),
    ('3001', 'Opening Balance', 'Equity', 'Credit'),
    ('3002', 'Retained Earnings', 'Equity', 'Credit'),
    ('4000', 'Sales Revenue', 'Revenue', 'Credit'),
    ('4900', 'Inventory Adjustment Gain', 'Revenue', 'Credit'),
    ('4910', 'Exchange Gain', 'Revenue', 'Credit'),
    ('5000', 'Cost of Goods Sold', 'Expense', 'Debit'),
    ('5900', 'Inventory Adjustment Loss', 'Expense', 'Debit'),
    ('5990', 'Rounding Difference', 'Expense', 'Debit')
ON CONFLICT (account_code) DO UPDATE
SET account_name = EXCLUDED.account_name,
    account_type = EXCLUDED.account_type,
    normal_balance = EXCLUDED.normal_balance,
    is_system = true;

CREATE TABLE IF NOT EXISTS journal_entries (
    journal_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_date date NOT NULL,
    description text NOT NULL,
    source_document_type varchar(32) NOT NULL,
    source_document_id bigint,
    source_document_number varchar(32),
    status varchar(10) NOT NULL DEFAULT 'posted',
    original_journal_id bigint REFERENCES journal_entries(journal_id),
    reversal_journal_id bigint REFERENCES journal_entries(journal_id),
    created_by integer,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reversed_at timestamptz,
    CONSTRAINT journal_entries_description_check CHECK (btrim(description) <> ''),
    CONSTRAINT journal_entries_source_type_check CHECK (
        source_document_type ~ '^[a-z][a-z0-9_]{1,31}$'
    ),
    CONSTRAINT journal_entries_status_check CHECK (
        status IN ('posted', 'reversed')
    ),
    CONSTRAINT journal_entries_reversal_shape_check CHECK (
        (original_journal_id IS NULL AND status IN ('posted', 'reversed'))
        OR (original_journal_id IS NOT NULL AND status = 'posted')
    ),
    CONSTRAINT journal_entries_not_self_original CHECK (
        original_journal_id IS NULL OR original_journal_id <> journal_id
    ),
    CONSTRAINT journal_entries_not_self_reversal CHECK (
        reversal_journal_id IS NULL OR reversal_journal_id <> journal_id
    ),
    CONSTRAINT journal_entries_one_reversal UNIQUE (original_journal_id)
);

CREATE TABLE IF NOT EXISTS journal_lines (
    line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id bigint NOT NULL REFERENCES journal_entries(journal_id),
    account_id bigint NOT NULL REFERENCES chart_of_accounts(account_id),
    party_id bigint,
    description text,
    debit numeric(24,4) NOT NULL DEFAULT 0,
    credit numeric(24,4) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT journal_lines_non_negative CHECK (debit >= 0 AND credit >= 0),
    CONSTRAINT journal_lines_one_side_positive CHECK (
        (debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)
    )
);

CREATE INDEX IF NOT EXISTS journal_lines_journal_idx ON journal_lines(journal_id);
CREATE INDEX IF NOT EXISTS journal_lines_account_idx ON journal_lines(account_id);
CREATE INDEX IF NOT EXISTS journal_entries_date_idx
    ON journal_entries(entry_date, journal_id);
CREATE UNIQUE INDEX IF NOT EXISTS journal_entries_source_unique
    ON journal_entries(source_document_type, source_document_id)
    WHERE source_document_id IS NOT NULL AND original_journal_id IS NULL;

CREATE OR REPLACE FUNCTION quantity_assert_journal_balanced()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    target_id bigint := COALESCE(NEW.journal_id, OLD.journal_id);
    line_count integer;
    total_debit numeric(24,4);
    total_credit numeric(24,4);
BEGIN
    IF NOT EXISTS (SELECT 1 FROM journal_entries WHERE journal_id = target_id) THEN
        RAISE EXCEPTION 'Posted journals cannot be deleted.';
    END IF;
    SELECT count(*), COALESCE(sum(debit), 0), COALESCE(sum(credit), 0)
      INTO line_count, total_debit, total_credit
      FROM journal_lines WHERE journal_id = target_id;
    IF line_count < 2 THEN
        RAISE EXCEPTION 'A posted journal requires at least two lines.'
            USING ERRCODE = 'check_violation';
    END IF;
    IF total_debit <> total_credit OR total_debit <= 0 THEN
        RAISE EXCEPTION 'Journal is empty or unbalanced.'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS journal_entries_balanced ON journal_entries;
CREATE CONSTRAINT TRIGGER journal_entries_balanced
AFTER INSERT OR UPDATE ON journal_entries
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION quantity_assert_journal_balanced();
DROP TRIGGER IF EXISTS journal_lines_balanced ON journal_lines;
CREATE CONSTRAINT TRIGGER journal_lines_balanced
AFTER INSERT OR UPDATE OR DELETE ON journal_lines
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION quantity_assert_journal_balanced();

CREATE OR REPLACE FUNCTION quantity_protect_posted_journal()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF current_setting('financee.journal_reversal', true) = 'allowed' THEN
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' OR ROW(NEW.*) IS DISTINCT FROM ROW(OLD.*) THEN
        RAISE EXCEPTION 'Posted journals are immutable; create a reversal.';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS journal_entries_immutable ON journal_entries;
CREATE TRIGGER journal_entries_immutable
BEFORE UPDATE OR DELETE ON journal_entries
FOR EACH ROW EXECUTE FUNCTION quantity_protect_posted_journal();
DROP TRIGGER IF EXISTS journal_lines_immutable ON journal_lines;
CREATE TRIGGER journal_lines_immutable
BEFORE UPDATE OR DELETE ON journal_lines
FOR EACH ROW EXECUTE FUNCTION quantity_protect_posted_journal();

CREATE OR REPLACE VIEW quantity_trial_balance AS
SELECT coa.account_id, coa.account_code, coa.account_name, coa.account_type,
       coa.normal_balance,
       COALESCE(sum(jl.debit), 0)::numeric(24,4) AS total_debit,
       COALESCE(sum(jl.credit), 0)::numeric(24,4) AS total_credit,
       (COALESCE(sum(jl.debit), 0) - COALESCE(sum(jl.credit), 0))::numeric(24,4)
           AS balance
  FROM chart_of_accounts coa
  LEFT JOIN journal_lines jl ON jl.account_id = coa.account_id
 GROUP BY coa.account_id, coa.account_code, coa.account_name,
          coa.account_type, coa.normal_balance;

CREATE OR REPLACE FUNCTION quantity_account_lookup(search_text text DEFAULT NULL)
RETURNS TABLE (
    account_id bigint, account_code varchar, account_name varchar,
    account_type varchar, normal_balance varchar
) LANGUAGE sql STABLE AS $$
    SELECT c.account_id, c.account_code, c.account_name,
           c.account_type, c.normal_balance
      FROM chart_of_accounts c
     WHERE c.is_active
       AND (search_text IS NULL OR btrim(search_text) = ''
            OR c.account_code ILIKE '%' || search_text || '%'
            OR c.account_name ILIKE '%' || search_text || '%')
     ORDER BY c.account_code;
$$;

CREATE OR REPLACE FUNCTION quantity_next_document_number(p_document_type text)
RETURNS text LANGUAGE plpgsql AS $$
DECLARE
    selected_prefix varchar(8);
    selected_number bigint;
BEGIN
    UPDATE document_sequences
       SET next_number = next_number + 1, updated_at = CURRENT_TIMESTAMP
     WHERE document_type = p_document_type
     RETURNING prefix, next_number - 1 INTO selected_prefix, selected_number;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Unknown document type.'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    RETURN selected_prefix || '-' || lpad(selected_number::text, 6, '0');
END;
$$;

CREATE OR REPLACE FUNCTION quantity_post_journal(
    p_entry_date date, p_description text, p_source_document_type text,
    p_source_document_id bigint, p_source_document_number text,
    p_created_by integer, p_lines jsonb
) RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
    new_journal_id bigint;
    line jsonb;
    line_account_id bigint;
    line_debit numeric(24,4);
    line_credit numeric(24,4);
    total_debit numeric(24,4) := 0;
    total_credit numeric(24,4) := 0;
BEGIN
    IF p_entry_date IS NULL OR btrim(COALESCE(p_description, '')) = '' THEN
        RAISE EXCEPTION 'Journal date and description are required.'
            USING ERRCODE = 'not_null_violation';
    END IF;
    IF p_source_document_type IS NULL
       OR p_source_document_type !~ '^[a-z][a-z0-9_]{1,31}$' THEN
        RAISE EXCEPTION 'Invalid source document type.'
            USING ERRCODE = 'check_violation';
    END IF;
    IF p_lines IS NULL OR jsonb_typeof(p_lines) <> 'array'
       OR jsonb_array_length(p_lines) < 2 THEN
        RAISE EXCEPTION 'A posted journal requires at least two lines.'
            USING ERRCODE = 'check_violation';
    END IF;
    INSERT INTO journal_entries (
        entry_date, description, source_document_type, source_document_id,
        source_document_number, created_by
    ) VALUES (
        p_entry_date, btrim(p_description), p_source_document_type,
        p_source_document_id, p_source_document_number, p_created_by
    ) RETURNING journal_id INTO new_journal_id;
    FOR line IN SELECT value FROM jsonb_array_elements(p_lines)
    LOOP
        IF jsonb_typeof(line) <> 'object' THEN
            RAISE EXCEPTION 'Every journal line must be an object.'
                USING ERRCODE = 'check_violation';
        END IF;
        SELECT account_id INTO line_account_id FROM chart_of_accounts
         WHERE account_code = line->>'account_code' AND is_active;
        IF line_account_id IS NULL THEN
            RAISE EXCEPTION 'Unknown or inactive account.'
                USING ERRCODE = 'foreign_key_violation';
        END IF;
        BEGIN
            line_debit := COALESCE((line->>'debit')::numeric, 0);
            line_credit := COALESCE((line->>'credit')::numeric, 0);
        EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
            RAISE EXCEPTION 'Invalid journal amount.'
                USING ERRCODE = 'check_violation';
        END;
        IF NOT ((line_debit > 0 AND line_credit = 0)
                OR (line_credit > 0 AND line_debit = 0)) THEN
            RAISE EXCEPTION 'Exactly one debit or credit must be positive.'
                USING ERRCODE = 'check_violation';
        END IF;
        INSERT INTO journal_lines (
            journal_id, account_id, party_id, description, debit, credit
        ) VALUES (
            new_journal_id, line_account_id, (line->>'party_id')::bigint,
            NULLIF(btrim(line->>'description'), ''), line_debit, line_credit
        );
        total_debit := total_debit + line_debit;
        total_credit := total_credit + line_credit;
    END LOOP;
    IF total_debit <> total_credit OR total_debit <= 0 THEN
        RAISE EXCEPTION 'Journal is empty or unbalanced.'
            USING ERRCODE = 'check_violation';
    END IF;
    SET CONSTRAINTS journal_entries_balanced, journal_lines_balanced IMMEDIATE;
    SET CONSTRAINTS journal_entries_balanced, journal_lines_balanced DEFERRED;
    RETURN new_journal_id;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_reverse_journal(
    p_journal_id bigint, p_reversal_date date, p_description text,
    p_created_by integer
) RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
    original journal_entries%ROWTYPE;
    new_journal_id bigint;
    reversal_lines jsonb;
BEGIN
    SELECT * INTO original FROM journal_entries
     WHERE journal_id = p_journal_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Journal not found.'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    IF original.status <> 'posted' OR original.original_journal_id IS NOT NULL
       OR original.reversal_journal_id IS NOT NULL THEN
        RAISE EXCEPTION 'Journal is already reversed or is a reversal.'
            USING ERRCODE = 'check_violation';
    END IF;
    SELECT jsonb_agg(jsonb_build_object(
               'account_code', coa.account_code, 'party_id', jl.party_id,
               'description', jl.description, 'debit', jl.credit,
               'credit', jl.debit
           ) ORDER BY jl.line_id)
      INTO reversal_lines
      FROM journal_lines jl
      JOIN chart_of_accounts coa ON coa.account_id = jl.account_id
     WHERE jl.journal_id = p_journal_id;
    new_journal_id := quantity_post_journal(
        p_reversal_date,
        COALESCE(NULLIF(btrim(p_description), ''), 'Reversal: ' || original.description),
        'journal_reversal', NULL, original.source_document_number,
        p_created_by, reversal_lines
    );
    PERFORM set_config('financee.journal_reversal', 'allowed', true);
    UPDATE journal_entries SET original_journal_id = p_journal_id
     WHERE journal_id = new_journal_id;
    UPDATE journal_entries
       SET status = 'reversed', reversal_journal_id = new_journal_id,
           reversed_at = CURRENT_TIMESTAMP
     WHERE journal_id = p_journal_id;
    PERFORM set_config('financee.journal_reversal', '', true);
    RETURN new_journal_id;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_schema_fingerprint()
RETURNS jsonb LANGUAGE sql STABLE AS $$
    SELECT jsonb_build_object(
        'family', family,
        'version', version,
        'base_currency_code', base_currency_code,
        'foundation_tables', ARRAY[
            'chart_of_accounts', 'document_sequences', 'journal_entries',
            'journal_lines', 'quantity_seed_registry', 'tenant_schema_metadata'
        ],
        'foundation_sequences', ARRAY[
            'chart_of_accounts_account_id_seq',
            'journal_entries_journal_id_seq',
            'journal_lines_line_id_seq',
            'quantity_foundation_id_seq'
        ]
    )
    FROM tenant_schema_metadata WHERE id = true;
$$;

INSERT INTO quantity_seed_registry (seed_key, seed_version, payload)
VALUES (
    'quantity.accounting', 1,
    '{"chart_accounts": 17, "ledger_precision": "numeric(24,4)"}'::jsonb
)
ON CONFLICT (seed_key) DO UPDATE
SET seed_version = GREATEST(
        quantity_seed_registry.seed_version, EXCLUDED.seed_version
    ),
    payload = EXCLUDED.payload,
    applied_at = CURRENT_TIMESTAMP;

UPDATE tenant_schema_metadata
   SET version = GREATEST(version, 2), applied_at = CURRENT_TIMESTAMP
 WHERE id = true AND family = 'quantity';
