-- Idempotent Phase 8 warehouse foundation for QUANTITY schemas, version 4.
DO $$
BEGIN
    IF to_regclass('tenant_schema_metadata') IS NULL
       OR NOT EXISTS (
           SELECT 1 FROM tenant_schema_metadata
            WHERE id = true AND family = 'quantity' AND version >= 3
       ) THEN
        RAISE EXCEPTION 'Quantity warehouse rollout refused: family/version mismatch.';
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS warehouses (
    warehouse_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code varchar(20) NOT NULL,
    warehouse_name varchar(120) NOT NULL,
    address text,
    is_default boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_by integer,
    updated_by integer,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    normalized_code text GENERATED ALWAYS AS (
        upper(regexp_replace(btrim(warehouse_code), '\s+', '', 'g'))
    ) STORED,
    normalized_name text GENERATED ALWAYS AS (
        lower(regexp_replace(btrim(warehouse_name), '\s+', ' ', 'g'))
    ) STORED,
    CONSTRAINT warehouses_code_check CHECK (
        btrim(warehouse_code) <> ''
        AND warehouse_code ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$'
    ),
    CONSTRAINT warehouses_name_check CHECK (btrim(warehouse_name) <> ''),
    CONSTRAINT warehouses_default_active_check CHECK (
        NOT is_default OR is_active
    ),
    CONSTRAINT warehouses_code_unique UNIQUE (normalized_code),
    CONSTRAINT warehouses_name_unique UNIQUE (normalized_name)
);

CREATE UNIQUE INDEX IF NOT EXISTS warehouses_one_active_default
    ON warehouses (is_default)
    WHERE is_default AND is_active;

CREATE TABLE IF NOT EXISTS warehouse_reference_registry (
    reference_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id bigint NOT NULL REFERENCES warehouses(warehouse_id)
        ON DELETE RESTRICT,
    source_type varchar(32) NOT NULL,
    source_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT warehouse_reference_source_check CHECK (
        source_type ~ '^[a-z][a-z0-9_]{1,31}$'
    ),
    CONSTRAINT warehouse_reference_unique UNIQUE (
        warehouse_id, source_type, source_id
    )
);

CREATE INDEX IF NOT EXISTS warehouse_reference_warehouse_idx
    ON warehouse_reference_registry(warehouse_id);

CREATE OR REPLACE FUNCTION quantity_create_warehouse(payload jsonb)
RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
    new_id bigint;
    requested_active boolean := COALESCE(
        (payload->>'is_active')::boolean, true
    );
    requested_default boolean := COALESCE(
        (payload->>'is_default')::boolean, false
    );
BEGIN
    PERFORM pg_advisory_xact_lock(hashtextextended('quantity.warehouse.default', 7308));
    IF requested_active
       AND NOT EXISTS (SELECT 1 FROM warehouses WHERE is_active AND is_default) THEN
        requested_default := true;
    END IF;
    IF requested_default AND NOT requested_active THEN
        RAISE EXCEPTION 'An inactive warehouse cannot be default.'
            USING ERRCODE = 'check_violation';
    END IF;
    IF requested_default THEN
        UPDATE warehouses
           SET is_default = false, updated_at = CURRENT_TIMESTAMP
         WHERE is_default;
    END IF;
    INSERT INTO warehouses (
        warehouse_code, warehouse_name, address, is_default, is_active,
        created_by, updated_by
    ) VALUES (
        btrim(payload->>'warehouse_code'),
        btrim(payload->>'warehouse_name'),
        NULLIF(btrim(payload->>'address'), ''),
        requested_default,
        requested_active,
        (payload->>'user_id')::integer,
        (payload->>'user_id')::integer
    ) RETURNING warehouse_id INTO new_id;
    RETURN new_id;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_update_warehouse(
    p_warehouse_id bigint, payload jsonb
) RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
    current_row warehouses%ROWTYPE;
    requested_active boolean;
    requested_default boolean;
    replacement_id bigint;
BEGIN
    PERFORM pg_advisory_xact_lock(hashtextextended('quantity.warehouse.default', 7308));
    SELECT * INTO current_row FROM warehouses
     WHERE warehouse_id = p_warehouse_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Warehouse not found.'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    requested_active := COALESCE(
        (payload->>'is_active')::boolean, current_row.is_active
    );
    requested_default := COALESCE(
        (payload->>'is_default')::boolean, current_row.is_default
    );
    IF requested_default AND NOT requested_active AND NOT current_row.is_default THEN
        RAISE EXCEPTION 'An inactive warehouse cannot be default.'
            USING ERRCODE = 'check_violation';
    END IF;
    IF requested_default THEN
        UPDATE warehouses SET is_default = false, updated_at = CURRENT_TIMESTAMP
         WHERE is_default AND warehouse_id <> p_warehouse_id;
    END IF;
    IF current_row.is_default AND NOT requested_active THEN
        requested_default := false;
        UPDATE warehouses
           SET is_default = false, updated_at = CURRENT_TIMESTAMP
         WHERE warehouse_id = p_warehouse_id;
        SELECT warehouse_id INTO replacement_id
          FROM warehouses
         WHERE warehouse_id <> p_warehouse_id AND is_active
         ORDER BY warehouse_id LIMIT 1 FOR UPDATE;
        IF replacement_id IS NOT NULL THEN
            UPDATE warehouses
               SET is_default = true, updated_at = CURRENT_TIMESTAMP
             WHERE warehouse_id = replacement_id;
        END IF;
    END IF;
    UPDATE warehouses
       SET warehouse_code = COALESCE(
               NULLIF(btrim(payload->>'warehouse_code'), ''), warehouse_code
           ),
           warehouse_name = COALESCE(
               NULLIF(btrim(payload->>'warehouse_name'), ''), warehouse_name
           ),
           address = CASE
               WHEN payload ? 'address'
               THEN NULLIF(btrim(payload->>'address'), '')
               ELSE address
           END,
           is_default = requested_default,
           is_active = requested_active,
           updated_by = COALESCE((payload->>'user_id')::integer, updated_by),
           updated_at = CURRENT_TIMESTAMP
     WHERE warehouse_id = p_warehouse_id;
    RETURN p_warehouse_id;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_delete_warehouse(p_warehouse_id bigint)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    was_default boolean;
    replacement_id bigint;
BEGIN
    PERFORM pg_advisory_xact_lock(hashtextextended('quantity.warehouse.default', 7308));
    SELECT is_default INTO was_default FROM warehouses
     WHERE warehouse_id = p_warehouse_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Warehouse not found.'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    IF EXISTS (
        SELECT 1 FROM warehouse_reference_registry
         WHERE warehouse_id = p_warehouse_id
    ) THEN
        RAISE EXCEPTION 'Referenced warehouses cannot be deleted.'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    DELETE FROM warehouses WHERE warehouse_id = p_warehouse_id;
    IF was_default THEN
        SELECT warehouse_id INTO replacement_id FROM warehouses
         WHERE is_active ORDER BY warehouse_id LIMIT 1 FOR UPDATE;
        IF replacement_id IS NOT NULL THEN
            UPDATE warehouses SET is_default = true,
                                  updated_at = CURRENT_TIMESTAMP
             WHERE warehouse_id = replacement_id;
        END IF;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_warehouse_lookup(
    search_text text DEFAULT NULL, active_only boolean DEFAULT true
) RETURNS TABLE (
    warehouse_id bigint, warehouse_code varchar, warehouse_name varchar,
    address text, is_default boolean, is_active boolean
) LANGUAGE sql STABLE AS $$
    SELECT w.warehouse_id, w.warehouse_code, w.warehouse_name, w.address,
           w.is_default, w.is_active
      FROM warehouses w
     WHERE (NOT active_only OR w.is_active)
       AND (search_text IS NULL OR btrim(search_text) = ''
            OR w.warehouse_code ILIKE '%' || search_text || '%'
            OR w.warehouse_name ILIKE '%' || search_text || '%'
            OR COALESCE(w.address, '') ILIKE '%' || search_text || '%')
     ORDER BY w.is_default DESC, w.warehouse_name, w.warehouse_id;
$$;

CREATE OR REPLACE FUNCTION quantity_default_warehouse()
RETURNS bigint LANGUAGE sql STABLE AS $$
    SELECT warehouse_id FROM warehouses
     WHERE is_active AND is_default
     ORDER BY warehouse_id LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION quantity_schema_fingerprint()
RETURNS jsonb LANGUAGE sql STABLE AS $$
    SELECT jsonb_build_object(
        'family', family, 'version', version,
        'base_currency_code', base_currency_code,
        'foundation_tables', ARRAY[
            'chart_of_accounts', 'document_sequences', 'journal_entries',
            'journal_lines', 'product_variants', 'products',
            'quantity_seed_registry', 'tenant_schema_metadata',
            'units_of_measure', 'variant_transaction_registry',
            'warehouse_reference_registry', 'warehouses'
        ],
        'foundation_sequences', ARRAY[
            'chart_of_accounts_account_id_seq',
            'journal_entries_journal_id_seq',
            'journal_lines_line_id_seq',
            'product_variants_variant_id_seq', 'products_product_id_seq',
            'quantity_foundation_id_seq', 'units_of_measure_unit_id_seq',
            'variant_transaction_registry_reference_id_seq',
            'warehouse_reference_registry_reference_id_seq',
            'warehouses_warehouse_id_seq'
        ]
    ) FROM tenant_schema_metadata WHERE id = true;
$$;

INSERT INTO quantity_seed_registry (seed_key, seed_version, payload)
VALUES (
    'quantity.warehouse', 1,
    '{"multiple": true, "single_active_default": true}'::jsonb
)
ON CONFLICT (seed_key) DO UPDATE
SET seed_version = GREATEST(
        quantity_seed_registry.seed_version, EXCLUDED.seed_version
    ),
    payload = EXCLUDED.payload,
    applied_at = CURRENT_TIMESTAMP;

UPDATE tenant_schema_metadata
   SET version = GREATEST(version, 4), applied_at = CURRENT_TIMESTAMP
 WHERE id = true AND family = 'quantity';
