-- Idempotent Phase 9 movement/FIFO engine for QUANTITY schemas, version 5.
DO $$
BEGIN
    IF to_regclass('tenant_schema_metadata') IS NULL
       OR NOT EXISTS (
           SELECT 1 FROM tenant_schema_metadata
            WHERE id = true AND family = 'quantity' AND version >= 4
       ) THEN
        RAISE EXCEPTION 'Quantity FIFO rollout refused: family/version mismatch.';
    END IF;
END;
$$;

CREATE SEQUENCE IF NOT EXISTS inventory_effective_sequence_seq AS bigint;

CREATE TABLE IF NOT EXISTS stock_movements (
    movement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id bigint NOT NULL REFERENCES product_variants(variant_id),
    warehouse_id bigint NOT NULL REFERENCES warehouses(warehouse_id),
    movement_date date NOT NULL,
    effective_sequence bigint NOT NULL
        DEFAULT nextval('inventory_effective_sequence_seq'),
    movement_type varchar(24) NOT NULL,
    quantity_in numeric NOT NULL DEFAULT 0,
    quantity_out numeric NOT NULL DEFAULT 0,
    source_type varchar(32) NOT NULL,
    source_id bigint NOT NULL,
    source_line_id bigint NOT NULL,
    document_number varchar(32),
    unit_cost_base numeric(20,6),
    total_cost_base numeric(24,6),
    description text,
    created_by integer,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reversal_of_movement_id bigint REFERENCES stock_movements(movement_id),
    CONSTRAINT stock_movements_direction_check CHECK (
        (quantity_in > 0 AND quantity_out = 0)
        OR (quantity_out > 0 AND quantity_in = 0)
    ),
    CONSTRAINT stock_movements_three_decimal_check CHECK (
        quantity_in = round(quantity_in, 3)
        AND quantity_out = round(quantity_out, 3)
        AND quantity_in < 1000000000000000::numeric
        AND quantity_out < 1000000000000000::numeric
    ),
    CONSTRAINT stock_movements_type_check CHECK (
        movement_type IN (
            'opening', 'purchase', 'sale', 'sale_return',
            'purchase_return', 'transfer_out', 'transfer_in',
            'adjustment_in', 'adjustment_out', 'reversal_in', 'reversal_out'
        )
    ),
    CONSTRAINT stock_movements_source_check CHECK (
        source_type ~ '^[a-z][a-z0-9_]{1,31}$'
    ),
    CONSTRAINT stock_movements_cost_check CHECK (
        unit_cost_base IS NULL OR unit_cost_base >= 0
    ),
    CONSTRAINT stock_movements_reversal_check CHECK (
        reversal_of_movement_id IS NULL
        OR reversal_of_movement_id <> movement_id
    ),
    CONSTRAINT stock_movements_source_unique UNIQUE (
        source_type, source_id, source_line_id, movement_type
    ),
    CONSTRAINT stock_movements_effective_unique UNIQUE (
        variant_id, warehouse_id, movement_date, effective_sequence
    ),
    CONSTRAINT stock_movements_one_reversal UNIQUE (reversal_of_movement_id)
);

CREATE INDEX IF NOT EXISTS stock_movements_scope_order_idx
    ON stock_movements(
        warehouse_id, variant_id, movement_date, effective_sequence, movement_id
    );

CREATE TABLE IF NOT EXISTS stock_balances (
    variant_id bigint NOT NULL REFERENCES product_variants(variant_id),
    warehouse_id bigint NOT NULL REFERENCES warehouses(warehouse_id),
    on_hand_quantity numeric NOT NULL DEFAULT 0,
    balance_version bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (variant_id, warehouse_id),
    CONSTRAINT stock_balances_non_negative CHECK (on_hand_quantity >= 0),
    CONSTRAINT stock_balances_precision CHECK (
        on_hand_quantity = round(on_hand_quantity, 3)
        AND on_hand_quantity < 1000000000000000::numeric
    )
);

CREATE TABLE IF NOT EXISTS fifo_layers (
    layer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inbound_movement_id bigint NOT NULL UNIQUE
        REFERENCES stock_movements(movement_id),
    variant_id bigint NOT NULL REFERENCES product_variants(variant_id),
    warehouse_id bigint NOT NULL REFERENCES warehouses(warehouse_id),
    source_type varchar(32) NOT NULL,
    source_id bigint NOT NULL,
    source_line_id bigint NOT NULL,
    source_date date NOT NULL,
    effective_sequence bigint NOT NULL,
    original_quantity numeric NOT NULL,
    remaining_quantity numeric NOT NULL,
    unit_cost_base numeric(20,6) NOT NULL,
    restored_from_allocation_id bigint,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fifo_layers_quantity_check CHECK (
        original_quantity > 0
        AND original_quantity = round(original_quantity, 3)
        AND remaining_quantity >= 0
        AND remaining_quantity <= original_quantity
        AND remaining_quantity = round(remaining_quantity, 3)
    ),
    CONSTRAINT fifo_layers_cost_check CHECK (unit_cost_base >= 0)
);

CREATE INDEX IF NOT EXISTS fifo_layers_available_idx
    ON fifo_layers(
        warehouse_id, variant_id, source_date, effective_sequence, layer_id
    ) WHERE remaining_quantity > 0;

CREATE TABLE IF NOT EXISTS fifo_allocations (
    allocation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbound_movement_id bigint NOT NULL
        REFERENCES stock_movements(movement_id),
    layer_id bigint NOT NULL REFERENCES fifo_layers(layer_id),
    quantity numeric NOT NULL,
    unit_cost_base numeric(20,6) NOT NULL,
    total_cost_base numeric(24,6) NOT NULL,
    allocation_order integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fifo_allocations_quantity_check CHECK (
        quantity > 0 AND quantity = round(quantity, 3)
    ),
    CONSTRAINT fifo_allocations_cost_check CHECK (
        unit_cost_base >= 0 AND total_cost_base >= 0
    ),
    CONSTRAINT fifo_allocations_order_check CHECK (allocation_order > 0),
    CONSTRAINT fifo_allocations_layer_unique UNIQUE (
        outbound_movement_id, layer_id
    ),
    CONSTRAINT fifo_allocations_order_unique UNIQUE (
        outbound_movement_id, allocation_order
    )
);

CREATE INDEX IF NOT EXISTS fifo_allocations_layer_idx
    ON fifo_allocations(layer_id);

CREATE OR REPLACE FUNCTION quantity_inventory_write_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF current_setting('financee.inventory_engine', true) = 'allowed' THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'Inventory history is writable only through controlled functions.'
        USING ERRCODE = 'insufficient_privilege';
END;
$$;

DROP TRIGGER IF EXISTS stock_movements_write_guard ON stock_movements;
CREATE TRIGGER stock_movements_write_guard
BEFORE INSERT OR UPDATE OR DELETE ON stock_movements
FOR EACH ROW EXECUTE FUNCTION quantity_inventory_write_guard();

DROP TRIGGER IF EXISTS fifo_layers_write_guard ON fifo_layers;
CREATE TRIGGER fifo_layers_write_guard
BEFORE INSERT OR UPDATE OR DELETE ON fifo_layers
FOR EACH ROW EXECUTE FUNCTION quantity_inventory_write_guard();

DROP TRIGGER IF EXISTS fifo_allocations_write_guard ON fifo_allocations;
CREATE TRIGGER fifo_allocations_write_guard
BEFORE INSERT OR UPDATE OR DELETE ON fifo_allocations
FOR EACH ROW EXECUTE FUNCTION quantity_inventory_write_guard();

DROP TRIGGER IF EXISTS stock_balances_write_guard ON stock_balances;
CREATE TRIGGER stock_balances_write_guard
BEFORE INSERT OR UPDATE OR DELETE ON stock_balances
FOR EACH ROW EXECUTE FUNCTION quantity_inventory_write_guard();

CREATE OR REPLACE FUNCTION quantity_inventory_scope_lock(
    p_variant_id bigint, p_warehouse_id bigint
) RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    PERFORM pg_advisory_xact_lock(
        hashtextextended(
            current_schema() || ':' || p_warehouse_id::text || ':' ||
            p_variant_id::text,
            7309
        )
    );
END;
$$;

CREATE OR REPLACE FUNCTION quantity_lock_inventory_pairs(p_pairs jsonb)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    pair record;
BEGIN
    IF p_pairs IS NULL OR jsonb_typeof(p_pairs) <> 'array' THEN
        RAISE EXCEPTION 'Inventory lock pairs must be an array.'
            USING ERRCODE = 'check_violation';
    END IF;
    FOR pair IN
        SELECT DISTINCT
               (value->>'warehouse_id')::bigint AS warehouse_id,
               (value->>'variant_id')::bigint AS variant_id
          FROM jsonb_array_elements(p_pairs)
         ORDER BY 1, 2
    LOOP
        PERFORM quantity_inventory_scope_lock(pair.variant_id, pair.warehouse_id);
    END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_replay_inventory(
    p_variant_id bigint, p_warehouse_id bigint
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    event_count integer;
    movement stock_movements%ROWTYPE;
    layer fifo_layers%ROWTYPE;
    running_quantity numeric := 0;
    needed numeric;
    take_quantity numeric;
    allocation_no integer;
    movement_cost numeric(24,6);
    closing_quantity numeric;
    fifo_quantity numeric;
    fifo_value numeric(24,6);
BEGIN
    PERFORM quantity_inventory_scope_lock(p_variant_id, p_warehouse_id);
    PERFORM set_config('financee.inventory_engine', 'allowed', true);
    INSERT INTO stock_balances (variant_id, warehouse_id)
    VALUES (p_variant_id, p_warehouse_id)
    ON CONFLICT (variant_id, warehouse_id) DO NOTHING;
    PERFORM 1 FROM stock_balances
     WHERE variant_id = p_variant_id AND warehouse_id = p_warehouse_id
     FOR UPDATE;

    SELECT count(*) INTO event_count FROM stock_movements
     WHERE variant_id = p_variant_id AND warehouse_id = p_warehouse_id;
    IF event_count > 10000 THEN
        RAISE EXCEPTION 'Inventory replay scope exceeds synchronous limit.'
            USING ERRCODE = 'program_limit_exceeded';
    END IF;

    -- Validate the complete historical timeline before mutating projections.
    FOR movement IN
        SELECT * FROM stock_movements
         WHERE variant_id = p_variant_id AND warehouse_id = p_warehouse_id
         ORDER BY movement_date, effective_sequence, movement_id
    LOOP
        running_quantity := running_quantity
                            + movement.quantity_in - movement.quantity_out;
        IF running_quantity < 0 THEN
            RAISE EXCEPTION
                'Insufficient stock: requested %, available %, variant %, warehouse %.',
                movement.quantity_out,
                running_quantity + movement.quantity_out,
                p_variant_id,
                p_warehouse_id
                USING ERRCODE = 'check_violation';
        END IF;
    END LOOP;
    closing_quantity := running_quantity;

    DELETE FROM fifo_allocations fa
     USING stock_movements sm
     WHERE fa.outbound_movement_id = sm.movement_id
       AND sm.variant_id = p_variant_id
       AND sm.warehouse_id = p_warehouse_id;

    INSERT INTO fifo_layers (
        inbound_movement_id, variant_id, warehouse_id, source_type,
        source_id, source_line_id, source_date, effective_sequence,
        original_quantity, remaining_quantity, unit_cost_base
    )
    SELECT sm.movement_id, sm.variant_id, sm.warehouse_id, sm.source_type,
           sm.source_id, sm.source_line_id, sm.movement_date,
           sm.effective_sequence, sm.quantity_in, sm.quantity_in,
           sm.unit_cost_base
      FROM stock_movements sm
     WHERE sm.variant_id = p_variant_id
       AND sm.warehouse_id = p_warehouse_id
       AND sm.quantity_in > 0
    ON CONFLICT (inbound_movement_id) DO UPDATE
    SET source_date = EXCLUDED.source_date,
        effective_sequence = EXCLUDED.effective_sequence,
        original_quantity = EXCLUDED.original_quantity,
        remaining_quantity = EXCLUDED.original_quantity,
        unit_cost_base = EXCLUDED.unit_cost_base;

    FOR movement IN
        SELECT * FROM stock_movements
         WHERE variant_id = p_variant_id AND warehouse_id = p_warehouse_id
         ORDER BY movement_date, effective_sequence, movement_id
    LOOP
        IF movement.quantity_out > 0 THEN
            needed := movement.quantity_out;
            allocation_no := 0;
            movement_cost := 0;
            FOR layer IN
                SELECT * FROM fifo_layers
                 WHERE variant_id = p_variant_id
                   AND warehouse_id = p_warehouse_id
                   AND remaining_quantity > 0
                   AND (
                       source_date < movement.movement_date
                       OR (
                           source_date = movement.movement_date
                           AND effective_sequence <= movement.effective_sequence
                       )
                   )
                 ORDER BY source_date, effective_sequence, layer_id
                 FOR UPDATE
            LOOP
                EXIT WHEN needed = 0;
                take_quantity := LEAST(needed, layer.remaining_quantity);
                allocation_no := allocation_no + 1;
                INSERT INTO fifo_allocations (
                    outbound_movement_id, layer_id, quantity, unit_cost_base,
                    total_cost_base, allocation_order
                ) VALUES (
                    movement.movement_id, layer.layer_id, take_quantity,
                    layer.unit_cost_base,
                    round(take_quantity * layer.unit_cost_base, 6),
                    allocation_no
                );
                UPDATE fifo_layers
                   SET remaining_quantity = remaining_quantity - take_quantity
                 WHERE layer_id = layer.layer_id;
                movement_cost := movement_cost
                                 + round(take_quantity * layer.unit_cost_base, 6);
                needed := needed - take_quantity;
            END LOOP;
            IF needed <> 0 THEN
                RAISE EXCEPTION 'FIFO allocation did not satisfy movement.'
                    USING ERRCODE = 'check_violation';
            END IF;
            UPDATE stock_movements
               SET total_cost_base = movement_cost,
                   unit_cost_base = round(
                       movement_cost / movement.quantity_out, 6
                   )
             WHERE movement_id = movement.movement_id;
        ELSE
            UPDATE stock_movements
               SET total_cost_base = round(quantity_in * unit_cost_base, 6)
             WHERE movement_id = movement.movement_id;
        END IF;
    END LOOP;

    SELECT COALESCE(sum(remaining_quantity), 0),
           COALESCE(sum(round(remaining_quantity * unit_cost_base, 6)), 0)
      INTO fifo_quantity, fifo_value
      FROM fifo_layers
     WHERE variant_id = p_variant_id AND warehouse_id = p_warehouse_id;
    IF fifo_quantity <> closing_quantity THEN
        RAISE EXCEPTION 'Inventory/FIFO quantity reconciliation failed.'
            USING ERRCODE = 'check_violation';
    END IF;
    UPDATE stock_balances
       SET on_hand_quantity = closing_quantity,
           balance_version = balance_version + 1,
           updated_at = CURRENT_TIMESTAMP
     WHERE variant_id = p_variant_id AND warehouse_id = p_warehouse_id;
    PERFORM set_config('financee.inventory_engine', '', true);
    RETURN jsonb_build_object(
        'variant_id', p_variant_id,
        'warehouse_id', p_warehouse_id,
        'on_hand_quantity', closing_quantity,
        'fifo_quantity', fifo_quantity,
        'fifo_value', fifo_value,
        'event_count', event_count
    );
END;
$$;

CREATE OR REPLACE FUNCTION quantity_post_stock_movement(
    p_movement_type text,
    p_variant_id bigint,
    p_warehouse_id bigint,
    p_movement_date date,
    p_quantity numeric,
    p_unit_cost_base numeric,
    p_source_type text,
    p_source_id bigint,
    p_source_line_id bigint,
    p_document_number text DEFAULT NULL,
    p_created_by integer DEFAULT NULL,
    p_description text DEFAULT NULL,
    p_effective_sequence bigint DEFAULT NULL,
    p_reversal_of_movement_id bigint DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    inbound boolean;
    v_movement_id bigint;
    existing stock_movements%ROWTYPE;
    replay_result jsonb;
BEGIN
    IF p_movement_type IN (
        'opening', 'purchase', 'sale_return', 'transfer_in',
        'adjustment_in', 'reversal_in'
    ) THEN
        inbound := true;
    ELSIF p_movement_type IN (
        'sale', 'purchase_return', 'transfer_out',
        'adjustment_out', 'reversal_out'
    ) THEN
        inbound := false;
    ELSE
        RAISE EXCEPTION 'Unknown movement type.'
            USING ERRCODE = 'check_violation';
    END IF;
    PERFORM quantity_validate_quantity(p_variant_id, p_quantity);
    IF NOT EXISTS (
        SELECT 1 FROM warehouses
         WHERE warehouse_id = p_warehouse_id AND is_active
    ) THEN
        RAISE EXCEPTION 'Unknown or inactive warehouse.'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    IF inbound AND (p_unit_cost_base IS NULL OR p_unit_cost_base < 0) THEN
        RAISE EXCEPTION 'Inbound unit cost is required and non-negative.'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NOT inbound AND p_unit_cost_base IS NOT NULL THEN
        RAISE EXCEPTION 'Outbound cost is assigned by FIFO.'
            USING ERRCODE = 'check_violation';
    END IF;
    IF p_movement_date IS NULL OR p_source_id IS NULL OR p_source_line_id IS NULL THEN
        RAISE EXCEPTION 'Movement date and source identity are required.'
            USING ERRCODE = 'not_null_violation';
    END IF;

    PERFORM quantity_inventory_scope_lock(p_variant_id, p_warehouse_id);
    SELECT * INTO existing FROM stock_movements
     WHERE source_type = p_source_type
       AND source_id = p_source_id
       AND source_line_id = p_source_line_id
       AND movement_type = p_movement_type;
    IF FOUND THEN
        IF existing.variant_id = p_variant_id
           AND existing.warehouse_id = p_warehouse_id
           AND existing.movement_date = p_movement_date
           AND (existing.quantity_in + existing.quantity_out) = p_quantity
           AND (
               NOT inbound
               OR existing.unit_cost_base = p_unit_cost_base
           ) THEN
            RETURN jsonb_build_object(
                'movement_id', existing.movement_id,
                'idempotent', true,
                'total_cost_base', existing.total_cost_base
            );
        END IF;
        RAISE EXCEPTION 'Source identity was already used with different data.'
            USING ERRCODE = 'unique_violation';
    END IF;

    PERFORM set_config('financee.inventory_engine', 'allowed', true);
    INSERT INTO stock_movements (
        variant_id, warehouse_id, movement_date, effective_sequence,
        movement_type, quantity_in, quantity_out, source_type, source_id,
        source_line_id, document_number, unit_cost_base, created_by,
        description, reversal_of_movement_id
    ) VALUES (
        p_variant_id, p_warehouse_id, p_movement_date,
        COALESCE(p_effective_sequence, nextval('inventory_effective_sequence_seq')),
        p_movement_type,
        CASE WHEN inbound THEN p_quantity ELSE 0 END,
        CASE WHEN inbound THEN 0 ELSE p_quantity END,
        p_source_type, p_source_id, p_source_line_id, p_document_number,
        CASE WHEN inbound THEN p_unit_cost_base ELSE NULL END,
        p_created_by, p_description, p_reversal_of_movement_id
    ) RETURNING stock_movements.movement_id INTO v_movement_id;
    INSERT INTO variant_transaction_registry (
        variant_id, source_type, source_id
    ) VALUES (p_variant_id, p_source_type, p_source_id)
    ON CONFLICT DO NOTHING;
    INSERT INTO warehouse_reference_registry (
        warehouse_id, source_type, source_id
    ) VALUES (p_warehouse_id, p_source_type, p_source_id)
    ON CONFLICT DO NOTHING;
    replay_result := quantity_replay_inventory(p_variant_id, p_warehouse_id);
    PERFORM set_config('financee.inventory_engine', '', true);
    RETURN jsonb_build_object(
        'movement_id', v_movement_id,
        'idempotent', false,
        'total_cost_base', (
            SELECT total_cost_base FROM stock_movements
             WHERE stock_movements.movement_id = v_movement_id
        ),
        'reconciliation', replay_result
    );
END;
$$;

CREATE OR REPLACE FUNCTION quantity_reverse_stock_movement(
    p_movement_id bigint,
    p_reversal_date date,
    p_source_id bigint,
    p_created_by integer DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    original stock_movements%ROWTYPE;
    reverse_type text;
    reverse_cost numeric;
BEGIN
    SELECT * INTO original FROM stock_movements
     WHERE movement_id = p_movement_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Movement not found.'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    IF original.reversal_of_movement_id IS NOT NULL
       OR EXISTS (
           SELECT 1 FROM stock_movements
            WHERE reversal_of_movement_id = p_movement_id
       ) THEN
        RAISE EXCEPTION 'Movement is already reversed or is a reversal.'
            USING ERRCODE = 'check_violation';
    END IF;
    IF original.quantity_in > 0 THEN
        reverse_type := 'reversal_out';
        reverse_cost := NULL;
    ELSE
        reverse_type := 'reversal_in';
        reverse_cost := original.unit_cost_base;
    END IF;
    RETURN quantity_post_stock_movement(
        reverse_type, original.variant_id, original.warehouse_id,
        p_reversal_date, original.quantity_in + original.quantity_out,
        reverse_cost, 'movement_reversal', p_source_id, original.movement_id,
        original.document_number, p_created_by,
        'Reversal of movement ' || original.movement_id, NULL, p_movement_id
    );
END;
$$;

CREATE OR REPLACE FUNCTION quantity_stock_availability(
    p_variant_id bigint, p_warehouse_id bigint, p_as_of_date date DEFAULT NULL
) RETURNS numeric LANGUAGE sql STABLE AS $$
    SELECT COALESCE(sum(quantity_in - quantity_out), 0)
      FROM stock_movements
     WHERE variant_id = p_variant_id
       AND warehouse_id = p_warehouse_id
       AND (p_as_of_date IS NULL OR movement_date <= p_as_of_date);
$$;

CREATE OR REPLACE FUNCTION quantity_inventory_reconciliation(
    p_variant_id bigint DEFAULT NULL, p_warehouse_id bigint DEFAULT NULL
) RETURNS TABLE (
    variant_id bigint, warehouse_id bigint, movement_quantity numeric,
    balance_quantity numeric, fifo_quantity numeric, fifo_value numeric,
    is_reconciled boolean
) LANGUAGE sql STABLE AS $$
    WITH scopes AS (
        SELECT variant_id, warehouse_id FROM stock_movements
        UNION
        SELECT variant_id, warehouse_id FROM stock_balances
    ), movement AS (
        SELECT sm.variant_id, sm.warehouse_id,
               sum(sm.quantity_in - sm.quantity_out) AS quantity
          FROM stock_movements sm GROUP BY sm.variant_id, sm.warehouse_id
    ), fifo AS (
        SELECT fl.variant_id, fl.warehouse_id,
               sum(fl.remaining_quantity) AS quantity,
               sum(round(fl.remaining_quantity * fl.unit_cost_base, 6)) AS value
          FROM fifo_layers fl GROUP BY fl.variant_id, fl.warehouse_id
    )
    SELECT s.variant_id, s.warehouse_id,
           COALESCE(m.quantity, 0), COALESCE(b.on_hand_quantity, 0),
           COALESCE(f.quantity, 0), COALESCE(f.value, 0),
           COALESCE(m.quantity, 0) = COALESCE(b.on_hand_quantity, 0)
           AND COALESCE(m.quantity, 0) = COALESCE(f.quantity, 0)
      FROM scopes s
      LEFT JOIN movement m USING (variant_id, warehouse_id)
      LEFT JOIN stock_balances b USING (variant_id, warehouse_id)
      LEFT JOIN fifo f USING (variant_id, warehouse_id)
     WHERE (p_variant_id IS NULL OR s.variant_id = p_variant_id)
       AND (p_warehouse_id IS NULL OR s.warehouse_id = p_warehouse_id)
     ORDER BY s.warehouse_id, s.variant_id;
$$;

CREATE OR REPLACE FUNCTION quantity_schema_fingerprint()
RETURNS jsonb LANGUAGE sql STABLE AS $$
    SELECT jsonb_build_object(
        'family', family, 'version', version,
        'base_currency_code', base_currency_code,
        'foundation_tables', ARRAY[
            'chart_of_accounts', 'document_sequences', 'fifo_allocations',
            'fifo_layers', 'journal_entries', 'journal_lines',
            'product_variants', 'products', 'quantity_seed_registry',
            'stock_balances', 'stock_movements', 'tenant_schema_metadata',
            'units_of_measure', 'variant_transaction_registry',
            'warehouse_reference_registry', 'warehouses'
        ]
    ) FROM tenant_schema_metadata WHERE id = true;
$$;

INSERT INTO quantity_seed_registry (seed_key, seed_version, payload)
VALUES (
    'quantity.fifo', 1,
    '{"costing": "FIFO", "replay_limit": 10000, "negative_stock": false}'::jsonb
)
ON CONFLICT (seed_key) DO UPDATE
SET seed_version = GREATEST(
        quantity_seed_registry.seed_version, EXCLUDED.seed_version
    ),
    payload = EXCLUDED.payload,
    applied_at = CURRENT_TIMESTAMP;

UPDATE tenant_schema_metadata
   SET version = GREATEST(version, 5), applied_at = CURRENT_TIMESTAMP
 WHERE id = true AND family = 'quantity';
