-- Phase 17 tax and discount calculation foundation for QUANTITY schemas, v13.
DO $$
BEGIN
 IF to_regclass('tenant_schema_metadata') IS NULL OR NOT EXISTS(
  SELECT 1 FROM tenant_schema_metadata
   WHERE id=true AND family='quantity' AND version>=12
 ) THEN
  RAISE EXCEPTION 'Quantity tax/discount rollout refused: family/version mismatch.';
 END IF;
END;
$$;

ALTER TABLE tenant_schema_metadata
 ADD COLUMN IF NOT EXISTS tax_environment text NOT NULL DEFAULT 'non_tax';
DO $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_constraint
  WHERE conname='tenant_schema_metadata_tax_environment') THEN
  ALTER TABLE tenant_schema_metadata ADD CONSTRAINT
   tenant_schema_metadata_tax_environment
   CHECK(tax_environment IN ('tax','non_tax'));
 END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS tax_codes(
 tax_code_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code varchar(24) NOT NULL UNIQUE,
 name varchar(100) NOT NULL,
 rate_percent numeric(9,6) NOT NULL,
 purchase_account_code varchar(20) NOT NULL DEFAULT '1300',
 sale_account_code varchar(20) NOT NULL DEFAULT '2100',
 is_active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT tax_code_code_valid CHECK(code~'^[A-Z][A-Z0-9_-]{0,23}$'),
 CONSTRAINT tax_code_name_valid CHECK(btrim(name)<>''),
 CONSTRAINT tax_code_rate_valid CHECK(rate_percent>=0 AND rate_percent<=100)
);

-- Posted documents retain every applied input and result. These columns are
-- additive so existing non-tax invoices remain valid zero-tax snapshots.
ALTER TABLE purchase_invoices
 ADD COLUMN IF NOT EXISTS tax_mode varchar(10) NOT NULL DEFAULT 'exclusive',
 ADD COLUMN IF NOT EXISTS invoice_discount_type varchar(10) NOT NULL DEFAULT 'none',
 ADD COLUMN IF NOT EXISTS invoice_discount_value numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS line_discount_total_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS invoice_discount_total_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_total_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS rounding_adjustment_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
 ADD COLUMN IF NOT EXISTS reversal_tax_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id);
ALTER TABLE sale_invoices
 ADD COLUMN IF NOT EXISTS tax_mode varchar(10) NOT NULL DEFAULT 'exclusive',
 ADD COLUMN IF NOT EXISTS invoice_discount_type varchar(10) NOT NULL DEFAULT 'none',
 ADD COLUMN IF NOT EXISTS invoice_discount_value numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS line_discount_total_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS invoice_discount_total_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_total_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS rounding_adjustment_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
 ADD COLUMN IF NOT EXISTS reversal_tax_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id);
ALTER TABLE purchase_lines
 ADD COLUMN IF NOT EXISTS gross_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS line_discount_type varchar(10) NOT NULL DEFAULT 'none',
 ADD COLUMN IF NOT EXISTS line_discount_value numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS line_discount_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS invoice_discount_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_classification varchar(12) NOT NULL DEFAULT 'none',
 ADD COLUMN IF NOT EXISTS exemption_reference text,
 ADD COLUMN IF NOT EXISTS tax_code_snapshot varchar(24),
 ADD COLUMN IF NOT EXISTS tax_account_code_snapshot varchar(20),
 ADD COLUMN IF NOT EXISTS tax_rate_percent numeric(9,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_mode varchar(10) NOT NULL DEFAULT 'exclusive',
 ADD COLUMN IF NOT EXISTS taxable_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_base numeric(24,6) NOT NULL DEFAULT 0;
ALTER TABLE sale_lines
 ADD COLUMN IF NOT EXISTS gross_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS line_discount_type varchar(10) NOT NULL DEFAULT 'none',
 ADD COLUMN IF NOT EXISTS line_discount_value numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS line_discount_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS invoice_discount_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_classification varchar(12) NOT NULL DEFAULT 'none',
 ADD COLUMN IF NOT EXISTS exemption_reference text,
 ADD COLUMN IF NOT EXISTS tax_code_snapshot varchar(24),
 ADD COLUMN IF NOT EXISTS tax_account_code_snapshot varchar(20),
 ADD COLUMN IF NOT EXISTS tax_rate_percent numeric(9,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_mode varchar(10) NOT NULL DEFAULT 'exclusive',
 ADD COLUMN IF NOT EXISTS taxable_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_base numeric(24,6) NOT NULL DEFAULT 0;
ALTER TABLE sale_return_invoices
 ADD COLUMN IF NOT EXISTS discount_reversal_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_reversal_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
 ADD COLUMN IF NOT EXISTS reversal_tax_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id);
ALTER TABLE sale_return_lines
 ADD COLUMN IF NOT EXISTS discount_reversal_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS taxable_reversal_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_reversal_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_code_snapshot varchar(24),
 ADD COLUMN IF NOT EXISTS tax_rate_percent numeric(9,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_mode varchar(10) NOT NULL DEFAULT 'exclusive';
ALTER TABLE purchase_return_invoices
 ADD COLUMN IF NOT EXISTS discount_reversal_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_reversal_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
 ADD COLUMN IF NOT EXISTS reversal_tax_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id);
ALTER TABLE purchase_return_lines
 ADD COLUMN IF NOT EXISTS discount_reversal_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS taxable_reversal_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_reversal_base numeric(24,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_code_snapshot varchar(24),
 ADD COLUMN IF NOT EXISTS tax_rate_percent numeric(9,6) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS tax_mode varchar(10) NOT NULL DEFAULT 'exclusive';

SELECT set_config('financee.purchase_engine','allowed',true);
UPDATE purchase_lines SET gross_base=line_total_base,
 taxable_base=line_total_base WHERE gross_base=0 AND line_total_base<>0;
SELECT set_config('financee.purchase_engine','',true);
SELECT set_config('financee.sale_engine','allowed',true);
UPDATE sale_lines SET gross_base=line_total_base,
 taxable_base=line_total_base WHERE gross_base=0 AND line_total_base<>0;
SELECT set_config('financee.sale_engine','',true);

ALTER TABLE purchase_invoices DROP CONSTRAINT IF EXISTS purchase_totals_check;
ALTER TABLE sale_invoices DROP CONSTRAINT IF EXISTS sale_totals_check;
DO $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='purchase_tax_totals_check') THEN
  ALTER TABLE purchase_invoices ADD CONSTRAINT purchase_tax_totals_check CHECK(
   subtotal_base>=0 AND line_discount_total_base>=0
   AND invoice_discount_total_base>=0 AND tax_total_base>=0
   AND total_base>=0 AND tax_mode IN('inclusive','exclusive')
   AND invoice_discount_type IN('none','percent','fixed'));
 END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='sale_tax_totals_check') THEN
  ALTER TABLE sale_invoices ADD CONSTRAINT sale_tax_totals_check CHECK(
   subtotal_base>=0 AND line_discount_total_base>=0
   AND invoice_discount_total_base>=0 AND tax_total_base>=0
   AND total_base>=0 AND tax_mode IN('inclusive','exclusive')
   AND invoice_discount_type IN('none','percent','fixed'));
 END IF;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_upsert_tax_code(data jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE v_id bigint; c varchar; n varchar; r numeric; pa varchar; sa varchar;
 active boolean;
BEGIN
 IF (SELECT m.tax_environment FROM tenant_schema_metadata m WHERE m.id=true)<>'tax' THEN
  RAISE EXCEPTION 'Tax codes cannot be configured for a non-tax company.'
   USING ERRCODE='check_violation';
 END IF;
 c:=upper(btrim(COALESCE(data->>'code','')));
 n:=btrim(COALESCE(data->>'name',''));
 BEGIN
  r:=(data->>'rate_percent')::numeric;
  v_id:=NULLIF(data->>'tax_code_id','')::bigint;
  active:=COALESCE(NULLIF(data->>'is_active','')::boolean,true);
 EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
  RAISE EXCEPTION 'Tax code values are invalid.' USING ERRCODE='check_violation';
 END;
 pa:=COALESCE(NULLIF(data->>'purchase_account_code',''),'1300');
 sa:=COALESCE(NULLIF(data->>'sale_account_code',''),'2100');
 IF c='' OR n='' OR r IS NULL OR r<0 OR r>100 THEN
  RAISE EXCEPTION 'Tax code, name, and a rate from 0 through 100 are required.'
   USING ERRCODE='check_violation';
 END IF;
 IF NOT EXISTS(SELECT 1 FROM chart_of_accounts
  WHERE account_code=pa AND account_type='Asset' AND is_active)
  OR NOT EXISTS(SELECT 1 FROM chart_of_accounts
  WHERE account_code=sa AND account_type='Liability' AND is_active) THEN
  RAISE EXCEPTION 'Tax control accounts are invalid.'
   USING ERRCODE='foreign_key_violation';
 END IF;
 IF v_id IS NULL THEN
  INSERT INTO tax_codes(code,name,rate_percent,purchase_account_code,
   sale_account_code,is_active)
  VALUES(c,n,r,pa,sa,active) RETURNING tax_code_id INTO v_id;
 ELSE
  UPDATE tax_codes SET code=c,name=n,rate_percent=r,
   purchase_account_code=pa,sale_account_code=sa,is_active=active,
   updated_at=CURRENT_TIMESTAMP WHERE tax_code_id=v_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Tax code not found.'
   USING ERRCODE='foreign_key_violation'; END IF;
 END IF;
 RETURN jsonb_build_object('tax_code_id',v_id,'code',c,'name',n,
  'rate_percent',r,'purchase_account_code',pa,'sale_account_code',sa,
  'is_active',active);
END;
$$;

CREATE OR REPLACE FUNCTION quantity_tax_code_catalog(include_inactive boolean DEFAULT false)
RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT COALESCE(jsonb_agg(jsonb_build_object(
  'tax_code_id',tax_code_id,'code',code,'name',name,
  'rate_percent',rate_percent,'purchase_account_code',purchase_account_code,
  'sale_account_code',sale_account_code,'is_active',is_active)
  ORDER BY code),'[]'::jsonb)
 FROM tax_codes WHERE include_inactive OR is_active;
$$;

-- Pure authoritative calculator. Inputs and outputs are suitable for permanent
-- invoice-line snapshots; no historical document needs a live tax-code lookup.
CREATE OR REPLACE FUNCTION quantity_calculate_document(data jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
 lines jsonb; x jsonb; prepared jsonb:='[]'; results jsonb:='[]';
 env text; mode text; inv_type text; classification text; disc_type text;
 qty numeric; price numeric; gross numeric; line_disc numeric; after_line numeric;
 inv_input numeric; inv_total numeric; basis_total numeric:=0; allocated numeric:=0;
 alloc numeric; taxable numeric; tax numeric; total numeric; rate numeric;
 tc tax_codes%ROWTYPE; n integer:=0; count_lines integer; scale integer:=2;
 subtotal_sum numeric:=0; line_discount_sum numeric:=0;
 tax_sum numeric:=0; total_sum numeric:=0; exemption text; tax_id bigint;
BEGIN
 IF data IS NULL OR jsonb_typeof(data)<>'object' THEN
  RAISE EXCEPTION 'Calculation payload must be an object.'
   USING ERRCODE='check_violation';
 END IF;
 lines:=data->'lines';
 IF lines IS NULL OR jsonb_typeof(lines)<>'array' OR jsonb_array_length(lines)=0 THEN
  RAISE EXCEPTION 'At least one calculation line is required.'
   USING ERRCODE='check_violation';
 END IF;
 env:=(SELECT tax_environment FROM tenant_schema_metadata WHERE id=true);
 mode:=lower(COALESCE(NULLIF(data->>'tax_mode',''),'exclusive'));
 inv_type:=lower(COALESCE(NULLIF(data->>'invoice_discount_type',''),'none'));
 BEGIN
  inv_input:=COALESCE(NULLIF(data->>'invoice_discount_value','')::numeric,0);
  scale:=COALESCE(NULLIF(data->>'minor_units','')::integer,2);
 EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
  RAISE EXCEPTION 'Discount or precision value is invalid.'
   USING ERRCODE='check_violation';
 END;
 IF mode NOT IN('inclusive','exclusive') OR inv_type NOT IN('none','percent','fixed')
  OR inv_input<0 OR (inv_type='percent' AND inv_input>100)
  OR scale<0 OR scale>6 THEN
  RAISE EXCEPTION 'Tax mode, discount, or precision is invalid.'
   USING ERRCODE='check_violation';
 END IF;
 FOR x IN SELECT value FROM jsonb_array_elements(lines) LOOP
  n:=n+1;
  BEGIN
   qty:=(x->>'quantity')::numeric; price:=(x->>'unit_price')::numeric;
  EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
   RAISE EXCEPTION 'Calculation line % contains invalid numbers.',n
    USING ERRCODE='check_violation';
  END;
  IF qty<=0 OR price<0 OR qty<>round(qty,3) OR price<>round(price,6) THEN
   RAISE EXCEPTION 'Calculation line % has invalid quantity or price.',n
    USING ERRCODE='check_violation';
  END IF;
  gross:=round(qty*price,6);
  disc_type:=lower(COALESCE(NULLIF(x->>'discount_type',''),'none'));
  BEGIN line_disc:=COALESCE(NULLIF(x->>'discount_value','')::numeric,0);
  EXCEPTION WHEN others THEN RAISE EXCEPTION 'Line discount is invalid.'
   USING ERRCODE='check_violation'; END;
  IF disc_type='percent' THEN
   IF line_disc<0 OR line_disc>100 THEN RAISE EXCEPTION 'Percentage discount must be 0 through 100.'
    USING ERRCODE='check_violation'; END IF;
   line_disc:=round(gross*line_disc/100,scale);
  ELSIF disc_type='fixed' THEN
   IF line_disc<0 THEN RAISE EXCEPTION 'Fixed discount cannot be negative.'
    USING ERRCODE='check_violation'; END IF;
   line_disc:=round(line_disc,scale);
  ELSIF disc_type='none' THEN line_disc:=0;
  ELSE RAISE EXCEPTION 'Line discount type is invalid.'
   USING ERRCODE='check_violation'; END IF;
  IF line_disc>gross THEN RAISE EXCEPTION 'Discount cannot exceed line gross value.'
   USING ERRCODE='check_violation'; END IF;
  after_line:=round(gross-line_disc,scale); basis_total:=basis_total+after_line;
  prepared:=prepared||jsonb_build_array(jsonb_build_object(
   'input',x,'line_number',n,'gross',gross,'line_discount',line_disc,
   'after_line',after_line,'discount_type',disc_type));
 END LOOP;
 inv_total:=CASE inv_type WHEN 'percent' THEN round(basis_total*inv_input/100,scale)
  WHEN 'fixed' THEN round(inv_input,scale) ELSE 0 END;
 IF inv_total>basis_total THEN RAISE EXCEPTION 'Invoice discount cannot exceed eligible value.'
  USING ERRCODE='check_violation'; END IF;
 count_lines:=jsonb_array_length(prepared); n:=0;
 FOR x IN SELECT value FROM jsonb_array_elements(prepared) LOOP
  n:=n+1; after_line:=(x->>'after_line')::numeric;
  IF n=count_lines THEN alloc:=inv_total-allocated;
  ELSIF basis_total=0 THEN alloc:=0;
  ELSE alloc:=round(inv_total*after_line/basis_total,scale); END IF;
  allocated:=allocated+alloc; taxable:=round(after_line-alloc,scale);
  classification:=lower(COALESCE(NULLIF(x->'input'->>'tax_classification',''),
   CASE WHEN env='tax' THEN 'taxable' ELSE 'none' END));
  exemption:=NULLIF(btrim(COALESCE(x->'input'->>'exemption_reference','')),'');
  tax_id:=NULLIF(x->'input'->>'tax_code_id','')::bigint;
  rate:=0; tax:=0;
  IF env='non_tax' THEN
   IF tax_id IS NOT NULL OR classification NOT IN('none','') THEN
    RAISE EXCEPTION 'A non-tax company cannot calculate tax.'
     USING ERRCODE='check_violation'; END IF;
   classification:='none';
  ELSIF classification='taxable' THEN
   IF tax_id IS NULL THEN RAISE EXCEPTION 'Taxable lines require an active tax code.'
    USING ERRCODE='not_null_violation'; END IF;
   SELECT * INTO tc FROM tax_codes WHERE tax_code_id=tax_id AND is_active;
   IF NOT FOUND THEN RAISE EXCEPTION 'Active tax code not found.'
    USING ERRCODE='foreign_key_violation'; END IF;
   rate:=tc.rate_percent;
   IF mode='inclusive' THEN
    tax:=round(taxable-(taxable/(1+rate/100)),scale); taxable:=taxable-tax;
   ELSE tax:=round(taxable*rate/100,scale); END IF;
  ELSIF classification='zero_rated' THEN
   IF tax_id IS NULL THEN RAISE EXCEPTION 'Zero-rated lines require an active tax code.'
    USING ERRCODE='not_null_violation'; END IF;
   SELECT * INTO tc FROM tax_codes WHERE tax_code_id=tax_id AND is_active;
   IF NOT FOUND OR tc.rate_percent<>0 THEN RAISE EXCEPTION 'Zero-rated lines require a 0%% tax code.'
    USING ERRCODE='check_violation'; END IF;
  ELSIF classification='exempt' THEN
   IF exemption IS NULL THEN RAISE EXCEPTION 'Exempt lines require an exemption reference.'
    USING ERRCODE='not_null_violation'; END IF;
  ELSE RAISE EXCEPTION 'Tax classification is invalid.'
   USING ERRCODE='check_violation'; END IF;
  total:=CASE WHEN mode='inclusive' THEN after_line-alloc ELSE taxable+tax END;
  results:=results||jsonb_build_array(jsonb_build_object(
   'line_number',n,'gross_base',(x->>'gross')::numeric,
   'line_discount_type',x->>'discount_type',
   'line_discount_base',(x->>'line_discount')::numeric,
   'invoice_discount_base',alloc,'tax_classification',classification,
   'exemption_reference',exemption,'tax_code_id',tax_id,
   'tax_code',CASE WHEN tax_id IS NULL THEN NULL ELSE tc.code END,
   'purchase_tax_account_code',CASE WHEN tax_id IS NULL THEN NULL
    ELSE tc.purchase_account_code END,
   'sale_tax_account_code',CASE WHEN tax_id IS NULL THEN NULL
    ELSE tc.sale_account_code END,
   'tax_rate_percent',rate,'tax_mode',mode,'taxable_base',taxable,
   'tax_base',tax,'line_total_base',total));
  subtotal_sum:=subtotal_sum+(x->>'gross')::numeric;
  line_discount_sum:=line_discount_sum+(x->>'line_discount')::numeric;
  tax_sum:=tax_sum+tax; total_sum:=total_sum+total;
 END LOOP;
 RETURN jsonb_build_object('tax_environment',env,'tax_mode',mode,
  'invoice_discount_type',inv_type,'invoice_discount_value',inv_input,
  'subtotal_base',round(subtotal_sum,scale),
  'line_discount_total_base',round(line_discount_sum,scale),
  'invoice_discount_total_base',inv_total,'tax_total_base',round(tax_sum,scale),
  'total_base',round(total_sum,scale),'rounding_adjustment_base',0,
  'lines',results);
END;
$$;

CREATE OR REPLACE FUNCTION quantity_finalize_tax_document(
 p_kind text,p_document_id bigint,p_data jsonb,p_calculation jsonb,p_user integer
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE h record; x jsonb; original_line jsonb; n integer:=0;
 counterparty varchar; tax_lines jsonb:='[]';
 tax_journal bigint; tax_total numeric;
BEGIN
 IF p_kind NOT IN('purchase','sale') THEN RAISE EXCEPTION 'Invalid document kind.'
  USING ERRCODE='check_violation'; END IF;
 tax_total:=COALESCE((p_calculation->>'tax_total_base')::numeric,0);
 IF p_kind='purchase' THEN
  SELECT invoice_date,document_number,purchase_type,payment_account_code,vendor_name
   INTO h FROM purchase_invoices WHERE purchase_invoice_id=p_document_id FOR UPDATE;
  counterparty:=CASE WHEN h.purchase_type='credit' THEN '2000'
   ELSE h.payment_account_code END;
  PERFORM set_config('financee.purchase_engine','allowed',true);
  UPDATE purchase_invoices SET tax_mode=p_calculation->>'tax_mode',
   invoice_discount_type=p_calculation->>'invoice_discount_type',
   invoice_discount_value=(p_calculation->>'invoice_discount_value')::numeric,
   subtotal_base=(p_calculation->>'subtotal_base')::numeric,
   line_discount_total_base=(p_calculation->>'line_discount_total_base')::numeric,
   invoice_discount_total_base=(p_calculation->>'invoice_discount_total_base')::numeric,
   tax_total_base=tax_total,total_base=(p_calculation->>'total_base')::numeric,
   rounding_adjustment_base=(p_calculation->>'rounding_adjustment_base')::numeric
   WHERE purchase_invoice_id=p_document_id;
  FOR x IN SELECT value FROM jsonb_array_elements(p_calculation->'lines') LOOP
   n:=n+1; original_line:=(COALESCE(p_data->'lines',p_data->'items'))->(n-1);
   UPDATE purchase_lines SET
    gross_base=(x->>'gross_base')::numeric,
    line_discount_type=x->>'line_discount_type',
    line_discount_value=COALESCE((original_line->>'discount_value')::numeric,0),
    line_discount_base=(x->>'line_discount_base')::numeric,
    invoice_discount_base=(x->>'invoice_discount_base')::numeric,
    tax_classification=x->>'tax_classification',
    exemption_reference=x->>'exemption_reference',
    tax_code_snapshot=x->>'tax_code',
    tax_account_code_snapshot=x->>'purchase_tax_account_code',
    tax_rate_percent=(x->>'tax_rate_percent')::numeric,tax_mode=x->>'tax_mode',
    taxable_base=(x->>'taxable_base')::numeric,tax_base=(x->>'tax_base')::numeric
    WHERE purchase_invoice_id=p_document_id AND line_number=n;
  END LOOP;
  IF tax_total>0 THEN
   SELECT COALESCE(jsonb_agg(jsonb_build_object('account_code',grouped.account_code,
    'debit',grouped.amount,'credit',0,'description','Input tax')
    ORDER BY grouped.account_code),
    '[]'::jsonb) INTO tax_lines FROM(
     SELECT tax_account_code_snapshot account_code,round(sum(tax_base),4) amount
     FROM purchase_lines WHERE purchase_invoice_id=p_document_id AND tax_base>0
     GROUP BY tax_account_code_snapshot) grouped;
   tax_lines:=tax_lines||jsonb_build_array(jsonb_build_object(
    'account_code',counterparty,'debit',0,'credit',round(tax_total,4),
    'description','Tax payable to vendor'));
   tax_journal:=quantity_post_journal(h.invoice_date,
    'Purchase tax '||h.document_number,'purchase_tax',p_document_id,
    h.document_number,p_user,tax_lines);
   UPDATE purchase_invoices SET tax_journal_id=tax_journal
    WHERE purchase_invoice_id=p_document_id;
  END IF;
  PERFORM set_config('financee.purchase_engine','',true);
 ELSE
  SELECT invoice_date,document_number,sale_type,payment_account_code,customer_name
   INTO h FROM sale_invoices WHERE sale_invoice_id=p_document_id FOR UPDATE;
  counterparty:=CASE WHEN h.sale_type='credit' THEN '1200'
   ELSE h.payment_account_code END;
  PERFORM set_config('financee.sale_engine','allowed',true);
  UPDATE sale_invoices SET tax_mode=p_calculation->>'tax_mode',
   invoice_discount_type=p_calculation->>'invoice_discount_type',
   invoice_discount_value=(p_calculation->>'invoice_discount_value')::numeric,
   subtotal_base=(p_calculation->>'subtotal_base')::numeric,
   line_discount_total_base=(p_calculation->>'line_discount_total_base')::numeric,
   invoice_discount_total_base=(p_calculation->>'invoice_discount_total_base')::numeric,
   tax_total_base=tax_total,total_base=(p_calculation->>'total_base')::numeric,
   rounding_adjustment_base=(p_calculation->>'rounding_adjustment_base')::numeric
   WHERE sale_invoice_id=p_document_id;
  n:=0;
  FOR x IN SELECT value FROM jsonb_array_elements(p_calculation->'lines') LOOP
   n:=n+1; original_line:=(COALESCE(p_data->'lines',p_data->'items'))->(n-1);
   UPDATE sale_lines SET gross_base=(x->>'gross_base')::numeric,
    line_discount_type=x->>'line_discount_type',
    line_discount_value=COALESCE((original_line->>'discount_value')::numeric,0),
    line_discount_base=(x->>'line_discount_base')::numeric,
    invoice_discount_base=(x->>'invoice_discount_base')::numeric,
    tax_classification=x->>'tax_classification',
    exemption_reference=x->>'exemption_reference',
    tax_code_snapshot=x->>'tax_code',
    tax_account_code_snapshot=x->>'sale_tax_account_code',
    tax_rate_percent=(x->>'tax_rate_percent')::numeric,tax_mode=x->>'tax_mode',
    taxable_base=(x->>'taxable_base')::numeric,tax_base=(x->>'tax_base')::numeric
    WHERE sale_invoice_id=p_document_id AND line_number=n;
  END LOOP;
  IF tax_total>0 THEN
   tax_lines:=jsonb_build_array(jsonb_build_object('account_code',counterparty,
    'debit',round(tax_total,4),'credit',0,'description','Tax receivable'));
   SELECT tax_lines||COALESCE(jsonb_agg(jsonb_build_object(
    'account_code',grouped.account_code,'debit',0,'credit',grouped.amount,
    'description','Output tax') ORDER BY grouped.account_code),'[]'::jsonb)
    INTO tax_lines FROM(SELECT tax_account_code_snapshot account_code,
     round(sum(tax_base),4) amount FROM sale_lines
     WHERE sale_invoice_id=p_document_id AND tax_base>0
     GROUP BY tax_account_code_snapshot) grouped;
   tax_journal:=quantity_post_journal(h.invoice_date,'Sale tax '||h.document_number,
    'sale_tax',p_document_id,h.document_number,p_user,tax_lines);
   UPDATE sale_invoices SET tax_journal_id=tax_journal
    WHERE sale_invoice_id=p_document_id;
  END IF;
  PERFORM set_config('financee.sale_engine','',true);
 END IF;
 RETURN jsonb_build_object('tax_journal_id',tax_journal,
  'tax_total_base',tax_total,'total_base',p_calculation->'total_base');
END;
$$;

CREATE OR REPLACE FUNCTION quantity_prepare_tax_revision(
 p_kind text,p_document_id bigint,p_date date,p_user integer
) RETURNS void LANGUAGE plpgsql AS $$
DECLARE j bigint;
BEGIN
 IF p_kind='purchase' THEN
  SELECT tax_journal_id INTO j FROM purchase_invoices
   WHERE purchase_invoice_id=p_document_id FOR UPDATE;
  IF j IS NOT NULL THEN PERFORM quantity_reverse_journal(j,p_date,
   'Superseded purchase tax',p_user);
   PERFORM set_config('financee.purchase_engine','allowed',true);
   UPDATE purchase_invoices SET tax_journal_id=NULL
    WHERE purchase_invoice_id=p_document_id;
   PERFORM set_config('financee.purchase_engine','',true);
  END IF;
 ELSIF p_kind='sale' THEN
  SELECT tax_journal_id INTO j FROM sale_invoices
   WHERE sale_invoice_id=p_document_id FOR UPDATE;
  IF j IS NOT NULL THEN PERFORM quantity_reverse_journal(j,p_date,
   'Superseded sale tax',p_user);
   PERFORM set_config('financee.sale_engine','allowed',true);
   UPDATE sale_invoices SET tax_journal_id=NULL WHERE sale_invoice_id=p_document_id;
   PERFORM set_config('financee.sale_engine','',true);
  END IF;
 ELSE RAISE EXCEPTION 'Invalid document kind.' USING ERRCODE='check_violation';
 END IF;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_reverse_tax_document(
 p_kind text,p_document_id bigint,p_date date,p_user integer
) RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE j bigint; r bigint;
BEGIN
 IF p_kind='purchase' THEN
  SELECT tax_journal_id INTO j FROM purchase_invoices
   WHERE purchase_invoice_id=p_document_id FOR UPDATE;
  IF j IS NOT NULL THEN r:=quantity_reverse_journal(j,COALESCE(p_date,CURRENT_DATE),
   'Reverse purchase tax',p_user);
   PERFORM set_config('financee.purchase_engine','allowed',true);
   UPDATE purchase_invoices SET reversal_tax_journal_id=r
    WHERE purchase_invoice_id=p_document_id;
   PERFORM set_config('financee.purchase_engine','',true); END IF;
 ELSIF p_kind='sale' THEN
  SELECT tax_journal_id INTO j FROM sale_invoices
   WHERE sale_invoice_id=p_document_id FOR UPDATE;
  IF j IS NOT NULL THEN r:=quantity_reverse_journal(j,COALESCE(p_date,CURRENT_DATE),
   'Reverse sale tax',p_user);
   PERFORM set_config('financee.sale_engine','allowed',true);
   UPDATE sale_invoices SET reversal_tax_journal_id=r
    WHERE sale_invoice_id=p_document_id;
   PERFORM set_config('financee.sale_engine','',true); END IF;
 ELSE RAISE EXCEPTION 'Invalid document kind.' USING ERRCODE='check_violation';
 END IF;
 RETURN r;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_purchase_details(p_purchase_invoice_id bigint)
RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT to_jsonb(i)||jsonb_build_object('lines',COALESCE((
  SELECT jsonb_agg(to_jsonb(l)||jsonb_build_object(
   'sku',v.sku,'product_name',p.product_name,'unit_code',u.code,
   'warehouse_code',w.warehouse_code,'warehouse_name',w.warehouse_name)
   ORDER BY l.line_number)
  FROM purchase_lines l JOIN product_variants v USING(variant_id)
  JOIN products p USING(product_id) JOIN units_of_measure u USING(unit_id)
  JOIN warehouses w USING(warehouse_id)
  WHERE l.purchase_invoice_id=i.purchase_invoice_id),'[]'::jsonb))
 FROM purchase_invoices i
 WHERE i.purchase_invoice_id=p_purchase_invoice_id;
$$;

CREATE OR REPLACE FUNCTION quantity_sale_details(p_sale_invoice_id bigint)
RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT to_jsonb(i)||jsonb_build_object('lines',COALESCE((
  SELECT jsonb_agg(to_jsonb(l)||jsonb_build_object(
   'sku',v.sku,'product_name',p.product_name,'unit_code',u.code,
   'warehouse_code',w.warehouse_code,'warehouse_name',w.warehouse_name)
   ORDER BY l.line_number)
  FROM sale_lines l JOIN product_variants v USING(variant_id)
  JOIN products p USING(product_id) JOIN units_of_measure u USING(unit_id)
  JOIN warehouses w USING(warehouse_id)
  WHERE l.sale_invoice_id=i.sale_invoice_id),'[]'::jsonb))
 FROM sale_invoices i WHERE i.sale_invoice_id=p_sale_invoice_id;
$$;

CREATE OR REPLACE FUNCTION quantity_finalize_tax_return(
 p_kind text,p_return_id bigint,p_user integer
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE l record; h record; src record; previous_tax numeric; remaining_tax numeric;
 tax_value numeric; discount_value numeric; tax_total numeric:=0;
 discount_total numeric:=0; counterparty varchar; tax_lines jsonb; j bigint;
BEGIN
 IF p_kind='sale_return' THEN
  PERFORM set_config('financee.sale_return_engine','allowed',true);
  FOR l IN SELECT * FROM sale_return_lines WHERE sale_return_id=p_return_id
   ORDER BY line_number FOR UPDATE LOOP
   SELECT sl.*,si.sale_type,si.payment_account_code INTO src
    FROM sale_lines sl JOIN sale_invoices si USING(sale_invoice_id)
    WHERE sl.sale_line_id=l.source_sale_line_id;
   SELECT COALESCE(sum(rl.tax_reversal_base),0) INTO previous_tax
    FROM sale_return_lines rl JOIN sale_return_invoices ri USING(sale_return_id)
    WHERE rl.source_sale_line_id=src.sale_line_id AND ri.status='posted'
     AND rl.sale_return_id<>p_return_id;
   remaining_tax:=GREATEST(src.tax_base-previous_tax,0);
   tax_value:=CASE WHEN l.quantity=src.quantity-(
    SELECT COALESCE(sum(rl.quantity),0) FROM sale_return_lines rl
    JOIN sale_return_invoices ri USING(sale_return_id)
    WHERE rl.source_sale_line_id=src.sale_line_id AND ri.status='posted'
     AND rl.sale_return_id<>p_return_id)
    THEN remaining_tax ELSE LEAST(remaining_tax,
     round(src.tax_base*l.quantity/src.quantity,2)) END;
   discount_value:=round((src.line_discount_base+src.invoice_discount_base)
    *l.quantity/src.quantity,2);
   UPDATE sale_return_lines SET discount_reversal_base=discount_value,
    taxable_reversal_base=round(src.taxable_base*l.quantity/src.quantity,2),
    tax_reversal_base=tax_value,tax_code_snapshot=src.tax_code_snapshot,
    tax_rate_percent=src.tax_rate_percent,tax_mode=src.tax_mode
    WHERE sale_return_line_id=l.sale_return_line_id;
   tax_total:=tax_total+tax_value; discount_total:=discount_total+discount_value;
  END LOOP;
  SELECT ri.return_date,ri.document_number,
   CASE WHEN si.sale_type='credit' THEN '1200'
    ELSE si.payment_account_code END AS counterparty
   INTO h FROM sale_return_invoices ri JOIN sale_return_lines rl USING(sale_return_id)
   JOIN sale_lines sl ON sl.sale_line_id=rl.source_sale_line_id
   JOIN sale_invoices si USING(sale_invoice_id)
   WHERE ri.sale_return_id=p_return_id LIMIT 1;
  UPDATE sale_return_invoices SET tax_reversal_base=tax_total,
   discount_reversal_base=discount_total WHERE sale_return_id=p_return_id;
  IF tax_total>0 THEN
   SELECT COALESCE(jsonb_agg(jsonb_build_object('account_code',account_code,
    'debit',amount,'credit',0,'description','Output tax reversed')
    ORDER BY account_code),'[]'::jsonb) INTO tax_lines FROM(
    SELECT sl.tax_account_code_snapshot account_code,
     round(sum(rl.tax_reversal_base),4) amount
    FROM sale_return_lines rl JOIN sale_lines sl
     ON sl.sale_line_id=rl.source_sale_line_id
    WHERE rl.sale_return_id=p_return_id GROUP BY sl.tax_account_code_snapshot
   ) grouped WHERE account_code IS NOT NULL;
   tax_lines:=tax_lines||jsonb_build_array(jsonb_build_object(
    'account_code',h.counterparty,'debit',0,'credit',round(tax_total,4),
    'description','Customer tax credit'));
   j:=quantity_post_journal(h.return_date,'Sale-return tax '||h.document_number,
    'sale_return_tax',p_return_id,h.document_number,p_user,tax_lines);
   UPDATE sale_return_invoices SET tax_journal_id=j WHERE sale_return_id=p_return_id;
  END IF;
  PERFORM set_config('financee.sale_return_engine','',true);
 ELSIF p_kind='purchase_return' THEN
  PERFORM set_config('financee.purchase_return_engine','allowed',true);
  FOR l IN SELECT * FROM purchase_return_lines WHERE purchase_return_id=p_return_id
   ORDER BY line_number FOR UPDATE LOOP
   SELECT pl.*,pi.purchase_type,pi.payment_account_code INTO src
    FROM purchase_lines pl JOIN purchase_invoices pi USING(purchase_invoice_id)
    WHERE pl.purchase_line_id=l.source_purchase_line_id;
   SELECT COALESCE(sum(rl.tax_reversal_base),0) INTO previous_tax
    FROM purchase_return_lines rl JOIN purchase_return_invoices ri
     USING(purchase_return_id)
    WHERE rl.source_purchase_line_id=src.purchase_line_id AND ri.status='posted'
     AND rl.purchase_return_id<>p_return_id;
   remaining_tax:=GREATEST(src.tax_base-previous_tax,0);
   tax_value:=CASE WHEN l.quantity=src.quantity-(
    SELECT COALESCE(sum(rl.quantity),0) FROM purchase_return_lines rl
    JOIN purchase_return_invoices ri USING(purchase_return_id)
    WHERE rl.source_purchase_line_id=src.purchase_line_id AND ri.status='posted'
     AND rl.purchase_return_id<>p_return_id)
    THEN remaining_tax ELSE LEAST(remaining_tax,
     round(src.tax_base*l.quantity/src.quantity,2)) END;
   discount_value:=round((src.line_discount_base+src.invoice_discount_base)
    *l.quantity/src.quantity,2);
   UPDATE purchase_return_lines SET discount_reversal_base=discount_value,
    taxable_reversal_base=round(src.taxable_base*l.quantity/src.quantity,2),
    tax_reversal_base=tax_value,tax_code_snapshot=src.tax_code_snapshot,
    tax_rate_percent=src.tax_rate_percent,tax_mode=src.tax_mode
    WHERE purchase_return_line_id=l.purchase_return_line_id;
   tax_total:=tax_total+tax_value;discount_total:=discount_total+discount_value;
  END LOOP;
  SELECT ri.return_date,ri.document_number,
   CASE WHEN pi.purchase_type='credit' THEN '2000'
    ELSE pi.payment_account_code END AS counterparty
   INTO h FROM purchase_return_invoices ri JOIN purchase_return_lines rl
    USING(purchase_return_id) JOIN purchase_lines pl
    ON pl.purchase_line_id=rl.source_purchase_line_id
   JOIN purchase_invoices pi USING(purchase_invoice_id)
   WHERE ri.purchase_return_id=p_return_id LIMIT 1;
  UPDATE purchase_return_invoices SET tax_reversal_base=tax_total,
   discount_reversal_base=discount_total WHERE purchase_return_id=p_return_id;
  IF tax_total>0 THEN
   tax_lines:=jsonb_build_array(jsonb_build_object('account_code',h.counterparty,
    'debit',round(tax_total,4),'credit',0,'description','Vendor tax credit'));
   SELECT tax_lines||COALESCE(jsonb_agg(jsonb_build_object(
    'account_code',account_code,'debit',0,'credit',amount,
    'description','Input tax reversed') ORDER BY account_code),'[]'::jsonb)
    INTO tax_lines FROM(SELECT pl.tax_account_code_snapshot account_code,
     round(sum(rl.tax_reversal_base),4) amount FROM purchase_return_lines rl
     JOIN purchase_lines pl ON pl.purchase_line_id=rl.source_purchase_line_id
     WHERE rl.purchase_return_id=p_return_id
     GROUP BY pl.tax_account_code_snapshot) grouped WHERE account_code IS NOT NULL;
   j:=quantity_post_journal(h.return_date,'Purchase-return tax '||h.document_number,
    'purchase_return_tax',p_return_id,h.document_number,p_user,tax_lines);
   UPDATE purchase_return_invoices SET tax_journal_id=j
    WHERE purchase_return_id=p_return_id;
  END IF;
  PERFORM set_config('financee.purchase_return_engine','',true);
 ELSE RAISE EXCEPTION 'Invalid return kind.' USING ERRCODE='check_violation';
 END IF;
 RETURN jsonb_build_object('tax_journal_id',j,'tax_reversal_base',tax_total,
  'discount_reversal_base',discount_total);
END;
$$;

CREATE OR REPLACE FUNCTION quantity_prepare_tax_return_revision(
 p_kind text,p_return_id bigint,p_date date,p_user integer
) RETURNS void LANGUAGE plpgsql AS $$
DECLARE j bigint;
BEGIN
 IF p_kind='sale_return' THEN
  SELECT tax_journal_id INTO j FROM sale_return_invoices
   WHERE sale_return_id=p_return_id FOR UPDATE;
  IF j IS NOT NULL THEN PERFORM quantity_reverse_journal(j,p_date,
   'Superseded sale-return tax',p_user);
   PERFORM set_config('financee.sale_return_engine','allowed',true);
   UPDATE sale_return_invoices SET tax_journal_id=NULL WHERE sale_return_id=p_return_id;
   PERFORM set_config('financee.sale_return_engine','',true); END IF;
 ELSIF p_kind='purchase_return' THEN
  SELECT tax_journal_id INTO j FROM purchase_return_invoices
   WHERE purchase_return_id=p_return_id FOR UPDATE;
  IF j IS NOT NULL THEN PERFORM quantity_reverse_journal(j,p_date,
   'Superseded purchase-return tax',p_user);
   PERFORM set_config('financee.purchase_return_engine','allowed',true);
   UPDATE purchase_return_invoices SET tax_journal_id=NULL
    WHERE purchase_return_id=p_return_id;
   PERFORM set_config('financee.purchase_return_engine','',true); END IF;
 ELSE RAISE EXCEPTION 'Invalid return kind.' USING ERRCODE='check_violation'; END IF;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_reverse_tax_return(
 p_kind text,p_return_id bigint,p_date date,p_user integer
) RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE j bigint;r bigint;
BEGIN
 IF p_kind='sale_return' THEN
  SELECT tax_journal_id INTO j FROM sale_return_invoices
   WHERE sale_return_id=p_return_id FOR UPDATE;
  IF j IS NOT NULL THEN r:=quantity_reverse_journal(j,COALESCE(p_date,CURRENT_DATE),
   'Reverse sale-return tax',p_user);
   PERFORM set_config('financee.sale_return_engine','allowed',true);
   UPDATE sale_return_invoices SET reversal_tax_journal_id=r
    WHERE sale_return_id=p_return_id;
   PERFORM set_config('financee.sale_return_engine','',true); END IF;
 ELSIF p_kind='purchase_return' THEN
  SELECT tax_journal_id INTO j FROM purchase_return_invoices
   WHERE purchase_return_id=p_return_id FOR UPDATE;
  IF j IS NOT NULL THEN r:=quantity_reverse_journal(j,COALESCE(p_date,CURRENT_DATE),
   'Reverse purchase-return tax',p_user);
   PERFORM set_config('financee.purchase_return_engine','allowed',true);
   UPDATE purchase_return_invoices SET reversal_tax_journal_id=r
    WHERE purchase_return_id=p_return_id;
   PERFORM set_config('financee.purchase_return_engine','',true); END IF;
 ELSE RAISE EXCEPTION 'Invalid return kind.' USING ERRCODE='check_violation'; END IF;
 RETURN r;
END;
$$;

INSERT INTO quantity_seed_registry(seed_key,seed_version,payload)
VALUES('quantity.tax_discounts',1,'{"phase":17,"schema_version":13}'::jsonb)
ON CONFLICT(seed_key) DO UPDATE SET
 seed_version=GREATEST(quantity_seed_registry.seed_version,EXCLUDED.seed_version),
 payload=EXCLUDED.payload,applied_at=CURRENT_TIMESTAMP;
UPDATE tenant_schema_metadata SET version=GREATEST(version,13),
 applied_at=CURRENT_TIMESTAMP WHERE id=true AND family='quantity';
