-- Idempotent Phase 7 product, variant, SKU, and unit masters, version 3.
DO $$
BEGIN
    IF to_regclass('tenant_schema_metadata') IS NULL
       OR NOT EXISTS (
           SELECT 1 FROM tenant_schema_metadata
            WHERE id = true AND family = 'quantity' AND version >= 2
       ) THEN
        RAISE EXCEPTION 'Quantity item rollout refused: family/version mismatch.';
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS units_of_measure (
    unit_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(8) NOT NULL UNIQUE,
    unit_name varchar(40) NOT NULL UNIQUE,
    quantity_scale smallint NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT units_of_measure_code_format CHECK (code ~ '^[A-Z]{1,8}$'),
    CONSTRAINT units_of_measure_scale_check CHECK (quantity_scale IN (0, 3))
);

INSERT INTO units_of_measure (code, unit_name, quantity_scale)
VALUES
    ('PCS', 'Piece', 0),
    ('BOX', 'Box', 0),
    ('KG', 'Kilogram', 3),
    ('GM', 'Gram', 3),
    ('LTR', 'Litre', 3),
    ('MTR', 'Metre', 3)
ON CONFLICT (code) DO UPDATE
SET unit_name = EXCLUDED.unit_name,
    quantity_scale = EXCLUDED.quantity_scale;

CREATE TABLE IF NOT EXISTS products (
    product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name varchar(150) NOT NULL,
    category varchar(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    created_by integer,
    updated_by integer,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    normalized_name text GENERATED ALWAYS AS (
        lower(regexp_replace(btrim(product_name), '\s+', ' ', 'g'))
    ) STORED,
    normalized_category text GENERATED ALWAYS AS (
        lower(regexp_replace(btrim(category), '\s+', ' ', 'g'))
    ) STORED,
    CONSTRAINT products_name_check CHECK (btrim(product_name) <> ''),
    CONSTRAINT products_category_check CHECK (btrim(category) <> ''),
    CONSTRAINT products_normalized_unique UNIQUE (
        normalized_name, normalized_category
    )
);

CREATE TABLE IF NOT EXISTS product_variants (
    variant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES products(product_id),
    sku varchar(64) NOT NULL,
    brand varchar(100) NOT NULL,
    model varchar(100) NOT NULL,
    color varchar(100) NOT NULL,
    storage varchar(100) NOT NULL,
    ram varchar(100) NOT NULL,
    region varchar(100) NOT NULL,
    condition varchar(100) NOT NULL,
    unit_id smallint NOT NULL REFERENCES units_of_measure(unit_id),
    reorder_level numeric NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_by integer,
    updated_by integer,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    normalized_sku text GENERATED ALWAYS AS (
        upper(regexp_replace(btrim(sku), '\s+', '', 'g'))
    ) STORED,
    normalized_brand text GENERATED ALWAYS AS (
        lower(regexp_replace(btrim(brand), '\s+', ' ', 'g'))
    ) STORED,
    normalized_model text GENERATED ALWAYS AS (
        lower(regexp_replace(btrim(model), '\s+', ' ', 'g'))
    ) STORED,
    normalized_color text GENERATED ALWAYS AS (
        lower(regexp_replace(btrim(color), '\s+', ' ', 'g'))
    ) STORED,
    normalized_storage text GENERATED ALWAYS AS (
        lower(regexp_replace(btrim(storage), '\s+', ' ', 'g'))
    ) STORED,
    normalized_ram text GENERATED ALWAYS AS (
        lower(regexp_replace(btrim(ram), '\s+', ' ', 'g'))
    ) STORED,
    normalized_region text GENERATED ALWAYS AS (
        lower(regexp_replace(btrim(region), '\s+', ' ', 'g'))
    ) STORED,
    normalized_condition text GENERATED ALWAYS AS (
        lower(regexp_replace(btrim(condition), '\s+', ' ', 'g'))
    ) STORED,
    CONSTRAINT product_variants_sku_check CHECK (
        btrim(sku) <> '' AND sku ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'
    ),
    CONSTRAINT product_variants_dimensions_check CHECK (
        btrim(brand) <> '' AND btrim(model) <> '' AND btrim(color) <> ''
        AND btrim(storage) <> '' AND btrim(ram) <> '' AND btrim(region) <> ''
        AND btrim(condition) <> ''
    ),
    CONSTRAINT product_variants_reorder_check CHECK (
        reorder_level >= 0
        AND reorder_level < 1000000000000000::numeric
        AND reorder_level = round(reorder_level, 3)
    ),
    CONSTRAINT product_variants_sku_unique UNIQUE (normalized_sku),
    CONSTRAINT product_variants_combination_unique UNIQUE (
        product_id, normalized_brand, normalized_model, normalized_color,
        normalized_storage, normalized_ram, normalized_region,
        normalized_condition, unit_id
    )
);

-- Phase 7 prerelease reruns may encounter the earlier numeric(18,3) prototype,
-- whose type coercion rounded a fourth decimal before the trigger could reject
-- it. Store exact numeric input and enforce scale explicitly instead.
DROP TRIGGER IF EXISTS product_variants_precision ON product_variants;
ALTER TABLE product_variants
    ALTER COLUMN reorder_level TYPE numeric USING reorder_level::numeric;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conrelid = 'product_variants'::regclass
           AND conname = 'product_variants_reorder_precision_check'
    ) THEN
        ALTER TABLE product_variants
            ADD CONSTRAINT product_variants_reorder_precision_check CHECK (
                reorder_level < 1000000000000000::numeric
                AND reorder_level = round(reorder_level, 3)
            );
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS product_variants_product_idx
    ON product_variants(product_id);
CREATE INDEX IF NOT EXISTS product_variants_lookup_idx
    ON product_variants(normalized_model, normalized_brand, normalized_sku);

CREATE TABLE IF NOT EXISTS variant_transaction_registry (
    reference_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id bigint NOT NULL REFERENCES product_variants(variant_id),
    source_type varchar(32) NOT NULL,
    source_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT variant_transaction_registry_source_check CHECK (
        source_type ~ '^[a-z][a-z0-9_]{1,31}$'
    ),
    CONSTRAINT variant_transaction_registry_unique UNIQUE (
        variant_id, source_type, source_id
    )
);

CREATE OR REPLACE FUNCTION quantity_normalize_sku_token(value text)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
    SELECT trim(both '-' FROM regexp_replace(
        upper(COALESCE(value, '')), '[^A-Z0-9]+', '-', 'g'
    ));
$$;

CREATE OR REPLACE FUNCTION quantity_suggest_sku(
    p_product_name text, p_brand text, p_model text, p_color text,
    p_storage text, p_ram text, p_region text, p_condition text
) RETURNS text LANGUAGE plpgsql AS $$
DECLARE
    base_sku text;
    candidate text;
    suffix integer := 1;
BEGIN
    base_sku := left(concat_ws('-',
        quantity_normalize_sku_token(p_product_name),
        quantity_normalize_sku_token(p_brand),
        quantity_normalize_sku_token(p_model),
        quantity_normalize_sku_token(p_color),
        quantity_normalize_sku_token(p_storage),
        quantity_normalize_sku_token(p_ram),
        quantity_normalize_sku_token(p_region),
        quantity_normalize_sku_token(p_condition)
    ), 56);
    IF base_sku = '' THEN
        RAISE EXCEPTION 'SKU source values are required.'
            USING ERRCODE = 'check_violation';
    END IF;
    PERFORM pg_advisory_xact_lock(hashtextextended(base_sku, 7307));
    candidate := base_sku;
    WHILE EXISTS (
        SELECT 1 FROM product_variants
         WHERE normalized_sku = upper(candidate)
    ) LOOP
        suffix := suffix + 1;
        candidate := left(base_sku, 64 - length(suffix::text) - 1)
                     || '-' || suffix::text;
    END LOOP;
    RETURN candidate;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_validate_quantity(
    p_variant_id bigint, p_quantity numeric, p_allow_zero boolean DEFAULT false
) RETURNS void LANGUAGE plpgsql STABLE AS $$
DECLARE
    scale smallint;
BEGIN
    SELECT u.quantity_scale INTO scale
      FROM product_variants v
      JOIN units_of_measure u ON u.unit_id = v.unit_id
     WHERE v.variant_id = p_variant_id AND v.is_active AND u.is_active;
    IF scale IS NULL THEN
        RAISE EXCEPTION 'Unknown or inactive variant/unit.'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    IF p_quantity IS NULL OR p_quantity < 0
       OR (p_quantity = 0 AND NOT p_allow_zero)
       OR p_quantity <> round(p_quantity, scale)
       OR abs(p_quantity) >= 1000000000000000::numeric THEN
        RAISE EXCEPTION 'Quantity is invalid for the selected unit.'
            USING ERRCODE = 'check_violation';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_variant_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM variant_transaction_registry
         WHERE variant_id = OLD.variant_id
    ) AND (
        upper(regexp_replace(btrim(NEW.sku), '\s+', '', 'g'))
            IS DISTINCT FROM OLD.normalized_sku
        OR NEW.unit_id IS DISTINCT FROM OLD.unit_id
    ) THEN
        RAISE EXCEPTION 'SKU and unit are locked after transactions exist.'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS product_variants_transaction_lock ON product_variants;
CREATE TRIGGER product_variants_transaction_lock
BEFORE UPDATE ON product_variants
FOR EACH ROW EXECUTE FUNCTION quantity_variant_guard();

CREATE OR REPLACE FUNCTION quantity_variant_precision_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    scale smallint;
BEGIN
    SELECT quantity_scale INTO scale FROM units_of_measure
     WHERE unit_id = NEW.unit_id AND is_active;
    IF scale IS NULL THEN
        RAISE EXCEPTION 'Unknown or inactive unit.'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    IF NEW.reorder_level <> round(NEW.reorder_level, scale) THEN
        RAISE EXCEPTION 'Reorder level is invalid for the selected unit.'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS product_variants_precision ON product_variants;
CREATE TRIGGER product_variants_precision
BEFORE INSERT OR UPDATE OF unit_id, reorder_level ON product_variants
FOR EACH ROW EXECUTE FUNCTION quantity_variant_precision_guard();

CREATE OR REPLACE FUNCTION quantity_create_product(payload jsonb)
RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
    new_id bigint;
BEGIN
    INSERT INTO products (
        product_name, category, description, created_by, updated_by
    ) VALUES (
        btrim(payload->>'product_name'), btrim(payload->>'category'),
        NULLIF(btrim(payload->>'description'), ''),
        (payload->>'user_id')::integer, (payload->>'user_id')::integer
    ) RETURNING product_id INTO new_id;
    RETURN new_id;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_create_variant(payload jsonb)
RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
    new_id bigint;
    selected_sku text;
    product_name text;
BEGIN
    SELECT p.product_name INTO product_name FROM products p
     WHERE p.product_id = (payload->>'product_id')::bigint AND p.is_active;
    IF product_name IS NULL THEN
        RAISE EXCEPTION 'Unknown or inactive product.'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    selected_sku := NULLIF(btrim(payload->>'sku'), '');
    IF selected_sku IS NULL THEN
        selected_sku := quantity_suggest_sku(
            product_name, payload->>'brand', payload->>'model',
            payload->>'color', payload->>'storage', payload->>'ram',
            payload->>'region', payload->>'condition'
        );
    END IF;
    INSERT INTO product_variants (
        product_id, sku, brand, model, color, storage, ram, region, condition,
        unit_id, reorder_level, created_by, updated_by
    ) VALUES (
        (payload->>'product_id')::bigint, selected_sku,
        btrim(payload->>'brand'), btrim(payload->>'model'),
        btrim(payload->>'color'), btrim(payload->>'storage'),
        btrim(payload->>'ram'), btrim(payload->>'region'),
        btrim(payload->>'condition'), (payload->>'unit_id')::smallint,
        COALESCE((payload->>'reorder_level')::numeric, 0),
        (payload->>'user_id')::integer, (payload->>'user_id')::integer
    ) RETURNING variant_id INTO new_id;
    RETURN new_id;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_update_product(
    p_product_id bigint, payload jsonb
) RETURNS bigint LANGUAGE plpgsql AS $$
BEGIN
    UPDATE products
       SET product_name = COALESCE(
               NULLIF(btrim(payload->>'product_name'), ''), product_name
           ),
           category = COALESCE(
               NULLIF(btrim(payload->>'category'), ''), category
           ),
           description = CASE
               WHEN payload ? 'description'
               THEN NULLIF(btrim(payload->>'description'), '')
               ELSE description
           END,
           is_active = COALESCE((payload->>'is_active')::boolean, is_active),
           updated_by = COALESCE((payload->>'user_id')::integer, updated_by),
           updated_at = CURRENT_TIMESTAMP
     WHERE product_id = p_product_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Product not found.'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    RETURN p_product_id;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_update_variant(
    p_variant_id bigint, payload jsonb
) RETURNS bigint LANGUAGE plpgsql AS $$
BEGIN
    UPDATE product_variants
       SET sku = COALESCE(NULLIF(btrim(payload->>'sku'), ''), sku),
           brand = COALESCE(NULLIF(btrim(payload->>'brand'), ''), brand),
           model = COALESCE(NULLIF(btrim(payload->>'model'), ''), model),
           color = COALESCE(NULLIF(btrim(payload->>'color'), ''), color),
           storage = COALESCE(NULLIF(btrim(payload->>'storage'), ''), storage),
           ram = COALESCE(NULLIF(btrim(payload->>'ram'), ''), ram),
           region = COALESCE(NULLIF(btrim(payload->>'region'), ''), region),
           condition = COALESCE(NULLIF(btrim(payload->>'condition'), ''), condition),
           unit_id = COALESCE((payload->>'unit_id')::smallint, unit_id),
           reorder_level = COALESCE(
               (payload->>'reorder_level')::numeric, reorder_level
           ),
           is_active = COALESCE((payload->>'is_active')::boolean, is_active),
           updated_by = COALESCE((payload->>'user_id')::integer, updated_by),
           updated_at = CURRENT_TIMESTAMP
     WHERE variant_id = p_variant_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Variant not found.'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    RETURN p_variant_id;
END;
$$;

CREATE OR REPLACE FUNCTION quantity_item_catalog(
    search_text text DEFAULT NULL, active_only boolean DEFAULT true
) RETURNS TABLE (
    product_id bigint, product_name varchar, category varchar,
    variant_id bigint, sku varchar, brand varchar, model varchar,
    color varchar, storage varchar, ram varchar, region varchar,
    condition varchar, unit_code varchar, unit_name varchar,
    quantity_scale smallint, reorder_level numeric, is_active boolean
) LANGUAGE sql STABLE AS $$
    SELECT p.product_id, p.product_name, p.category, v.variant_id, v.sku,
           v.brand, v.model, v.color, v.storage, v.ram, v.region, v.condition,
           u.code, u.unit_name, u.quantity_scale, v.reorder_level,
           (p.is_active AND v.is_active AND u.is_active)
      FROM products p
      JOIN product_variants v ON v.product_id = p.product_id
      JOIN units_of_measure u ON u.unit_id = v.unit_id
     WHERE (NOT active_only OR (p.is_active AND v.is_active AND u.is_active))
       AND (search_text IS NULL OR btrim(search_text) = ''
            OR v.sku ILIKE '%' || search_text || '%'
            OR p.product_name ILIKE '%' || search_text || '%'
            OR v.brand ILIKE '%' || search_text || '%'
            OR v.model ILIKE '%' || search_text || '%')
     ORDER BY p.product_name, v.sku;
$$;

CREATE OR REPLACE FUNCTION quantity_schema_fingerprint()
RETURNS jsonb LANGUAGE sql STABLE AS $$
    SELECT jsonb_build_object(
        'family', family, 'version', version,
        'base_currency_code', base_currency_code,
        'foundation_tables', ARRAY[
            'chart_of_accounts', 'document_sequences', 'journal_entries',
            'journal_lines', 'product_variants', 'products',
            'quantity_seed_registry', 'tenant_schema_metadata',
            'units_of_measure', 'variant_transaction_registry'
        ],
        'foundation_sequences', ARRAY[
            'chart_of_accounts_account_id_seq',
            'journal_entries_journal_id_seq',
            'journal_lines_line_id_seq',
            'product_variants_variant_id_seq', 'products_product_id_seq',
            'quantity_foundation_id_seq',
            'units_of_measure_unit_id_seq',
            'variant_transaction_registry_reference_id_seq'
        ]
    ) FROM tenant_schema_metadata WHERE id = true;
$$;

INSERT INTO quantity_seed_registry (seed_key, seed_version, payload)
VALUES (
    'quantity.item_master', 1,
    '{"units": 6, "dimensions": 7, "quantity_precision": 3}'::jsonb
)
ON CONFLICT (seed_key) DO UPDATE
SET seed_version = GREATEST(
        quantity_seed_registry.seed_version, EXCLUDED.seed_version
    ),
    payload = EXCLUDED.payload,
    applied_at = CURRENT_TIMESTAMP;

UPDATE tenant_schema_metadata
   SET version = GREATEST(version, 3), applied_at = CURRENT_TIMESTAMP
 WHERE id = true AND family = 'quantity';
