-- Idempotent Phase 16 physical counts and adjustments, QUANTITY v12.
DO $$ BEGIN
 IF to_regclass('tenant_schema_metadata') IS NULL OR NOT EXISTS(
  SELECT 1 FROM tenant_schema_metadata WHERE id=true AND family='quantity' AND version>=11
 ) THEN RAISE EXCEPTION 'Quantity count rollout refused: family/version mismatch.'; END IF;
END $$;

CREATE TABLE IF NOT EXISTS physical_counts(
 count_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 document_number varchar(32) NOT NULL UNIQUE,count_date date NOT NULL,
 cutoff_date date NOT NULL,warehouse_id bigint NOT NULL REFERENCES warehouses(warehouse_id),
 description text,status varchar(12) NOT NULL DEFAULT 'submitted',
 idempotency_key varchar(100) NOT NULL UNIQUE,request_fingerprint varchar(32) NOT NULL,
 adjustment_id bigint UNIQUE,created_by integer,approved_by integer,reversed_by integer,
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,approved_at timestamptz,
 reversed_at timestamptz,updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK(status IN('submitted','posted','reversed','cancelled')),
 CHECK(cutoff_date<=count_date)
);
CREATE TABLE IF NOT EXISTS physical_count_lines(
 count_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 count_id bigint NOT NULL REFERENCES physical_counts(count_id),line_number integer NOT NULL,
 variant_id bigint NOT NULL REFERENCES product_variants(variant_id),
 system_quantity numeric NOT NULL,counted_quantity numeric NOT NULL,variance numeric NOT NULL,
 positive_unit_cost_base numeric(20,6),reason varchar(300) NOT NULL,note text,
 CHECK(system_quantity>=0 AND counted_quantity>=0),
 CHECK(system_quantity=round(system_quantity,3) AND counted_quantity=round(counted_quantity,3)),
 CHECK(variance=counted_quantity-system_quantity),
 CHECK(variance<=0 OR positive_unit_cost_base>0),
 UNIQUE(count_id,line_number),UNIQUE(count_id,variant_id)
);
CREATE TABLE IF NOT EXISTS inventory_adjustments(
 adjustment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 count_id bigint NOT NULL UNIQUE REFERENCES physical_counts(count_id),
 document_number varchar(32) NOT NULL UNIQUE,adjustment_date date NOT NULL,
 warehouse_id bigint NOT NULL REFERENCES warehouses(warehouse_id),status varchar(10) NOT NULL DEFAULT 'posted',
 gain_total_base numeric(24,6) NOT NULL DEFAULT 0,loss_total_base numeric(24,6) NOT NULL DEFAULT 0,
 journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
 reversal_journal_id bigint UNIQUE REFERENCES journal_entries(journal_id),
 approved_by integer NOT NULL,reversed_by integer,created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 reversed_at timestamptz,CHECK(status IN('posted','reversed')),CHECK(gain_total_base>=0 AND loss_total_base>=0)
);
ALTER TABLE physical_counts DROP CONSTRAINT IF EXISTS physical_counts_adjustment_id_fkey;
ALTER TABLE physical_counts ADD CONSTRAINT physical_counts_adjustment_id_fkey
 FOREIGN KEY(adjustment_id) REFERENCES inventory_adjustments(adjustment_id) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE IF NOT EXISTS inventory_adjustment_lines(
 adjustment_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 adjustment_id bigint NOT NULL REFERENCES inventory_adjustments(adjustment_id),
 count_line_id bigint NOT NULL UNIQUE REFERENCES physical_count_lines(count_line_id),
 variant_id bigint NOT NULL REFERENCES product_variants(variant_id),quantity_difference numeric NOT NULL,
 unit_cost_base numeric(20,6) NOT NULL,total_cost_base numeric(24,6) NOT NULL,
 reason varchar(300) NOT NULL,movement_id bigint NOT NULL UNIQUE REFERENCES stock_movements(movement_id),
 CHECK(quantity_difference<>0 AND quantity_difference=round(quantity_difference,3)),
 CHECK(unit_cost_base>=0 AND total_cost_base>=0)
);

CREATE OR REPLACE FUNCTION quantity_protect_count() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF current_setting('financee.count_engine',true)='allowed' THEN RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;END IF;
 RAISE EXCEPTION 'Count and adjustment records are immutable; use controlled operations.' USING ERRCODE='check_violation';
END $$;
DO $$ DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['physical_counts','physical_count_lines','inventory_adjustments','inventory_adjustment_lines'] LOOP
 EXECUTE format('DROP TRIGGER IF EXISTS %I_guard ON %I',t,t);
 EXECUTE format('CREATE TRIGGER %I_guard BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION quantity_protect_count()',t,t);
END LOOP;END $$;

CREATE OR REPLACE FUNCTION quantity_count_fingerprint(data jsonb) RETURNS varchar LANGUAGE sql IMMUTABLE AS $$
 SELECT md5(jsonb_build_object('count_date',data->>'count_date','cutoff_date',COALESCE(data->>'cutoff_date',data->>'count_date'),
 'warehouse_id',data->>'warehouse_id','description',btrim(COALESCE(data->>'description','')),
 'lines',COALESCE(data->'lines',data->'items','[]'::jsonb))::text)
$$;
CREATE OR REPLACE FUNCTION quantity_physical_count_details(p_id bigint) RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT jsonb_build_object('count_id',c.count_id,'document_number',c.document_number,'count_date',c.count_date,
 'cutoff_date',c.cutoff_date,'warehouse_id',c.warehouse_id,'warehouse_code',w.warehouse_code,
 'warehouse_name',w.warehouse_name,'description',c.description,'status',c.status,'adjustment_id',c.adjustment_id,
 'lines',COALESCE(jsonb_agg(jsonb_build_object('count_line_id',l.count_line_id,'line_number',l.line_number,
 'variant_id',l.variant_id,'sku',v.sku,'product_name',p.product_name,'unit_code',u.code,
 'system_quantity',l.system_quantity,'counted_quantity',l.counted_quantity,'variance',l.variance,
 'positive_unit_cost_base',l.positive_unit_cost_base,'reason',l.reason,'note',l.note)
 ORDER BY l.line_number)FILTER(WHERE l.count_line_id IS NOT NULL),'[]'::jsonb))
 FROM physical_counts c JOIN warehouses w USING(warehouse_id) LEFT JOIN physical_count_lines l USING(count_id)
 LEFT JOIN product_variants v ON v.variant_id=l.variant_id LEFT JOIN products p ON p.product_id=v.product_id
 LEFT JOIN units_of_measure u ON u.unit_id=v.unit_id WHERE c.count_id=p_id GROUP BY c.count_id,w.warehouse_id
$$;

CREATE OR REPLACE FUNCTION quantity_create_physical_count(data jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE d date;cutoff date;wid bigint;descr text;lines jsonb;usr integer;key varchar;fp varchar;
 existing physical_counts%ROWTYPE;id bigint;number text;x jsonb;n integer:=0;v bigint;counted numeric;
 system_qty numeric;cost numeric;reason varchar;note text;
BEGIN
 BEGIN d:=(data->>'count_date')::date;cutoff:=COALESCE(NULLIF(data->>'cutoff_date','')::date,d);
  wid:=(data->>'warehouse_id')::bigint;usr:=NULLIF(data->>'created_by_id','')::integer;
 EXCEPTION WHEN others THEN RAISE EXCEPTION 'Count date, cutoff, warehouse, or user is invalid.' USING ERRCODE='check_violation';END;
 descr:=NULLIF(btrim(COALESCE(data->>'description','')),'');lines:=COALESCE(data->'lines',data->'items');
 key:=btrim(COALESCE(data->>'idempotency_key',''));
 IF d IS NULL OR cutoff>d OR lines IS NULL OR jsonb_typeof(lines)<>'array' OR jsonb_array_length(lines)=0 OR key=''
 THEN RAISE EXCEPTION 'Count date, valid cutoff, warehouse, lines, and idempotency key are required.' USING ERRCODE='check_violation';END IF;
 IF NOT EXISTS(SELECT 1 FROM warehouses WHERE warehouse_id=wid AND is_active) THEN RAISE EXCEPTION 'Count warehouse must be active.' USING ERRCODE='check_violation';END IF;
 fp:=quantity_count_fingerprint(data);PERFORM pg_advisory_xact_lock(hashtextextended(current_schema()||':count:'||key,0));
 SELECT * INTO existing FROM physical_counts WHERE idempotency_key=key FOR UPDATE;
 IF FOUND THEN IF existing.request_fingerprint=fp THEN RETURN jsonb_build_object('status','success','idempotent',true,
 'count_id',existing.count_id,'document_number',existing.document_number);END IF;
 RAISE EXCEPTION 'Idempotency key reused with different count data.' USING ERRCODE='unique_violation';END IF;
 number:=quantity_next_document_number('stock_count');PERFORM set_config('financee.count_engine','allowed',true);
 INSERT INTO physical_counts(document_number,count_date,cutoff_date,warehouse_id,description,status,
 idempotency_key,request_fingerprint,created_by)VALUES(number,d,cutoff,wid,descr,'submitted',key,fp,usr)RETURNING count_id INTO id;
 FOR x IN SELECT value FROM jsonb_array_elements(lines) LOOP n:=n+1;
  BEGIN v:=(x->>'variant_id')::bigint;counted:=(x->>'counted_quantity')::numeric;
   cost:=NULLIF(x->>'positive_unit_cost_base','')::numeric;
  EXCEPTION WHEN others THEN RAISE EXCEPTION 'Count line % contains invalid numbers.',n USING ERRCODE='check_violation';END;
  PERFORM quantity_validate_quantity(v,counted);system_qty:=quantity_stock_availability(v,wid,cutoff);
  reason:=btrim(COALESCE(x->>'reason',''));note:=NULLIF(btrim(COALESCE(x->>'note','')),'');
  IF reason='' THEN RAISE EXCEPTION 'Count line % requires a reason.',n USING ERRCODE='check_violation';END IF;
  IF counted>system_qty AND(cost IS NULL OR cost<=0 OR cost<>round(cost,6)) THEN
   RAISE EXCEPTION 'Surplus count line % requires an approved positive unit cost.',n USING ERRCODE='check_violation';END IF;
  INSERT INTO physical_count_lines(count_id,line_number,variant_id,system_quantity,counted_quantity,
   variance,positive_unit_cost_base,reason,note)VALUES(id,n,v,system_qty,counted,counted-system_qty,cost,reason,note);
 END LOOP;PERFORM set_config('financee.count_engine','',true);
 RETURN jsonb_build_object('status','success','idempotent',false,'count_id',id,'document_number',number);
END $$;

CREATE OR REPLACE FUNCTION quantity_approve_physical_count(p_id bigint,p_user integer) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE h physical_counts%ROWTYPE;l physical_count_lines%ROWTYPE;aid bigint;anum text;movement jsonb;
 gain numeric(24,6):=0;loss numeric(24,6):=0;line_cost numeric(24,6);jid bigint;jlines jsonb:='[]'::jsonb;
BEGIN
 SELECT * INTO h FROM physical_counts WHERE count_id=p_id FOR UPDATE;
 IF NOT FOUND OR h.status<>'submitted' THEN RAISE EXCEPTION 'Submitted count not found or already posted.' USING ERRCODE='check_violation';END IF;
 PERFORM quantity_lock_inventory_pairs((SELECT jsonb_agg(jsonb_build_object('warehouse_id',h.warehouse_id,'variant_id',variant_id))FROM physical_count_lines WHERE count_id=p_id));
 anum:=quantity_next_document_number('adjustment');PERFORM set_config('financee.count_engine','allowed',true);
 INSERT INTO inventory_adjustments(count_id,document_number,adjustment_date,warehouse_id,approved_by)
 VALUES(p_id,anum,h.count_date,h.warehouse_id,p_user)RETURNING adjustment_id INTO aid;
 FOR l IN SELECT * FROM physical_count_lines WHERE count_id=p_id ORDER BY line_number LOOP
  CONTINUE WHEN l.variance=0;
  movement:=quantity_post_stock_movement(CASE WHEN l.variance>0 THEN 'adjustment_in' ELSE 'adjustment_out' END,
   l.variant_id,h.warehouse_id,h.count_date,abs(l.variance),CASE WHEN l.variance>0 THEN l.positive_unit_cost_base ELSE NULL END,
   'physical_count',p_id,l.line_number,anum,p_user,l.reason);
  line_cost:=(movement->>'total_cost_base')::numeric;
  INSERT INTO inventory_adjustment_lines(adjustment_id,count_line_id,variant_id,quantity_difference,
   unit_cost_base,total_cost_base,reason,movement_id)VALUES(aid,l.count_line_id,l.variant_id,l.variance,
   round(line_cost/abs(l.variance),6),line_cost,l.reason,(movement->>'movement_id')::bigint);
  IF l.variance>0 THEN gain:=gain+line_cost;ELSE loss:=loss+line_cost;END IF;
 END LOOP;
 IF gain+loss>0 THEN
  IF gain>0 THEN jlines:=jlines||jsonb_build_array(
   jsonb_build_object('account_code','1400','debit',round(gain,4),'credit',0,'description','Count surplus inventory'),
   jsonb_build_object('account_code','4900','debit',0,'credit',round(gain,4),'description','Inventory adjustment gain'));END IF;
  IF loss>0 THEN jlines:=jlines||jsonb_build_array(
   jsonb_build_object('account_code','5900','debit',round(loss,4),'credit',0,'description','Inventory adjustment loss'),
   jsonb_build_object('account_code','1400','debit',0,'credit',round(loss,4),'description','Count shortage inventory'));END IF;
  jid:=quantity_post_journal(h.count_date,'Inventory adjustment '||anum,'inventory_adjustment',aid,anum,p_user,
   jlines);
 END IF;
 UPDATE inventory_adjustments SET gain_total_base=gain,loss_total_base=loss,journal_id=jid WHERE adjustment_id=aid;
 UPDATE physical_counts SET status='posted',adjustment_id=aid,approved_by=p_user,approved_at=CURRENT_TIMESTAMP,
  updated_at=CURRENT_TIMESTAMP WHERE count_id=p_id;
 PERFORM set_config('financee.count_engine','',true);
 RETURN jsonb_build_object('status','success','count_id',p_id,'adjustment_id',aid,'adjustment_number',anum,
  'gain_total_base',gain,'loss_total_base',loss,'journal_id',jid);
END $$;

CREATE OR REPLACE FUNCTION quantity_reverse_physical_count(p_id bigint,p_date date,p_user integer) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE h physical_counts%ROWTYPE;a inventory_adjustments%ROWTYPE;l record;layer fifo_layers%ROWTYPE;j bigint;
BEGIN
 SELECT * INTO h FROM physical_counts WHERE count_id=p_id FOR UPDATE;
 SELECT * INTO a FROM inventory_adjustments WHERE adjustment_id=h.adjustment_id FOR UPDATE;
 IF NOT FOUND OR h.status<>'posted' OR a.status<>'posted' THEN RAISE EXCEPTION 'Posted count adjustment not found.' USING ERRCODE='check_violation';END IF;
 IF p_date<h.count_date THEN RAISE EXCEPTION 'Reversal date precedes count date.' USING ERRCODE='check_violation';END IF;
 FOR l IN SELECT * FROM inventory_adjustment_lines WHERE adjustment_id=a.adjustment_id ORDER BY adjustment_line_id LOOP
  IF l.quantity_difference>0 THEN
   SELECT * INTO layer FROM fifo_layers WHERE inbound_movement_id=l.movement_id FOR UPDATE;
   IF NOT FOUND OR layer.remaining_quantity<>layer.original_quantity OR layer.layer_id<>(
    SELECT min(layer_id)FROM fifo_layers WHERE variant_id=l.variant_id AND warehouse_id=a.warehouse_id AND remaining_quantity>0
   )THEN RAISE EXCEPTION 'Surplus adjustment cannot be reversed after its stock order or quantity changed.' USING ERRCODE='check_violation';END IF;
  END IF;
  PERFORM quantity_reverse_stock_movement(l.movement_id,p_date,p_id*1000000+l.adjustment_line_id,p_user);
 END LOOP;
 IF a.journal_id IS NOT NULL THEN j:=quantity_reverse_journal(a.journal_id,p_date,'Reverse inventory adjustment '||a.document_number,p_user);END IF;
 PERFORM set_config('financee.count_engine','allowed',true);
 UPDATE inventory_adjustments SET status='reversed',reversal_journal_id=j,reversed_by=p_user,reversed_at=CURRENT_TIMESTAMP WHERE adjustment_id=a.adjustment_id;
 UPDATE physical_counts SET status='reversed',reversed_by=p_user,reversed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE count_id=p_id;
 PERFORM set_config('financee.count_engine','',true);
 RETURN jsonb_build_object('status','success','count_id',p_id,'adjustment_id',a.adjustment_id,'reversal_journal_id',j);
END $$;

CREATE OR REPLACE FUNCTION quantity_physical_count_navigate(action text,current_id bigint DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE id bigint;BEGIN CASE lower(COALESCE(action,'last'))
 WHEN 'current'THEN id:=current_id;WHEN 'previous'THEN SELECT max(count_id)INTO id FROM physical_counts WHERE count_id<current_id;
 WHEN 'next'THEN SELECT min(count_id)INTO id FROM physical_counts WHERE count_id>current_id;
 WHEN 'first'THEN SELECT min(count_id)INTO id FROM physical_counts;WHEN 'last'THEN SELECT max(count_id)INTO id FROM physical_counts;
 ELSE RAISE EXCEPTION 'Unknown navigation action.' USING ERRCODE='check_violation';END CASE;RETURN quantity_physical_count_details(id);END $$;
CREATE OR REPLACE FUNCTION quantity_physical_count_summary(from_date date DEFAULT NULL,to_date date DEFAULT NULL) RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT jsonb_build_object('count_total',count(*)::integer,'submitted_count',count(*)FILTER(WHERE c.status='submitted')::integer,
 'posted_count',count(*)FILTER(WHERE c.status='posted')::integer,'documents',COALESCE(jsonb_agg(jsonb_build_object(
 'count_id',c.count_id,'document_number',c.document_number,'count_date',c.count_date,'warehouse_code',w.warehouse_code,
 'status',c.status,'gain_total_base',COALESCE(a.gain_total_base,0),'loss_total_base',COALESCE(a.loss_total_base,0))
 ORDER BY c.count_id DESC),'[]'::jsonb))FROM physical_counts c JOIN warehouses w USING(warehouse_id)
 LEFT JOIN inventory_adjustments a ON a.adjustment_id=c.adjustment_id
 WHERE(from_date IS NULL OR c.count_date>=from_date)AND(to_date IS NULL OR c.count_date<=to_date)
$$;
INSERT INTO quantity_seed_registry(seed_key,seed_version,payload)VALUES('quantity.counts_adjustments',1,
'{"cutoff_snapshot":true,"approval_required":true,"gain_account":"4900","loss_account":"5900"}'::jsonb)
ON CONFLICT(seed_key)DO UPDATE SET seed_version=GREATEST(quantity_seed_registry.seed_version,EXCLUDED.seed_version),
payload=EXCLUDED.payload,applied_at=CURRENT_TIMESTAMP;
UPDATE tenant_schema_metadata SET version=GREATEST(version,12),applied_at=CURRENT_TIMESTAMP WHERE id=true AND family='quantity';
